### ISSUE TITLE
支持 Kubernetes 1.16

### ISSUE THREAD

**Issue by tzlaosiji** [KubeOperator/KubeOperator#102]
**请描述您的需求或者改进建议.**
支持 Kubernetes 1.16

**请描述你建议的实现方案**
支持 Kubernetes 1.16

**Comment by KubeOperator** [comment]
1.17 正式 release 后，我们会支持 1.16。 我们的策略是落后一个版本。

**Comment by KubeOperator** [comment]
2.2 版本已经解决
