### ISSUE TITLE
集群初次部署成功，内置应用的跳转链接无法使用

### ISSUE THREAD

**Issue by tzlaosiji** [KubeOperator/KubeOperator#103]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.1.36

**Bug 描述**
简要描述您碰到的问题
集群初次部署成功，内置应用的跳转链接无法使用。链接一直处于disable状态，无法点击。但从部署日志、状态检查、webkubectl去查pod状态来看，内置的应用应该都已经处于运行状态了。后来整个页面刷新后链接才可以点击，看来是状态判断问题？

**Bug 重现步骤**
1.  创建集群
2. 部署k8s集群
3. 部署成功后，内置应用跳转链接无法点击

**期待的正确结果**
正确情况下应该是什么样的？
部署成功后可以直接点击内置应用进行访问。

**截图**
如果有截图，请附上截图.

**Comment by KubeOperator** [comment]
最新版本已经fix
