### ISSUE TITLE
集群的健康状态页面无自动更新？

### ISSUE THREAD

**Issue by tzlaosiji** [KubeOperator/KubeOperator#104]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.1.36

**Bug 描述**
简要描述您碰到的问题
刚刚成功部署完k8s集群，在集群的“健康状态”页面查看，发现nodes一栏一直是红色的，等了段时间也没有变更状态，刷新后才变正常，是否需要增加自动刷新功能？或者增加一个刷新按钮？

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by KubeOperator** [comment]
@zhengkunwang223 考虑添加一下
