### ISSUE TITLE
主机信息没有及时更新

### ISSUE THREAD

**Issue by xiaomanong223** [KubeOperator/KubeOperator#111]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
V2.1
**Bug 描述**
简要描述您碰到的问题
创建集群提示我内存不足 然后我修改了虚拟机的配置
主机列表页面并没有及时更新 导致我创建集群仍然显示内存不足
**Bug 重现步骤**
添加主机 添加完之后修改主机内存 刷新主机列表页面 没有更新

**期待的正确结果**
正确情况下应该是什么样的？
修改主机内存之后 主机列表跟着更新
建议增加刷新按钮 
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/57124014/67839865-91d1ef00-fb2f-11e9-95c8-0390ec4a9a21.png)

**Comment by KubeOperator** [comment]
2.1.58 版本已经解决。
