### ISSUE TITLE
vSphere 5.5 + NFS + CentOS 7.6 这个组合符合条件吗？

### ISSUE THREAD

**Issue by addressone** [KubeOperator/KubeOperator#113]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
2.1

**Bug 描述**
简要描述您碰到的问题

vSphere 5.5 + NFS + CentOS 7.6 这个组合能够使用 KubeOperator 自动部署 K8s ？

**Comment by KubeOperator** [comment]
[v2.1.52](https://github.com/KubeOperator/KubeOperator/releases/tag/2.1.52) 版本已解决。
