### ISSUE TITLE
集群-备份/恢复--立即备份--备份的名称和备份时间时间不一致

### ISSUE THREAD

**Issue by xiaoning-1984** [KubeOperator/KubeOperator#116]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
2.1.42
**Bug 描述**
简要描述您碰到的问题
集群-备份/恢复--立即备份--备份的名称和备份时间时间不一致
**Bug 重现步骤**
1.  集群-备份/恢复--立即备份--备份的名称和备份时间时间不一致
 

**期待的正确结果**
正确情况下应该是什么样的？
时间一致
**截图**
如果有截图，请附上截图.
![图片](https://user-images.githubusercontent.com/57245636/68002990-7806e800-fca6-11e9-84a4-c9fe0b893d28.png)

**Comment by KubeOperator** [comment]
已经解决。
