### ISSUE TITLE
创建集群，配置检查未通过时，提示原因不明确

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [KubeOperator/KubeOperator#117]
**请描述您的需求或者改进建议.**

创建集群，配置检查未通过时，提示原因不明确

**请描述你建议的实现方案**
如检查操作系统未通过，提示用户kubeoperator支持的操作系统版本有哪些

![error](https://user-images.githubusercontent.com/46734380/68016396-7867a900-fccf-11e9-98dc-d9cdc6d06d5e.png)

**Comment by KubeOperator** [comment]
已经解决。
