### ISSUE TITLE
DNS问题请教

### ISSUE THREAD

**Issue by chiobit** [KubeOperator/KubeOperator#119]
部署后发现master会不断连114.114.114.114这个DNS，因不符合公司网路政策被挡下。请问是哪个环节需要不断对外连线?谢谢

**Comment by wanghe-fit2cloud** [comment]
需要手动修改master节点的dnsmasq配置文件（/etc/dnsmasq.d/kubeops-upstream.dns.conf）

支持自定义dns功能将在2.2版本中发布
