### ISSUE TITLE
【需求】支持和集成 Rook (Ceph)

### ISSUE THREAD

**Issue by addressone** [KubeOperator/KubeOperator#122]
**请描述您的需求或者改进建议.**

目前 KubeOperator 支持三种持久化存储，一是通过 vSphere Cloud Provider 支持 vSAN、VMFS等；二是通过 OpenStack Cloud Provider 支持 Cinder；三是独立 NFS 支持。希望能增加第四种方式，就是通过云原生存储编排框架 Rook 支持其他存储，特别是对 Ceph 的支持。

**请描述你建议的实现方案**

支持和集成 Rook。

**Comment by KubeOperator** [comment]
2.2 已经解决
