### ISSUE TITLE
vcenter 上没有集群时，创建 AZ 页面一直加载，无相关提示

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [KubeOperator/KubeOperator#124]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
版本: v2.1.52

**Bug 描述**
简要描述您碰到的问题
vcenter 中没有创建集群，在部署计划中创建区域完成后创建可用区时，一直处于加载页面，无错误提示。

**Bug 重现步骤**
1.  准备没有集群的 vcenter 账号
2.  添加区域
3.  添加可用区
4. 

**期待的正确结果**
在该页面弹出类似 ’所选 vcenter 区域中没有集群‘ 等提示信息

**Comment by KubeOperator** [comment]
2.2 已经解决。
