### ISSUE TITLE
安装停止在重启防火墙

### ISSUE THREAD

**Issue by 25280841** [KubeOperator/KubeOperator#132]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
2.15

**Bug 描述**
简要描述您碰到的问题
安装停止在master1重启防火墙
卡住不动

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![Uploading image.png…]()

**Comment by 25280841** [comment]
![image](https://user-images.githubusercontent.com/36323901/68412069-939e5100-01c6-11ea-9266-d96cd9ec6758.png)

**Comment by 25280841** [comment]
Step 6/24 : RUN cd /tmp/requirements && yum -y install epel-release && yum -y install $(cat rpm_requirements.txt)
 ---> Running in f8b07c2bbead
Loaded plugins: fastestmirror, ovl
Setting up Install Process
Determining fastest mirrors
Error: Cannot find a valid baseurl for repo: base
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=container error was
14: PYCURL ERROR 7 - "Failed to connect to 2607:f8f8:700:12::10: Network is unreachable"
ERROR: Service 'api' failed to build: The command '/bin/sh -c cd /tmp/requirements && yum -y install epel-release && yum -y install $(cat rpm_requirements.txt)' returned a non-zero code: 1
/vmnfs/kubeOperator-v2.1.54-release
start service......
 kubeOperator 安装成功!
 默认登陆信息: 
 username: admin 
 password: kubeoperator@admin123 
[root@master1 kubeOperator-v2.1.54-release]# ls /etc/yum.repos.d
bak  kubeops.repo
[root@master1 kubeOperator-v2.1.54-release]# ls /etc/yum.repos.d/bak
CentOS-Base.repo  CentOS-Debuginfo.repo  CentOS-Media.repo    CentOS-Vault.repo
CentOS-CR.repo    CentOS-fasttrack.repo  CentOS-Sources.repo  kubeops.repo

**Comment by KubeOperator** [comment]
@wanghe-fit2cloud 这个问题群里有人也碰到了。研究一下。

**Comment by KubeOperator** [comment]
@Aaron3S 好像问题和集群域名带中划线有关。

**Comment by KubeOperator** [comment]
一直未能重现，放到 2.3 版本观察。
