### ISSUE TITLE
多master集群时间不同步，导致创建集群失败

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [KubeOperator/KubeOperator#133]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.1.56

**Bug 描述**
简要描述您碰到的问题
创建多主集群失败
查看集群所有节点时间，发现集群内部时间不同步

**Bug 重现步骤**
1.  部署模型选择多主多节点
2. 安装集群
3. 安装worker节点失败 

**期待的正确结果**
正确情况下应该是什么样的？
1.将多master中的一个节点来作为chrony的主节点
2.能否支持自定义chrony server节点

**Comment by KubeOperator** [comment]
2.1.58，已解决。
