### ISSUE TITLE
使用手动录入的 NFS 创建集群失败

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [KubeOperator/KubeOperator#134]
**KubeOperator 版本**
版本：v2.1.56

**Bug 描述**
使用手动录入的 NFS 存储创建集群失败，前端页面无报错，后端返回 http 500，报错信息见截图

**Bug 重现步骤**
1. 添加手动录入的 NFS 存储
2. 创建集群
3. 
4. 

**期待的正确结果**
1. 可以使用手动录入的 NFS 存储创建集群
2. 集群创建异常时前端进行相关提示

**截图**
![image](https://user-images.githubusercontent.com/27671436/68468256-a3637700-0252-11ea-9b74-31a7874537f5.png)

**Comment by KubeOperator** [comment]
v2.1.58 版本已解决。
