### ISSUE TITLE
在vsphere 平台自动部署k8s集群失败

### ISSUE THREAD

**Issue by wml3** [KubeOperator/KubeOperator#135]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.1.54

**Bug 描述**
简要描述您碰到的问题
如题，使用自动部署模式，vcenter版本是6.5，esxi版本6.5，kubeoperator版本v2.1.54.包括2.1.58也有同样报错。

**Bug 重现步骤**
1. 正常添加plan，存储使用新建nfs
2. 新建集群并开始部署，创建虚机报错
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
正常应该进入虚拟机部署。查看cat /opt/kubeoperator/data/iso/vsphere/kubeoperator_centos_7.6.1810.ovf，这里模板的系统版本不正确，当前为“<OperatingSystemSection ovf:id="107" ovf:version="6" vmw:osType="centos6_64Guest">”，而OS为7.6，虚机的系统版本属性应为“<OperatingSystemSection ovf:id="107" ovf:version="7" vmw:osType="centos7_64Guest">”
手动修改后仍然不能正确进入部署
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/49503874/68525995-36afb180-0312-11ea-947d-9ae7bfdb9b6b.png)

**Comment by KubeOperator** [comment]
收到，我们正在调查。

**Comment by KubeOperator** [comment]
我们在 vSphere 6.7 上面测试都没有问题。我们想办法弄个 vSphere 6.5 环境来重现。

**Comment by wml3** [comment]
这模板拿出来在democenter手动克隆失败，在手动编辑属性时，一直刷不出来

![image](https://user-images.githubusercontent.com/49503874/68531161-52cf4500-034a-11ea-9b75-a46ef8141205.png)

![image](https://user-images.githubusercontent.com/49503874/68531172-6da1b980-034a-11ea-9b24-5c7461d6b7de.png)

![image](https://user-images.githubusercontent.com/49503874/68531183-932ec300-034a-11ea-8052-02eaffe93024.png)

**Comment by wml3** [comment]
模板原兼容性是支持esxi5.5以上 ，升级到6.5则可以编辑且能正常克隆。目前兼容的vcenter版本是哪些？

**Comment by KubeOperator** [comment]
@wml3 你找徐工，他会和你在 demo center 上面测试一下。我们的目标是支持 5.5 以上所有版本，当然 5.5 的不支持 vSAN。

**Comment by xuwei-fit2cloud** [comment]
@wml3 该环境内原有旧版本的 KubeOperator 导入的镜像 kubeoperator_centos_7.6.1810 存在这个问题，删除镜像后，新建可用区，由 KubeOperator 自动重新导入一个新镜像即可。
