### ISSUE TITLE
请问啥时候支持k8s的V1.16.2的版本？

### ISSUE THREAD

**Issue by arraycto** [KubeOperator/KubeOperator#136]
**请描述您的需求或者改进建议.**
请问啥时候支持k8s的V1.16.2的版本？

**请描述你建议的实现方案**
请问啥时候支持k8s的V1.16.2的版本？

**Comment by KubeOperator** [comment]
2.2 版本支持，目前正在持续测试中，预计 11 月 20 号左右发布。
