### ISSUE TITLE
请问这个软件能在公司用么，是免费的么？

### ISSUE THREAD

**Issue by arraycto** [KubeOperator/KubeOperator#137]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？

2.1.58最新版本

**Bug 描述**
请问大佬，这个软件能在公司用么，是免费的么？不敢用

**Bug 重现步骤**
1.  不敢随便用，请问大佬，这个软件能在公司用么，是免费的么？不敢用

**Comment by KubeOperator** [comment]
KubeOperator 是100% 开源，而且协议是 Apache 协议，请放心使用。

**Comment by arraycto** [comment]
收到，推荐更多的同行使用，且已经star

**Comment by KubeOperator** [comment]
感谢，一起努力，持续改进这个项目。
