### ISSUE TITLE
CentOS 7.5什么时候能支持啊，公司大部分都是7.5的系统

### ISSUE THREAD

**Issue by arraycto** [KubeOperator/KubeOperator#138]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
KubeOperator 2.1.58

 
 请问：什么时候支持centos7.5.x的内网os

**Comment by KubeOperator** [comment]
我们可以考虑测试下并解除限制。回头更新结论。

**Comment by KubeOperator** [comment]
7.4 和 7.5 一起测试和验证，如果没有问题，限制为 7.4，7.5，7.6，7.7

**Comment by KubeOperator** [comment]
预计2.2.x版本支持

**Comment by leffss** [comment]
下载的kubeOperator-v2.1.56-release.tar.gz，centos 7.5 可以用的，但是管理里面只有机器增加节点，没有减少节点，是版本的原因吗？

**Comment by KubeOperator** [comment]
2.2 已经解决。
