### ISSUE TITLE
最近一直在玩kubeoperator，有几点需求和问题，帮忙解答下吧

### ISSUE THREAD

**Issue by plateauandsp** [KubeOperator/KubeOperator#139]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
54版本

1.部署时候的安装目录不能修改，不能适配有强制部署规范
2.caclio的网络插件不能选择BGP模式，默认部署IP-IP模式
3.在vc删除模板后，新部署不会自动导入模块
4.人工导入模板需要干预调整模板的兼容性与操作系统类型
5.安装部署的过程中，刷新下浏览器任务记录就看不到了
6.任务历史日志无发定位查看和下拉，无法导出查看，无法查看全部
7.部署的过程中，直接进行卸载，然后再进行部署，平台报错，无法再进行部署
8.如果部署在自动创建主机环境报错，后续有可能卸载的时候不会卸载主机列表信息，会导致此集群一直无法在次部署，必须先删除集群在删除主机，然后新建集群

**Comment by KubeOperator** [comment]
收到，我们会一一进行分析和解决。

**Comment by KubeOperator** [comment]
@Aaron3S
