### ISSUE TITLE
KubeOperator 多系统单点登录咨询

### ISSUE THREAD

**Issue by chenpfeisoo** [KubeOperator/KubeOperator#145]
我看到官方的演示视频中，内置应用，通过KubeOperator 可以直接访问 granfana  监控， 等一些辅助三方系统 ，请问这块认证是怎么做？
是屏蔽了各个子系统的认证模块，使用 Gateway统一认证 还是？ 
对这块的技术比较好奇，麻烦官方解惑

**Comment by chenpfeisoo** [comment]
![image](https://user-images.githubusercontent.com/18147157/68820162-64577a80-06c5-11ea-956c-0b0aafda52bd.png)

**Comment by KubeOperator** [comment]
我的想法是起一个 keyclock-proxy  watch 所有的namespace 下的 deployment   只要 在deployment 中声明了要使用我的认证系统 我就在这个pod中注入一个容器用来拦截，这样的话在kubeoperator侧启动一个keyclock-server 作为proxy 的上游 就能在这一侧做所有内置应用的认

**Comment by chenpfeisoo** [comment]
好的 ，感谢 官方回复
