### ISSUE TITLE
kubeOperator-v2.1.58-release安装报错

### ISSUE THREAD

**Issue by ckgmg** [KubeOperator/KubeOperator#147]
**KubeOperator 版本**
kubeOperator-v2.1.58-release

**Bug 描述**
TASK [cluster-storage : 轮询等待 storageclass验证结果] *********************************
FAILED - RETRYING: 轮询等待 storageclass验证结果 (10 retries left).
FAILED - RETRYING: 轮询等待 storageclass验证结果 (9 retries left).
FAILED - RETRYING: 轮询等待 storageclass验证结果 (8 retries left).
FAILED - RETRYING: 轮询等待 storageclass验证结果 (7 retries left).
FAILED - RETRYING: 轮询等待 storageclass验证结果 (6 retries left).
FAILED - RETRYING: 轮询等待 storageclass验证结果 (5 retries left).
FAILED - RETRYING: 轮询等待 storageclass验证结果 (4 retries left).
FAILED - RETRYING: 轮询等待 storageclass验证结果 (3 retries left).
FAILED - RETRYING: 轮询等待 storageclass验证结果 (2 retries left).
FAILED - RETRYING: 轮询等待 storageclass验证结果 (1 retries left).
master1.kb1.mydomain.com | FAILED | rc=0 >>
Pending

NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
master1.kb1.mydomain.com   : ok=8    changed=7    unreachable=0    failed=1   
Unexpect error occur: playbook: addon error!
playbook: addon error!
Traceback (most recent call last):
  File "/opt/kubeOperator-api/kubeops_api/models/deploy.py", line 53, in start
    result = self.on_install(extra_vars)
  File "/opt/kubeOperator-api/kubeops_api/models/deploy.py", line 129, in on_install
    return self.run_playbooks(extra_vars)
  File "/opt/kubeOperator-api/kubeops_api/models/deploy.py", line 222, in run_playbooks
    raise RuntimeError("playbook: {} error!".format(step['playbook']))
RuntimeError: playbook: addon error!
Task kubeops_api.tasks.start_deploy_execution[77334826-7e22-4c47-9f09-62213c4b0806] succeeded in 1139.850583503s: {'raw': {}, 'summary': {'error': 'Unexpect error occur: playbook: addon error!'}}

**Comment by KubeOperator** [comment]
NFS 存储有问题，你从worker 节点看能否 mount 上，并确认权限。

**Comment by KubeOperator** [comment]
请加 qq 群获取技术支持。

**Comment by ckgmg** [comment]
OK了，原来是我NFS存储服务没有随系统启动
