### ISSUE TITLE
集群的主机无法删除

### ISSUE THREAD

**Issue by ckgmg** [KubeOperator/KubeOperator#149]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？

**Bug 描述**
1：主机关机中，页面还显示在运行中
2：删除主机，页面为灰色，不能点，（主机已经关机）
3：集群无法删除，也删除页面

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/49260651/68911960-ae0d9700-0791-11ea-81e3-ea26d799d4af.png)

![image](https://user-images.githubusercontent.com/49260651/68912113-178da580-0792-11ea-8a73-df2c8945bca2.png)

**Comment by ckgmg** [comment]
集群主机全部已经关机，
集群状态还是运行中

![image](https://user-images.githubusercontent.com/49260651/68912272-a1d60980-0792-11ea-9f67-c3ac547aeddc.png)

**Comment by Aaron3S** [comment]
集群需要先卸载再关机

**Comment by cnwelee** [comment]
**提个无法删除主机的场景**：

添加主机的时候使用的凭据是 非root账号 导致集群手动安装失败（在自行准备的主机上规划、部署及运营 K8s 集群方式）

[这种场景下无法正常卸载集群（点集群卸载是无法正确卸载的），无法删除集群，无法删除主机，无法为主机变更凭据……就很僵]

以上，问题可复现。

**Comment by youliyuan-fit2cloud** [comment]
> **提个无法删除主机的场景**：
> 
> 添加主机的时候使用的凭据是 非root账号 导致集群手动安装失败（在自行准备的主机上规划、部署及运营 K8s 集群方式）
> 
> [这种场景下无法正常卸载集群（点集群卸载是无法正确卸载的），无法删除集群，无法删除主机，无法为主机变更凭据……就很僵]
> 
> 以上，问题可复现。

临时解决办法：集群概览页-重置状态为卸载或就绪--删除集群-删除主机，试试看～
然后以root账号重新添加主机，再安装部署集群。

**Comment by cnwelee** [comment]
> > **提个无法删除主机的场景**：
> > 添加主机的时候使用的凭据是 非root账号 导致集群手动安装失败（在自行准备的主机上规划、部署及运营 K8s 集群方式）
> > [这种场景下无法正常卸载集群（点集群卸载是无法正确卸载的），无法删除集群，无法删除主机，无法为主机变更凭据……就很僵]
> > 以上，问题可复现。
> 
> 临时解决办法：集群概览页-重置状态为卸载或就绪--删除集群-删除主机，试试看～
> 然后重启主机之后以root账号重新添加主机，再安装部署集群。

集群概览页可以重置成就绪态（重置只有两个选项“就绪”和“运行中”），但是重置之后删除集群依然报错（删除失败undefined
）无法删除
