### ISSUE TITLE
多master安装错误

### ISSUE THREAD

**Issue by ckgmg** [KubeOperator/KubeOperator#150]
ok: [master2.kb2.mydomain.com] => (item=portmap)
ok: [master3.kb2.mydomain.com] => (item=portmap)
changed: [master1.kb2.mydomain.com] => (item=portmap)
TASK [flannel : 运行 flannel网络] **************************************************
master2.kb2.mydomain.com | SUCCESS | rc=0 >>
clusterrole.rbac.authorization.k8s.io/flannel created
clusterrolebinding.rbac.authorization.k8s.io/flannel created
serviceaccount/flannel created
configmap/kube-flannel-cfg created
daemonset.extensions/kube-flannel-ds-amd64 created

TASK [flannel : 删除默认cni配置] *****************************************************
changed: [worker1.kb2.mydomain.com]
changed: [master2.kb2.mydomain.com]
changed: [master1.kb2.mydomain.com]
changed: [master3.kb2.mydomain.com]
TASK [flannel : 轮询等待flannel 运行，视下载镜像速度而定] **************************************
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (15 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (15 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (15 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (15 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (14 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (14 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (14 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (14 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (13 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (13 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (13 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (13 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (12 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (12 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (12 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (12 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (11 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (11 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (11 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (11 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (10 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (10 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (10 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (10 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (9 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (9 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (9 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (9 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (8 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (8 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (7 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (7 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (6 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (6 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (8 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (5 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (5 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (8 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (7 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (4 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (4 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (7 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (6 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (6 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (3 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (3 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (5 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (5 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (4 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (4 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (1 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (1 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (3 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (3 retries left).
master3.kb2.mydomain.com | FAILED | rc=0 >>
Unable to connect to the server: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

master1.kb2.mydomain.com | FAILED | rc=0 >>
Unable to connect to the server: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (2 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (1 retries left).
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (1 retries left).
master2.kb2.mydomain.com | FAILED | rc=0 >>
Unable to connect to the server: net/http: TLS handshake timeout

worker1.kb2.mydomain.com | FAILED | rc=0 >>
Unable to connect to the server: net/http: TLS handshake timeout

PLAY RECAP *********************************************************************
master1.kb2.mydomain.com   : ok=4    changed=3    unreachable=0    failed=1   
master2.kb2.mydomain.com   : ok=7    changed=4    unreachable=0    failed=1   
master3.kb2.mydomain.com   : ok=4    changed=1    unreachable=0    failed=1   
worker1.kb2.mydomain.com   : ok=37   changed=28   unreachable=0    failed=1   
Unexpect error occur: playbook: worker error!
playbook: worker error!
Traceback (most recent call last):
  File "/opt/kubeOperator-api/kubeops_api/models/deploy.py", line 53, in start
    result = self.on_install(extra_vars)
  File "/opt/kubeOperator-api/kubeops_api/models/deploy.py", line 129, in on_install
    return self.run_playbooks(extra_vars)
  File "/opt/kubeOperator-api/kubeops_api/models/deploy.py", line 222, in run_playbooks
    raise RuntimeError("playbook: {} error!".format(step['playbook']))
RuntimeError: playbook: worker error!
Task kubeops_api.tasks.start_deploy_execution[ce6c8849-e4af-43e9-a2ca-d09596b794dd] succeeded in 10253.50713772999s: {'raw': {}, 'summary': {'error': 'Unexpect error occur: playbook: worker error!'}}

**Comment by KubeOperator** [comment]
2.2 已经解决，DNS 问题。
