### ISSUE TITLE
全新部署后K8S pod 内 DNS 无法解析域名了，求指教，到底那个环节出了问题呢？

### ISSUE THREAD

**Issue by bingoku** [KubeOperator/KubeOperator#151]
**KubeOperator 版本**

版本: v2.1.58

**Bug 描述**

部署后，完全没有任何手动的改过任何地方。是模拟了一些情况。刚开始是一个worker1后面有部署了worker2，用了几个小时后又部署了worker3.就这样的过程。然后就遇到了下面情况。

使用了 KubeOperator 部署了一个完整的 k8s ，刚开始挺好的，各种指标，验证都很不错。用了几天后发现 coredns 崩了一个。我就重新删掉启了一个。当时没注意看日志。随后，coredns 正常起来了。但是过一会儿就发现，集群中的部署的 pod 应用，容器内部无法解析域名了。

**Bug 重现步骤**
master worker 主机上的 resolv.conf
# 部署后默认都是 3 个 master 的 主机 IP
```
nameserver 10.8.200.166
nameserver 10.8.200.100
nameserver 10.8.200.30
```

# 随后我查看 pod 内部的 resolv.conf
```
[root@ngx-577c8b668c-gz2zp conf]# cat /etc/resolv.conf
nameserver 10.68.0.2search devops.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```
容器内部 去 ping或者 dig  www.baidu.com 还是 ping 内部域名结果都是无法解析

```
[root@ngx-577c8b668c-gz2zp conf]# ping www.baidu.com
ping: www.baidu.com: Name or service not known
```
容器内部 去 ping或者 dig  内部域名结果都是无法解析
```
[root@ngx-577c8b668c-gz2zp conf]# ping codisfe.apps.local-dev-k8s.dev-kubeoperator.xzy.io 
ping: codisfe.apps.local-dev-k8s.dev-kubeoperator.xzy.io: Name or service not known
```

**期待的正确结果**
正常情况，pod 内部应该可以互相解析域名内部域名吧？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/4134788/68988081-ecc44f80-086c-11ea-88c2-e97d6910910b.png)

![image](https://user-images.githubusercontent.com/4134788/68988084-f77ee480-086c-11ea-9e7a-0f1a14e93d0a.png)

![image](https://user-images.githubusercontent.com/4134788/68988096-209f7500-086d-11ea-82cc-6d1526c60ce2.png)

**Comment by KubeOperator** [comment]
2.2 版本已修复。
