### ISSUE TITLE
系统配置最低要求？

### ISSUE THREAD

**Issue by 296468465** [KubeOperator/KubeOperator#153]
本地电脑开发电脑，用虚拟机模拟部署。
是否必须准守最低配置要求，可能本地电脑没有这么高的配置

**Comment by KubeOperator** [comment]
我们建议2核8G，以避免内存不够导致的各种异常错误。

**Comment by leitinglvke** [comment]
怎么修改配置要求？我修改了 cluster/config.yml内存要求，但是不生效。
