### ISSUE TITLE
内置应用grafana无法访问，使用google浏览器，其他内置应用都正常

### ISSUE THREAD

**Issue by ckgmg** [KubeOperator/KubeOperator#157]
![image](https://user-images.githubusercontent.com/49260651/69314528-567a9a00-0c6f-11ea-9b94-62862cbe0851.png)

**Comment by Aaron3S** [comment]
kubectl get pod --all-namespaces 看看grafana pod 是否处于错误状态

**Comment by ckgmg** [comment]
monitoring    f2c-grafana-977b8dcf8-44lkk                                     0/1     CrashLoopBackOff   31         2d21h
请问如何操作

**Comment by ckgmg** [comment]
解决方法：是由于nfs没有权限，chmkod 777 nfs,
kubectl delete pop f2c-grafana-977b8dcf8-44lk -n monitoring重建，
