### ISSUE TITLE
求助：集群安装是报错！

### ISSUE THREAD

**Issue by seanminij** [KubeOperator/KubeOperator#160]
在集群安装过程有如下报错：

PLAY RECAP *********************************************************************
master1.yccluster.yccloud.com : ok=18   changed=6    unreachable=0    failed=0
worker1.yccluster.yccloud.com : ok=22   changed=8    unreachable=0    failed=0
PLAY [prepare kube bin files] **************************************************
TASK [Gathering Facts] *********************************************************
ok: [localhost]
TASK [kube-bin : Create some directory for doing work in] **********************
ok: [localhost]
TASK [kube-bin : debug] ********************************************************
ok: [localhost] => {
    "msg": "Create temp dir /opt/kubeOperator-kube-bin/1.16.2"
}
TASK [kube-bin : Download bin kube file] ***************************************
localhost | FAILED! => {
    "changed": false,
    "dest": "/opt/kubeOperator-kube-bin/1.16.2/k8s.1-16-2.tar.gz",
    "msg": "Request failed: <urlopen error [Errno 113] 没有到主机的路由>",
    "state": "absent",
    "url": "http://192.168.36.181:8085/repository/raw/1.16.2/k8s.1-16-2.tar.gz"
}
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   
:cluster yccluster exec install error
NoneType: None

**Comment by seanminij** [comment]
补充：“/var/lib/docker/overlay2/66900a46872cd1e12866b9a6f86f0fb31b2afb4e265f4a91ee82027e23677b15/merged/opt/kubeOperator-kube-bin/1.16.2/k8s.1-16-2.tar.gz” 看到目录有这个文件，url的地址和端口都没有，能wget到这文件。但是报这个错误。很纳闷。
![image](https://user-images.githubusercontent.com/58322738/69850460-47709900-12ba-11ea-9a2d-7dba76bcb359.png)

**Comment by wanghe-fit2cloud** [comment]
1、确认kubeoperator部署机防火墙是否为开启状态
2、关闭防火墙(systemctl stop firewalld.service)
3、重启docker(systemctl restart docker.service)
4、重启kubeops(systemctl restart kubeops.service)
5、重新安装

可以添加技术交流群（见README沟通交流）

**Comment by seanminij** [comment]
依照你说的操作了，但是还是提示错误。
![企业微信截图_15753359499865](https://user-images.githubusercontent.com/58322738/70012033-0fb16c00-15ae-11ea-8b85-5b70afe1b43c.png)

**Comment by yule-sun** [comment]
部署过程中会启用防火墙，按照他官网的方式加一下防火墙规则。
 启动防火墙
$ systemctl start firewalld
# 加入开机自动启动
$ systemctl enable firewalld
# 开放端口
$ firewall-cmd --zone=public --add-port=80/tcp --permanent
$ firewall-cmd --zone=public --add-port=8080-8089/tcp --permanent
$ firewall-cmd --zone=public --add-port=8090-8099/tcp --permanent
# 重新加载防火墙配置使生效
$ firewall-cmd --reload
# 查看防火墙状态
$ firewall-cmd --list-all
