### ISSUE TITLE
集群部署错误'dict object' has no attribute 'address'

### ISSUE THREAD

**Issue by lazyii** [KubeOperator/KubeOperator#161]
kubeOperator:2.2.28

TASK [etcd : 分发证书相关] ***********************************************************
ok: [master1.cluster3.kube.com -> None] => (item=ca.pem)
ok: [master1.cluster3.kube.com -> None] => (item=ca-key.pem)
ok: [master1.cluster3.kube.com -> None] => (item=ca-config.json)
TASK [etcd : 创建etcd证书请求] *******************************************************
master1.cluster3.kube.com | FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'address'"
}
PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=0
master1.cluster3.kube.com  : ok=64   changed=24   unreachable=0    failed=1   
worker1.cluster3.kube.com  : ok=33   changed=9    unreachable=0    failed=0
:cluster cluster3 exec install error

**Comment by KubeOperator** [comment]
已fix

**Comment by lazyii** [comment]
666.最近发版吗? @KubeOperator

**Comment by KubeOperator** [comment]
周二晚上发新的版本，在测试中了。
