### ISSUE TITLE
GPU 支持

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#164]
支持 GPU，运行机器学习、通用 GPU、高性能计算，以及受益于专用硬件加速器的其他工作负载。

**Comment by maninhill** [comment]
https://github.com/AliyunContainerService/gpushare-scheduler-extender

**Comment by KubeOperator** [comment]
https://github.com/NVIDIA/deepops

**Comment by KubeOperator** [comment]
https://docs.nvidia.com/datacenter/kubernetes/kubernetes-upstream/index.html

**Comment by KubeOperator** [comment]
已解决。
