### ISSUE TITLE
vCenter 密码中含有 $ 符导致存储配置失败

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [KubeOperator/KubeOperator#166]
**KubeOperator 版本**
v2.2.28

**Bug 描述**
vCenter 的密码中存在 $ 符，使用 vsphere datastore 类型的存储自动安装集群时配置并验证 StorageClass 环节失败。
由于密码中存在 $ 符，在使用 govc 获取虚拟机信息时 $ 未被转义，导致使用的密码不正确，未能正常获取虚拟机信息并更新 node 信息。

**Bug 重现步骤**
1. vcenter 密码修改为带有 $ 符的密码，并配置区域、可用区及部署计划
2. 部署集群，存储选择 vsphere datastore
3. 验证 Storage Class 环节报错
4. 

**期待的正确结果**
正常创建 PVC

**Comment by KubeOperator** [comment]
已经解决。
