### ISSUE TITLE
内置应用 Grafana和Prometheus "404 page not found"

### ISSUE THREAD

**Issue by seanminij** [KubeOperator/KubeOperator#167]
问题描述：
打开内置应用 Grafana和Prometheus都显示 404报错。其他应用都正常。
![157535903022](https://user-images.githubusercontent.com/58322738/70031630-a1d56680-15e6-11ea-896c-c998f0b4075b.png)

**Comment by youliyuan-fit2cloud** [comment]
> 问题描述：
> 打开内置应用 Grafana和Prometheus都显示 404报错。其他应用都正常。
> ![157535903022](https://user-images.githubusercontent.com/58322738/70031630-a1d56680-15e6-11ea-896c-c998f0b4075b.png)

您好～
这个问题在新版本中没有复现，建议使用v2.2.32 版本，谢谢～

**Comment by tanmx** [comment]
我也是同样的情况 release 2.3.2
有 grafana 的安装task
![x1.png](https://i.loli.net/2019/12/08/Um2dBvsgyGe6LxT.png)

但是没有 grafana的 namespace
![x2.png](https://i.loli.net/2019/12/08/DJq7KFsZwLvrdeW.png)

**Comment by wanghe-fit2cloud** [comment]
问题原因在于node节点间pod ip 不通导致的apiservice v1beta1.metrics.k8s.io不可用

建议准备全新的服务器 重新添加主机、添加集群 安装部署
或者卸载现有集群，手动删除flannel或calico等网卡（卸载不完全导致）

后期版本会优化卸载脚本
