### ISSUE TITLE
默认密码无法登录

### ISSUE THREAD

**Issue by hongtao7964** [KubeOperator/KubeOperator#168]
2.2.28版本。布署完成后使用默认密码admin / kubeoperator@admin123 无法登录。提示“用户密码错语”；

**Comment by huperzhao** [comment]
请问你的KubeOperator 管理控制台的地址多少，我这访问总是502 Bad Gateway，我用的VM按照教程装的KubeOperator

**Comment by youliyuan-fit2cloud** [comment]
> 请问你的KubeOperator 管理控制台的地址多少，我这访问总是502 Bad Gateway，我用的VM按照教程装的KubeOperator

地址是部署KubeOperator的机器ip地址。例如： 部署KubeOperator的地址是192.168.1.100，KubeOperator 管理控制台登录地址即为 ：192.168.1.100
安装成功后，需要等服务全部启动才能登录KubeOperator 管理控制台，可以在部署机器上执行命令：docker ps -a 查看所有服务是否启动。

**Comment by hongtao7964** [comment]
是的.docker服务都启动了。地址也对。防火墙。selinux都关了。就是提示密码不对哟。不知道什么原因。






在 2019-12-04 14:22:39，"youliyuan-fit2cloud" <notifications@github.com> 写道：


请问你的KubeOperator 管理控制台的地址多少，我这访问总是502 Bad Gateway，我用的VM按照教程装的KubeOperator

地址是部署KubeOperator的机器ip地址。例如： 部署KubeOperator的地址是192.168.1.100，KubeOperator 管理控制台登录地址即为 ：192.168.1.100
安装成功后，需要等服务全部启动才能登录KubeOperator 管理控制台，可以在部署机器上执行命令：docker ps -a 查看所有服务是否启动。

**Comment by J2AZYZ** [comment]
我的也无法登录，请求400了，没法用啊

**Comment by purplepalmdash** [comment]
删除本地卷后，重新初始化，有可能恢复正常

```
cd /opt/kubeoperator
docker-compose down
docker volume ls | sed -n '1!p' | awk {'print $2'} | xargs -I % docker volume rm %
docker-compose up -d
```
