### ISSUE TITLE
v2.1版本无法创建可用区，一直在转圈圈

### ISSUE THREAD

**Issue by wucaitian** [KubeOperator/KubeOperator#169]
**KubeOperator 版本**
所使用的 KubeOperator 版本是v2.1

**Bug 描述**
KeyError at /api/v1/cloud/sz/zone/
'resourcePool'
Request Method:	GET
Request URL:	http://10.238.239.28/api/v1/cloud/sz/zone/
Django Version:	2.1.11
Exception Type:	KeyError
Exception Value:	
'resourcePool'
Exception Location:	/opt/kubeOperator-api/cloud_provider/clients/vsphere.py in list_zone, line 51
Python Executable:	/usr/bin/python
Python Version:	3.6.1
Python Path:	
['/usr/local/lib/python3.6/site-packages/git/ext/gitdb',
 '/opt/kubeOperator-api',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/opt/kubeOperator-api',
 '/usr/local/lib/python3.6/site-packages/gitdb/ext/smmap']
Server time:	Tue, 3 Dec 2019 11:49:11 +0000

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**

**截图**

**Comment by KubeOperator** [comment]
如果方便的话，请升级到最新版本，应该已经修复了。
