### ISSUE TITLE
集群初次部署成功，内置应用的跳转链接无法访问

### ISSUE THREAD

**Issue by gst6062825** [KubeOperator/KubeOperator#170]
**KubeOperator 版本**
kubeoperator-v2.1.58-release

**Bug 描述**
环境：win7工作站，Oracle VM VirtualBox6.0，安装4个centos7虚拟机kubeOperator,Master,
Worker,NFS。所有虚拟机器ip地址和本地宿主机在同一网段10.192.26.0/32。集群初次部署成功，网络策略为flannel host-gw。
问题：目前问题表现为在kubeOperator机器上访问curl http://dashboard/apps.carnet.leapmotor.com可以访问，但是在本地宿主机通过10.192.26.164/ui/kubeOperator/cluster/carnet/apps页面中各个内置应用的“转到”链接，无法访问此网站

**Bug 重现步骤**
1.  按KubeOperator-v2.2 第四部分教程，手动模式搭建集群
2. 集群搭建成功后，在kubeOperator管理平台集群内置应用，点击转到链接
3. 显示网站无法访问
4. 

**期待的正确结果**
宿主机相对于kubeopertor集群是否属于外部网络，访问内置应用是否需要转发

**截图**
如果有截图，请附上截图.

**Comment by KubeOperator** [comment]
是否配置了域名解析 或者在client 写了hosts文件

**Comment by gst6062825** [comment]
> 是否配置了域名解析 或者在client 写了hosts文件

![image](https://user-images.githubusercontent.com/17375688/71428384-69174180-26fb-11ea-94d7-883aeeaef2bb.png)

**Comment by gst6062825** [comment]
> 是否配置了域名解析 或者在client 写了hosts文件
宿主机hosts文件配置如下：
10.192.26.148 grafana.apps.carnet.leapmotor.com
10.192.26.148 prometheus.apps.carnet.leapmotor.com
10.192.26.148 registry-ui.apps.carnet.leapmotor.com
10.192.26.148 dashboard.apps.carnet.leapmotor.com
10.192.26.148 traefik.apps.carnet.leapmotor.com
10.192.26.148 scope.weave.apps.carnet.leapmotor.com

**Comment by gst6062825** [comment]
问题已解决，是由于宿主机配置了网络代理的原因
