### ISSUE TITLE
KubeOperator服务器的IP变更，原有集群的运维操作出错

### ISSUE THREAD

**Issue by tzlaosiji** [KubeOperator/KubeOperator#172]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.2.32

**Bug 描述**
简要描述您碰到的问题
由于网络内IP冲突，KubeOperator服务器的原有IP被占，做了IP变更后，重启了docker及KubeOperator服务，但对原有集群进行k8s版本升级时提示的下载地址还是以前那个IP，导致无法升级。

**Comment by youliyuan-fit2cloud** [comment]
该问题已修复，下个版本发布后解决～
