### ISSUE TITLE
在停止docker服务的情况下进行KubeOperator升级会升级失败

### ISSUE THREAD

**Issue by tzlaosiji** [KubeOperator/KubeOperator#173]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.2.32

**Bug 描述**
简要描述您碰到的问题
今天下了最新版本的KubeOperator，就准备对原有的KubeOperator进行升级。但由于网络内IP冲突的问题（见issue #172 ）而重置了IP，期间将docker服务给停止了。

升级过程中没有报任何错误，也提示升级成功了。升级过程中给出的打印信息中有“加载镜像”、“移除镜像”等操作提示，我觉得docker服务停止了这些操作应该会失败。在升级命令执行完成后，把docker服务启动，检查镜像，发现镜像确实没有升级。在docker服务启动状态下重新升级后解决了问题。

希望升级脚本能对服务环境判断的更准确一些。

**Comment by xuwei-fit2cloud** [comment]
已经在升级脚本中添加了对docker服务状态的判断，在下一次发布的版本中会解决这个问题。
