### ISSUE TITLE
平台日志存储在哪里？历史任务失败怎么取消？

### ISSUE THREAD

**Issue by yule-sun** [KubeOperator/KubeOperator#174]
问题：集群扩容时显示状态Pending，如何排错，找不到日志，不知道如何取消任务。
![image](https://user-images.githubusercontent.com/37107125/70203319-69a16580-1757-11ea-9571-abc52f83b953.png)

**请描述你建议的实现方案**

**Comment by KubeOperator** [comment]
celery 由于未知的原因进入了pending 状态,可以重新启动 kubeops_task 这个容器进程解决

**Comment by yule-sun** [comment]
> celery 由于未知的原因进入了pending 状态,可以重新启动 kubeops_task 这个容器进程解决

谢谢回复，我试着重启了kubeops_task容器，但是状态依然是pending。这个任务能够取消或者终止么？平台的日志是在什么地方呢？
![image](https://user-images.githubusercontent.com/37107125/70204559-0108b780-175c-11ea-9ffe-b61af37004a8.png)

**Comment by yule-sun** [comment]
奇奇怪怪的突然自己又好了
![image](https://user-images.githubusercontent.com/37107125/70207458-c6a41800-1765-11ea-913d-6b4464f5931d.png)

**Comment by KubeOperator** [comment]
可能由于任务队列拥堵造成了任务执行延后。
