### ISSUE TITLE
创建可用区配置网络时，增加 DNS 配置

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [KubeOperator/KubeOperator#175]
**请描述您的需求或者改进建议.**
创建可用区配置网络时，增加 DNS 配置。
vCenter 地址配置了域名访问，同时集群内 pod 也需要通过内部 DNS 访问其他系统。目前的方案自动部署节点创建后是没有配置 DNS 地址的，所有域名都无法解析。

**请描述你建议的实现方案**
在创建可用区配置网络时，增加 DNS 相关的配置，安装集群时自动配置节点的 DNS 地址。

**Comment by KubeOperator** [comment]
好的。在下一个版本会提供。
