### ISSUE TITLE
通过HTTPS反向代理访问 WebSocket 未使用 wss

### ISSUE THREAD

**Issue by 502647092** [KubeOperator/KubeOperator#176]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是 v2.2.32

**Bug 描述**
简要描述您碰到的问题
通过Nginx 反向代理访问 KubeOperator 日志请求后端WebSocket 提示 ws链接错误

**Bug 重现步骤**
1.  用Nginx反向代理访问KubeOperator

**期待的正确结果**
正确情况下应该是什么样的？
根据当前页面的情况选择wss或者ws

**截图**
如果有截图，请附上截图.

**Comment by KubeOperator** [comment]
收到，我们处理一下。

**Comment by 502647092** [comment]
@Aaron3S 这个问题修复了嘛 那个版本可以用了?
