### ISSUE TITLE
新建可用区报错

### ISSUE THREAD

**Issue by 502647092** [KubeOperator/KubeOperator#177]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是 2.2.35

**Bug 描述**
简要描述您碰到的问题

![image](https://user-images.githubusercontent.com/10203793/70404030-a92bc280-1a73-11ea-8e3a-50ca530a7d4e.png)

**Bug 重现步骤**
1.  新建区域 成功
2.  新建可用区 错误
3.  看起来是上传OS Image报错

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by KubeOperator** [comment]
vsphere 和 esxi 的版本是多少啊

**Comment by 502647092** [comment]
vsphere 6.7.0
esxi 6.7.0u3

**Comment by KubeOperator** [comment]
![image](https://user-images.githubusercontent.com/52770786/70491833-67674e80-1b3d-11ea-8af1-2bf4037b2bfc.png)
此目录下是否存在ovf

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/70492067-24f24180-1b3e-11ea-841b-64642a8a9775.png)

**Comment by KubeOperator** [comment]
1.
