### ISSUE TITLE
2.2.51默认密码错误

### ISSUE THREAD

**Issue by 905839698** [KubeOperator/KubeOperator#181]
2.2.51默认密码错误

**Comment by youliyuan-fit2cloud** [comment]
您好，我安装2.2.51版本没有复现这个问题。请在部署机器上执行命令：docker ps -a 查看所有服务是否启动。如果服务正常的话，尝试 重启，执行 docker-compose up -d  。

**Comment by hhl311** [comment]
同样的，2.2.51 登录失败。
/api/v1/api-token-auth/ 请求：{"username":"admin","password":"kubeoperator@admin123"}
返回：{"non_field_errors":["Unable to log in with provided credentials."]}

**Comment by zhengkunwang223** [comment]
> 同样的，2.2.51 登录失败。
> /api/v1/api-token-auth/ 请求：{"username":"admin","password":"kubeoperator@admin123"}
> 返回：{"non_field_errors":["Unable to log in with provided credentials."]}

已经找到问题了 是升级导致的BUG 马上修复 临时解决方案请加QQ群825046920或者微信wh_it0224 获取

**Comment by linou518** [comment]
报告：2.2.55还有同意的错误

**Comment by KubeOperator** [comment]
请加QQ群825046920或者微信wh_it0224 ，我们会协助解决。

**Comment by wuqionglei** [comment]
就不更新下？？？

**Comment by KubeOperator** [comment]
已经解决了，请升级到新版本。

**Comment by Chinaxiang** [comment]
2.2.74 安装的也有这个问题，400 bad requests.

**Comment by KubeOperator** [comment]
收到，我们再验证下。
