### ISSUE TITLE
请问有考虑过把ansible脚本独立出来吗？

### ISSUE THREAD

**Issue by mdh67899** [KubeOperator/KubeOperator#183]
**请描述您的需求或者改进建议.**
希望能够在不安装KubeOperator的情况下也能一键部署k8s集群
**请描述你建议的实现方案**
请问有没有计划将ansible脚本独立出来或者再建一个repo，供运维使用

**Comment by youliyuan-fit2cloud** [comment]
目前没有这个计划。
谢谢关注～

如有其他问题请加入下面QQ群或微信群交流～
技术交流 QQ 群
请加 QQ 群号：825046920
微信群
搜索微信号 wh_it0224，添加好友，备注（城市-github用户名）, 验证通过会加入群聊。

**Comment by mdh67899** [comment]
好的，感谢KubeOperator，只能读一下源码了解一下实现方式了
