### ISSUE TITLE
KubeOperator自身支持高可用，数据支持备份么？

### ISSUE THREAD

**Issue by BruceShenC** [KubeOperator/KubeOperator#184]
**请描述您的需求或者改进建议.**
由于集群信息通过KubeOperator管理，配置信息需要提供容错机制，比如KubeOperator所在机器宕机，磁盘损坏等
**请描述你建议的实现方案**
采用数据库，或者接口可以导出集群配置信息。

**Comment by youliyuan-fit2cloud** [comment]
KubeOperator目前版本还不支持自身高可用，后期版本会支持。敬请期待！
因为后端的数据存储是mysql ，数据备份用户可以自己做备份～

如有其他问题请加入下面QQ群或微信群交流～
技术交流 QQ 群
请加 QQ 群号：825046920
微信群
搜索微信号 wh_it0224，添加好友，备注（城市-github用户名）, 验证通过会加入群聊。

**Comment by KubeOperator** [comment]
KubeOperator 是一个旁路系统，KubeOperator 出现问题不会影响其创建和管理的 K8s  集群。

**Comment by BruceShenC** [comment]
明白，由于集群很多，希望可以用KubeOperator提供统一的界面来管理各种集群。
