### ISSUE TITLE
请问支持arm平台么？

### ISSUE THREAD

**Issue by BruceShenC** [KubeOperator/KubeOperator#186]
**请描述您的需求或者改进建议.**
k8s-package没有看到arm平台的二进制，请问支持arm么？

**请描述你建议的实现方案**
k8s-package加入arm支持

**Comment by zhengkunwang223** [comment]
我们有计划支持，包括华为的鲲鹏平台

**Comment by KubeOperator** [comment]
3.0 已经解决。
