### ISSUE TITLE
2.2.52版本创建完集群后，kubectl get cs获取到的组件状态和实际不符。

### ISSUE THREAD

**Issue by F-liuhui** [KubeOperator/KubeOperator#187]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
2.2.52
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
2.2.52版本，在集群创建完后，kubectl get cs 获取到etcd,scheduler,controller manager状态都是不可用，但实际都是可用的，这个是什么原因
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by KubeOperator** [comment]
请加QQ群825046920或者微信wh_it0224，我们会协助解决。
