### ISSUE TITLE
创建部署计划无法获取规格

### ISSUE THREAD

**Issue by trotyoung** [KubeOperator/KubeOperator#189]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.2.55
**Bug 描述**
简要描述您碰到的问题
参照https://docs.kubeoperator.io/kubeoperator-v2.1/userguide-openstack#13-%E5%87%86%E5%A4%87%E5%AD%98%E5%82%A8
在创建区域-->可用区-->部署计划的流程中，创建完可用区，在创建部署计划时，无法从Master 规格和Worker规格中选择flavor，系统也没有进行提示。
**Bug 重现步骤**
1.  创建部署计划
2. 配置计划

![image](https://user-images.githubusercontent.com/19234895/71337342-37309e80-2586-11ea-9679-d032813e8f00.png)

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zhengkunwang223** [comment]
> **KubeOperator 版本**
> 您所使用的 KubeOperator 版本是？
> v2.2.55
> **Bug 描述**
> 简要描述您碰到的问题
> 参照https://docs.kubeoperator.io/kubeoperator-v2.1/userguide-openstack#13-%E5%87%86%E5%A4%87%E5%AD%98%E5%82%A8
> 在创建区域-->可用区-->部署计划的流程中，创建完可用区，在创建部署计划时，无法从Master 规格和Worker规格中选择flavor，系统也没有进行提示。
> **Bug 重现步骤**
> 
> 1. 创建部署计划
> 2. 配置计划
> 
> ![image](https://user-images.githubusercontent.com/19234895/71337342-37309e80-2586-11ea-9679-d032813e8f00.png)
> 
> **期待的正确结果**
> 正确情况下应该是什么样的？
> 
> **截图**
> 如果有截图，请附上截图.
您好 浏览器页面邮件检查 然后选择Network label 查看是否报错
可以加QQ群 825046920 微信号 wh_it0224 方便交流

**Comment by fcmfcm01** [comment]
flavor 没有返回 

![image](https://user-images.githubusercontent.com/34680571/71439081-27a28880-2733-11ea-8eb5-e5e8e17bbd63.png)

**Comment by zhengkunwang223** [comment]
> flavor 没有返回
> 
> ![image](https://user-images.githubusercontent.com/34680571/71439081-27a28880-2733-11ea-8eb5-e5e8e17bbd63.png)

请问有flavor吗？没有的话需要创建

**Comment by fcmfcm01** [comment]
有 flavor的，但是跟core/apps/cloud_provider/clients/openstack.py里面获取flavor的期望值不一样，个人认为应该去掉限制，直接用拿到的flavor
`def get_flavors(self, region):
        openstack_client = get_openstack_client(self.vars, region)
        flavors = openstack_client.list_flavors()
        models = []
        for flavor in flavors:
            model = {
                    'name': flavor.name,
                    'meta': {
                        'id': flavor.id,
                        'cpu': flavor.vcpus,
                        'memory': flavor.ram / 1024,
                        'disk': flavor.disk
                    }
                }
                models.append(model)
        return models
`

**Comment by zhengkunwang223** [comment]
> openstack_client.list_flavors()

如果选的flavor太小 会影响到后面机器的创建 而且flavor可能会有上百个 所以我们加了一点限制 这样 我们考虑一下 设置一个最小值 最小值以上的全部显示

**Comment by fcmfcm01** [comment]
因为我装的OpenStack环境并不由我自己控制，资源的分配和flavor的配置都是由相应的人员来完成的，所以和你们的推荐配置可能不是很吻合， 这个是我的一个flavor信息：
```
+-------------+--------+------+-----------+-------+-----------+
| Name        |    RAM | Disk | Ephemeral | VCPUs | Is Public |
+-------------+--------+------+-----------+-------+-----------+
| el.024-0064 |  65536 |  512 |         0 |    24 | True      |
| ea.010-0032 |  32768 |  213 |         0 |    10 | True      |
| ea.002-0006 |   6242 |   43 |         0 |     2 | True      |
| ea.006-0016 |  16384 |  128 |         0 |     6 | True      |
| aa.001-0002 |   2048 |   25 |         0 |     1 | True      |
| ea.002-0008 |   8192 |   32 |         0 |     2 | True      |
| ea.012-0036 |  36864 |  256 |         0 |    12 | True      |
| el.052-0144 | 147456 | 1109 |         0 |    52 | True      |
| el.036-0096 |  98304 |  768 |         0 |    36 | True      |
| ea.004-0012 |  12288 |   85 |         0 |     4 | True      |
| ea.001-0002 |   2048 |   25 |         0 |     1 | True      |
| aa.002-0008 |   8192 |   32 |         0 |     2 | True      |
| ea.008-0024 |  24576 |  171 |         0 |     8 | True      |
| el.044-0128 | 131072 |  939 |         0 |    44 | True      |
| ea.016-0044 |  45056 |  341 |         0 |    16 | True      |
+-------------+--------+------+-----------+-------+-----------+
```
所以我的建议是可以把条件由**=**变成**>**, 这样相对来说更宽泛一点

**Comment by zhengkunwang223** [comment]
> 因为我装的OpenStack环境并不由我自己控制，资源的分配和flavor的配置都是由相应的人员来完成的，所以和你们的推荐配置可能不是很吻合， 这个是我的一个flavor信息：
> 
> ```
> +-------------+--------+------+-----------+-------+-----------+
> | Name        |    RAM | Disk | Ephemeral | VCPUs | Is Public |
> +-------------+--------+------+-----------+-------+-----------+
> | el.024-0064 |  65536 |  512 |         0 |    24 | True      |
> | ea.010-0032 |  32768 |  213 |         0 |    10 | True      |
> | ea.002-0006 |   6242 |   43 |         0 |     2 | True      |
> | ea.006-0016 |  16384 |  128 |         0 |     6 | True      |
> | aa.001-0002 |   2048 |   25 |         0 |     1 | True      |
> | ea.002-0008 |   8192 |   32 |         0 |     2 | True      |
> | ea.012-0036 |  36864 |  256 |         0 |    12 | True      |
> | el.052-0144 | 147456 | 1109 |         0 |    52 | True      |
> | el.036-0096 |  98304 |  768 |         0 |    36 | True      |
> | ea.004-0012 |  12288 |   85 |         0 |     4 | True      |
> | ea.001-0002 |   2048 |   25 |         0 |     1 | True      |
> | aa.002-0008 |   8192 |   32 |         0 |     2 | True      |
> | ea.008-0024 |  24576 |  171 |         0 |     8 | True      |
> | el.044-0128 | 131072 |  939 |         0 |    44 | True      |
> | ea.016-0044 |  45056 |  341 |         0 |    16 | True      |
> +-------------+--------+------+-----------+-------+-----------+
> ```
> 
> 所以我的建议是可以把条件由**=**变成**>**, 这样相对来说更宽泛一点

您的建议我们会参考 谢谢 现在这个版本建议您创建一个4c16G的flavor

**Comment by fcmfcm01** [comment]
另外 我在本地编docker镜像的时候遇到这个错误：
```
Running command git clone -q https://github.com/KubeOperator/python-terraform.git /tmp/pip-req-build-bq6k7csh
  error: The requested URL returned error: 403 Forbidden while accessing https://github.com/KubeOperator/python-terraform.git/info/refs

```
公开的目录里是找不到 https://github.com/KubeOperator/python-terraform.git

**Comment by zhengkunwang223** [comment]
> 另外 我在本地编docker镜像的时候遇到这个错误：
> 
> ```
> Running command git clone -q https://github.com/KubeOperator/python-terraform.git /tmp/pip-req-build-bq6k7csh
>   error: The requested URL returned error: 403 Forbidden while accessing https://github.com/KubeOperator/python-terraform.git/info/refs
> ```
> 
> 公开的目录里是找不到 https://github.com/KubeOperator/python-terraform.git

请问您是用什么命令编译的

**Comment by fcmfcm01** [comment]
在 KubeOperator/core/ 目录下， `docker build `

**Comment by zhengkunwang223** [comment]
> 在 KubeOperator/core/ 目录下， `docker build `

如果您想自己修改源码解除限制 我建议您在/opt/kubeoperator 里面修改代码 并执行docker-compose build api

**Comment by zhengkunwang223** [comment]
> 在 KubeOperator/core/ 目录下， `docker build `
> 
> 在第一次run `./kubeopsctl.sh install` 时也遇到了同样的错误

加微信号 wh_it0224 方便交流

**Comment by fcmfcm01** [comment]
已加wecha

> > 在 KubeOperator/core/ 目录下， `docker build `
> > 在第一次run `./kubeopsctl.sh install` 时也遇到了同样的错误
> 
> 加微信号 wh_it0224 方便交流

已加，请通过

**Comment by trotyoung** [comment]
> flavor 没有返回
> 
> ![image](https://user-images.githubusercontent.com/34680571/71439081-27a28880-2733-11ea-8eb5-e5e8e17bbd63.png)

确实有flavor不存在导致的。

**Comment by trotyoung** [comment]
> > flavor 没有返回
> > ![image](https://user-images.githubusercontent.com/34680571/71439081-27a28880-2733-11ea-8eb5-e5e8e17bbd63.png)
> 
> 请问有flavor吗？没有的话需要创建

嗯嗯，微信上得到解答了。
需要创建kubeoperator需要的flavor。我觉得这里可以给个提示，提示用户去创建响应的规格。

**Comment by KubeOperator** [comment]
非常好的建议，我们会加上提示。

**Comment by tjlygdx** [comment]
> 有 flavor的，但是跟core/apps/cloud_provider/clients/openstack.py里面获取flavor的期望值不一样，个人认为应该去掉限制，直接用拿到的flavor
> 
> ```
> def get_flavors(self, region):
>         openstack_client = get_openstack_client(self.vars, region)
>         flavors = openstack_client.list_flavors()
>         models = []
>         for flavor in flavors:
>             model = {
>                     'name': flavor.name,
>                     'meta': {
>                         'id': flavor.id,
>                         'cpu': flavor.vcpus,
>                         'memory': flavor.ram / 1024,
>                         'disk': flavor.disk
>                     }
>                 }
>                 models.append(model)
>         return models
> ```



> 因为我装的OpenStack环境并不由我自己控制，资源的分配和flavor的配置都是由相应的人员来完成的，所以和你们的推荐配置可能不是很吻合， 这个是我的一个flavor信息：
> 
> ```
> +-------------+--------+------+-----------+-------+-----------+
> | Name        |    RAM | Disk | Ephemeral | VCPUs | Is Public |
> +-------------+--------+------+-----------+-------+-----------+
> | el.024-0064 |  65536 |  512 |         0 |    24 | True      |
> | ea.010-0032 |  32768 |  213 |         0 |    10 | True      |
> | ea.002-0006 |   6242 |   43 |         0 |     2 | True      |
> | ea.006-0016 |  16384 |  128 |         0 |     6 | True      |
> | aa.001-0002 |   2048 |   25 |         0 |     1 | True      |
> | ea.002-0008 |   8192 |   32 |         0 |     2 | True      |
> | ea.012-0036 |  36864 |  256 |         0 |    12 | True      |
> | el.052-0144 | 147456 | 1109 |         0 |    52 | True      |
> | el.036-0096 |  98304 |  768 |         0 |    36 | True      |
> | ea.004-0012 |  12288 |   85 |         0 |     4 | True      |
> | ea.001-0002 |   2048 |   25 |         0 |     1 | True      |
> | aa.002-0008 |   8192 |   32 |         0 |     2 | True      |
> | ea.008-0024 |  24576 |  171 |         0 |     8 | True      |
> | el.044-0128 | 131072 |  939 |         0 |    44 | True      |
> | ea.016-0044 |  45056 |  341 |         0 |    16 | True      |
> +-------------+--------+------+-----------+-------+-----------+
> ```

我们把条件由**=**变成**>**, 这样相对来说更宽泛一点

> 因为我装的OpenStack环境并不由我自己控制，资源的分配和flavor的配置都是由相应的人员来完成的，所以和你们的推荐配置可能不是很吻合， 这个是我的一个flavor信息：
> 
> ```
> +-------------+--------+------+-----------+-------+-----------+
> | Name        |    RAM | Disk | Ephemeral | VCPUs | Is Public |
> +-------------+--------+------+-----------+-------+-----------+
> | el.024-0064 |  65536 |  512 |         0 |    24 | True      |
> | ea.010-0032 |  32768 |  213 |         0 |    10 | True      |
> | ea.002-0006 |   6242 |   43 |         0 |     2 | True      |
> | ea.006-0016 |  16384 |  128 |         0 |     6 | True      |
> | aa.001-0002 |   2048 |   25 |         0 |     1 | True      |
> | ea.002-0008 |   8192 |   32 |         0 |     2 | True      |
> | ea.012-0036 |  36864 |  256 |         0 |    12 | True      |
> | el.052-0144 | 147456 | 1109 |         0 |    52 | True      |
> | el.036-0096 |  98304 |  768 |         0 |    36 | True      |
> | ea.004-0012 |  12288 |   85 |         0 |     4 | True      |
> | ea.001-0002 |   2048 |   25 |         0 |     1 | True      |
> | aa.002-0008 |   8192 |   32 |         0 |     2 | True      |
> | ea.008-0024 |  24576 |  171 |         0 |     8 | True      |
> | el.044-0128 | 131072 |  939 |         0 |    44 | True      |
> | ea.016-0044 |  45056 |  341 |         0 |    16 | True      |
> +-------------+--------+------+-----------+-------+-----------+
> ```
> 
> 所以我的建议是可以把条件由**=**变成**>**, 这样相对来说更宽泛一点

很好的建议，我们下个版本会筛选条件由**=**变成**>=**。
感谢
