### ISSUE TITLE
扩容、缩容问题

### ISSUE THREAD

**Issue by hoiwanchang** [KubeOperator/KubeOperator#190]
**KubeOperator 版本**
2.2.35 及 2.2.55

**Bug 描述**
在集群扩容缩容时无法正常扩容&缩容
1. 使用rook-ceph作为后端存储，执行扩容后无法正确发现存储卷，服务器与原worker节点相同
2. 扩容失败后无法正确缩容，如果扩容失败的话，节点会添加到集群中，缩容时因未安装成功所以执行卸载时失败。

**Bug 重现步骤**
扩容失败
1.  点击扩容
2. 成功后执行kubectl get pods -n rook-ceph查看pod状态
3. loki无法安装成功同时ceph-osd-mon一直处于pending状态

缩容失败
1. 点击扩容并且扩容失败
2. 点击缩容并选择失败的服务器
3. 在 TASK [drain node] 环节提示无此命令并执行失败，同时节点没有正确移除

**期待的正确结果**
正确情况下应该是什么样的？
正确扩容缩容

**截图**
如果有截图，请附上截图.

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下loki、ceph-operator、ceph-mgr的日志

如有其他问题请加入下面QQ群或微信群交流～
技术交流 QQ 群
请加 QQ 群号：825046920
微信群
搜索微信号 wh_it0224，添加好友，备注（城市-github用户名）, 验证通过会加入群聊。
