### ISSUE TITLE
内置应用可插拔需求

### ISSUE THREAD

**Issue by F-liuhui** [KubeOperator/KubeOperator#198]
**请描述您的需求或者改进建议.**
希望内置应用做成可选方式，用户需要什么内置应用自己选择安装。目前我们的做法是默认全部安装，
这样如果我的集群管理平台不使用ko，我可能不需要默认的内置应用。

**请描述你建议的实现方案**

**Comment by KubeOperator** [comment]
收到，我们内部讨论下。

**Comment by huanglei288766** [comment]
经过最近的测试，我发现，内置组件经常无法访问。所以也希望能够增加可以自行选择内置应用或者无内置应用的功能。

**Comment by KubeOperator** [comment]
我们会逐步移动到应用商店。

**Comment by KubeOperator** [comment]
2.5 版本仅会保留最小且必要的应用，其他可选的全部移到应用商店中。

**Comment by KubeOperator** [comment]
仅剩应用商店，2.6 版本解决。

**Comment by maninhill** [comment]
2.6 已经解决，关闭。
