### ISSUE TITLE
docker push镜像到Registry，报403

### ISSUE THREAD

**Issue by gst6062825** [KubeOperator/KubeOperator#199]
**KubeOperator 版本**
版本: v2.2.32
**Bug 描述**
###登录registry成功
$ docker login --username=admin -p=admin123 registry-ui.apps.carnet.testlp.com
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
###
$ docker push registry-ui.apps.carnet.testlp.com/charger_docker/uuevc-main:uuevc-gate_20191229_
error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "\n\n<title>403 Forbidden</title>\n\n
Forbidden
\n
You don't have permission to access /v2/charger_docker/uuevc-main/blobs/uploads/\non this server.
\nApache/2.4.10 (Debian) Server at registry-ui.apps.carnet.leapmotor.com Port 80\n\n"

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![无标题](https://user-images.githubusercontent.com/17375688/71652999-fcd4b780-2d64-11ea-813b-dd1ed44a36ff.png)

**Comment by gst6062825** [comment]
"insecure-registries" : [
    "registry.kubeops.io:8092",
    "registry-ui.apps.carnet.leapmotor.com"
  ],

**Comment by youliyuan-fit2cloud** [comment]
> "insecure-registries" : [
> "registry.kubeops.io:8092",
> "registry-ui.apps.carnet.leapmotor.com"
> ],

您好～，我们测试没有复现您的问题。

请加QQ群825046920或者微信wh_it0224 ，我们会协助解决。

**Comment by lth3726381** [comment]
> "insecure-registries" : [
> "registry.kubeops.io:8092",
> "registry-ui.apps.carnet.leapmotor.com"
> ],

不能使用registry-ui.apps.carnet.leapmotor.com，这是一个前端界面
应该使用 registry.apps.carnet.leapmotor.com
