### ISSUE TITLE
安装2.2.55成功，服务启动失败。

### ISSUE THREAD

**Issue by xinwudi** [KubeOperator/KubeOperator#200]
CentOS版本: CentOS Linux release 7.7.1908 (Core)
内核版本：4.19.8-1.el7.elrepo.x86_64 
查看kubeops状态显示：Creating 过后会变成stopping,Removing.
按自己的解决方案：感觉kubeops服务是执行了docker-compose up，
发现mysql和nginx启动失败，nginx安装 docker logs 修改了/opt/kubeoperator/docker/nginx/f2o.conf文件中的http://地址。nginx启动成功，但是mysql容器能进去，但是状态为unhealthy。没定位到错误。请大佬指教

**Comment by youliyuan-fit2cloud** [comment]
您的问题需要更详细的信息定位问题，方便的话可以加入下面微信群和QQ群。

QQ 群号：825046920

微信群：搜索微信号 wh_it0224，添加好友，备注（城市-github用户名）, 验证通过会加入群聊。

谢谢～！
