### ISSUE TITLE
ES Index Month处理

### ISSUE THREAD

**Issue by ericwinn** [KubeOperator/KubeOperator#203]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.2.61

**Bug 描述**
简要描述您碰到的问题
请求日志时的index与通过cmreslogging自动创建的index在月份的处理上不致

**Bug 重现步骤**

**期待的正确结果**
正确情况下应该是什么样的？
cmreslogging采用的是双字符处理月份，get_index采用的是标准的，建议采用一样的处理方式。看到master分支中现在是采用大小判断，感觉这种写法不太好，建议改成”datetime.datetime.now().strftime('%Y.%m')“

**Comment by KubeOperator** [comment]
感谢  已经修改。
