### ISSUE TITLE
增加私有仓库配置项

### ISSUE THREAD

**Issue by tokyo2006** [KubeOperator/KubeOperator#205]
**请描述您的需求或者改进建议.**
增加私有镜像仓库配置项（可选)

**请描述你建议的实现方案**
一旦勾选了私有仓库配置，则需要填写私有镜像仓库地址，并根据填写的ca root证书在安装docker的时候自动生成客户端证书.结构如下：
- /etc/docker/certs.d/$REPO HOSTNAME/ca.crt  
- /etc/docker/certs.d/$REPO HOSTNAME/client.cert
- /etc/docker/certs.d/$REPO HOSTNAME/client.key

默认应用中的registry则无需再安装了

**Comment by KubeOperator** [comment]
非常好的建议，我们这边讨论下放到 roadmap 中去。
