### ISSUE TITLE
增加证书管理功能

### ISSUE THREAD

**Issue by tokyo2006** [KubeOperator/KubeOperator#206]
**请描述您的需求或者改进建议.**
证书的管理
**请描述你建议的实现方案**
考虑使用[vault](https://github.com/hashicorp/vault-helm)和[cert-manager](https://cert-manager.io/)协同管理证书

- Vault保护、存储并严格控制对令牌、密码、证书、API密钥和当前计算中的其他秘密的访问。

- cert-manager是Kubernetes的一个附加组件，用于自动化管理和从各种发行源发出的TLS证书。

实现的方式，通过WEBUI的统一配置，部署好集群后就部署好cert-manager插件以及valut插件，这2个插件作为必选插件进行安装

**Comment by KubeOperator** [comment]
非常好的建议，我们这边讨论下放到 roadmap 中去。

**Comment by KubeOperator** [comment]
3.0 已经支持 cert-manager
