### ISSUE TITLE
uninstall环境清理

### ISSUE THREAD

**Issue by hl8437** [KubeOperator/KubeOperator#207]
**请描述您的需求或者改进建议.**
在进行不同版本的operator进行测试的时候，我发现总是会有之前的版本会环境没有清理干净。
所以希望uninstall的时候，能够对环境有一个全面的清理或者还原。
或者有一个operator详细的数据文件存放列表，以供进行清理。

**请描述你建议的实现方案**

**Comment by lvxiaohu** [comment]
我们将会对自动卸载进一步优化，感谢你的建议! #
