### ISSUE TITLE
ETCD单独部署

### ISSUE THREAD

**Issue by tokyo2006** [KubeOperator/KubeOperator#211]
**请描述您的需求或者改进建议.**
实际上在生产环境中都是将etcd独立部署的高可用集群

**请描述你建议的实现方案**
etcd独立部署并提供高可用部署的方式 节点为奇数个

etcd的备份: https://github.com/vmware-tanzu/velero

**Comment by Aaron3S** [comment]
计划3.0做这个事情

**Comment by maninhill** [comment]
etcd 作为 control plane 存在，跟公有云托管 k8s 集群一样。
