### ISSUE TITLE
使用NAT做端口转发 导致webkubectl报错

### ISSUE THREAD

**Issue by wangzhengkun** [KubeOperator/KubeOperator#214]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.3.27
**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/12987937/74806075-f05deb80-531f-11ea-8e03-7ee62ddb7fcc.png)

**Bug 重现步骤**
1.  点击webkubectl 出现上图的样子
后台日志
![image](https://user-images.githubusercontent.com/12987937/74806110-09ff3300-5320-11ea-8322-0a3182a4af60.png)
![image](https://user-images.githubusercontent.com/12987937/74806113-0ec3e700-5320-11ea-9150-0e5840198b22.png)

**Comment by KubeOperator** [comment]
2.4 版本已经修复。
