### ISSUE TITLE
关于nfs导致安装失败

### ISSUE THREAD

**Issue by wang628625** [KubeOperator/KubeOperator#215]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.3.27
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  应为其他问题导致部署失败，比如本机地址填错等
2. nfs服务器状态显示久异常了
3. 重新安装也久失败了
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zhengkunwang223** [comment]
已验证此BUG 谢谢您的反馈
