### ISSUE TITLE
安装内置应用步骤报/bin/sh kubectl: command not foundnon-zero return code错误

### ISSUE THREAD

**Issue by 745819123** [KubeOperator/KubeOperator#221]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.3.27
**Bug 描述**
简要描述您碰到的问题
集群安装失败，在安装内置应用步骤报/bin/sh kubectl: command not foundnon-zero return code错误，集群当前状态为“错误”
**Bug 重现步骤**
1.  操作系统采用centos7.7，sshd升级到最新版本8.2，存储采用新建nfs的方式
2. 1台kubeoperator主机，1台master，1台worker，一台nfs服务器

**期待的正确结果**
正确情况下应该是什么样的？
正常安装集群
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/10809565/76162879-74b3c980-617c-11ea-86e0-9c256f15308f.png)
![image](https://user-images.githubusercontent.com/10809565/76162901-b3498400-617c-11ea-9181-626a1507fcc6.png)

**Comment by 745819123** [comment]
发现可能导致这个问题的原因
KubeOperator/core/resource/kubeasz/roles/cluster-storage/tasks/main.yml文件配置错误
![image](https://user-images.githubusercontent.com/10809565/76196785-cd8b6c80-6225-11ea-9732-d9c1acee741b.png)

**Comment by Aaron3S** [comment]
确认一下master节点上 kubectl 命令有没有安装。 如果没有安装我们从这里找问题

**Comment by 745819123** [comment]
安装了的，因为没有bin_dir，所以提示找不到命令，发现好多文件都没有bin_dir，不知道其他人怎么安装成功的

**Comment by Aaron3S** [comment]
这是 ko 的  bin_dir变量的值,
![image](https://user-images.githubusercontent.com/34506289/76307639-2c271800-6304-11ea-8592-eda6f49e5ec8.png) 绝大多数情况下这个路径是包含在 PATH中的，所以有的kubectl命令并没有使用绝对路径，所以绝大多数情况下会成功的。您可以检查一下您的PATH中是否包含这个路径，同时也感谢您的issue，以后我们会更严谨的使用绝对路径。

**Comment by 745819123** [comment]
我的机器上面没有这个PATH，手动加上就可以了，建议ko自动配置或者在文档的集群安装模块写明需要保证有该配置，当然都是用绝对路径最好
