### ISSUE TITLE
KubeOperator 改了哪些 Linux 内核参数？

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#222]
如题？

**Comment by zhengkunwang223** [comment]
感谢提问
我们修改了如下参数
### 内核参数
    net.ipv4.ip_forward = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-arptables = 1
    net.ipv4.tcp_tw_recycle = 0
    net.ipv4.tcp_tw_reuse = 0
    net.netfilter.nf_conntrack_max=1000000
    vm.swappiness = 0
    vm.max_map_count=655360
    fs.file-max=6553600
    <----'ipvs only start'----->
    net.ipv4.tcp_keepalive_time = 600
    net.ipv4.tcp_keepalive_intvl = 30
    net.ipv4.tcp_keepalive_probes = 10
    <----'ipvs only end'------->

### 系统日志参数

    Storage=persistent
    SystemMaxUse=2G
    SystemMaxFileSize=200M
    MaxRetentionSec=2week
    ForwardToSyslog=no
    ForwardToWall=no

### 系统文件数限制

    DefaultLimitCORE=infinity
    DefaultLimitNOFILE=100000
    DefaultLimitNPROC=100000
    
### 其他
禁用SELinux<br>
关闭 swap

我们会同步更新到常见问题中 再次感谢您的提问
