### ISSUE TITLE
集群安装时在firewall : 打开防火墙UDP端口的时候遇到问题

### ISSUE THREAD

**Issue by dnangelxueaoran** [KubeOperator/KubeOperator#223]
**KubeOperator 版本**
2.3.27

**Bug 描述**
集群安装时在firewall : 打开防火墙UDP端口的时候遇到问题，在任务日志中打印如下
failed: [master1.xtestm.xtestm.com] (item=53) => {"changed": false, "item": 53, "msg": "ERROR: Exception caught: Unable to guess signature from an empty list Permanent operation"}

**Comment by maninhill** [comment]
请升级到最新 2.6 版本。
