### ISSUE TITLE
部署机运行过几天负载异常高，celery进程占CPU高达300％

### ISSUE THREAD

**Issue by jamping** [KubeOperator/KubeOperator#224]
**KubeOperator 版本**
版本：v2.3.27
**Bug 描述**
部署机运行过几天负载异常高，celery进程占CPU高达300％
**截图**
![644339507](https://user-images.githubusercontent.com/29243508/76486206-a4532200-6459-11ea-850c-4e988d402b17.jpg)

**Comment by KubeOperator** [comment]
收到，我们这边努力去复现。

**Comment by lvxiaohu** [comment]
KubeOperator v2.4.30 对 Celery 做了一定优化。建议升级到 KubeOperator v2.4 版本（支持平滑升级至2.4），继续观察，看看是否解决可以此问题。
