### ISSUE TITLE
选择不到部署计划

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#228]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
2.4.30

**Bug 描述**
简要描述您碰到的问题
选择不到部署计划

**Bug 重现步骤**

![image](https://user-images.githubusercontent.com/41712985/76697306-b25ea800-66d0-11ea-98be-da94e05fa271.png)

**Comment by KubeOperator** [comment]
需要授权到项目，然后就能看到。我们后续会在这个页面加个提示。

**Comment by KubeOperator** [comment]
已经解决
