### ISSUE TITLE
关于worker节点弹性扩容的建议

### ISSUE THREAD

**Issue by weishuo6** [KubeOperator/KubeOperator#229]
**请描述您的需求或者改进建议.**
worker 节点能否支持自动伸缩，类似公有云弹性伸缩，到了监控阈值，自动伸缩 worker 节点
业务场景：业务量猛增时不用在手动去扩容 worker ，业务量下降时自动回收空闲 worker
**请描述你建议的实现方案**
比如连续三个采集周期内的监测指标平均值（例如 CPU 平均使用量和内存平均使用量）均超出所设定的上下限时，会触发扩容或伸缩操作

**Comment by KubeOperator** [comment]
技术上我们已经可以通过手动更改 worker 节点数量，实现快速伸缩。

基于监控指标做自动伸缩技术上没有问题，后续版本再考虑。
