### ISSUE TITLE
关于 KubeOperator 的后续研发计划

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#233]
**请描述您的需求或者改进建议.**

可否分享后续版本的研发计划？具体有哪些功能？

**Comment by KubeOperator** [comment]
我们的策略是每月发布一个版本，具体发布时间是每周第三周的周一。

月度版本的开发计划请参考：https://github.com/KubeOperator/KubeOperator/blob/master/ROADMAP.md
