### ISSUE TITLE
prometheus未部署成功，如何重新增加部署？

### ISSUE THREAD

**Issue by fanhongli** [KubeOperator/KubeOperator#237]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
KubeOperator-v2.4

**Bug 描述**
简要描述您碰到的问题

TASK [cluster-addon : 拷贝 prometheus values文件] **********************************
changed: [master1.k8scluster.yueying.info]
TASK [cluster-addon : 拷贝 prometheus setting文件] *********************************
changed: [master1.k8scluster.yueying.info]
TASK [cluster-addon : 部署 prometheus] *******************************************
 [WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ansible_api.ansible.callback.PlaybookResultCallBack object at
0x7fc622480438>): 'ignore'

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wanghe-fit2cloud** [comment]
进入master节点，手动执行以下命令：
1、# cd /opt/kubeOperator-kube-bin/1.16.7/manifests/prometheus/
2、# helm upgrade f2c-prometheus --namespace=kube-operator --install --force --recreate-pods -f prom-settings.yaml -f prom-alertsmanager.yaml -f prom-alertrules.yaml ./prometheus

可以添加技术交流群（见README沟通交流）

**Comment by fanhongli** [comment]
谢谢

**Comment by fanhongli** [comment]
> 进入master节点，手动执行以下命令：
> 1、# cd /opt/kubeOperator-kube-bin/1.16.7/manifests/prometheus/
> 2、# helm upgrade f2c-prometheus --namespace=kube-operator --install --force --recreate-pods -f prom-settings.yaml -f prom-alertsmanager.yaml -f prom-alertrules.yaml ./prometheus
> 
> 可以添加技术交流群（见README沟通交流）

可以了
