### ISSUE TITLE
安装后,系统不可用

### ISSUE THREAD

**Issue by bruceywave** [KubeOperator/KubeOperator#244]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.4
**Bug 描述**
简要描述您碰到的问题
安装后无法启动服务,通过systemctl status kubeops查看状态发现.

- Mar 24 16:34:50 localhost.localdomain docker-compose[23168]: kubeops_task     | Error: celery start error

- Mar 24 16:36:12 localhost.localdomain docker-compose[23168]: kubeops_task     | ProgrammingError
可以打开登录界面,但是无法登录,提示用户名密码错误.

**Bug 重现步骤**
1.  安装成功,等待了五分钟,按照官方的文档一步一步执行的,但是安装成功后,启动出错.

![image](https://user-images.githubusercontent.com/8263729/77406278-5c37e600-6def-11ea-8411-2acd342bb6b0.png)

2. 

![image](https://user-images.githubusercontent.com/8263729/77406237-4e826080-6def-11ea-9962-5e7cf22064c4.png)

3. 此时登录,报用户名和密码错误
![image](https://user-images.githubusercontent.com/8263729/77406303-6823a800-6def-11ea-9253-c0f82c7d3b7e.png)

请问以上问题该如何解决呢,我已经重装了n次了.一直不成功

**Comment by zhengkunwang223** [comment]
看你的日志显示中有MYSQL连接不上的

> **KubeOperator 版本**
> 您所使用的 KubeOperator 版本是？
> v2.4
> **Bug 描述**
> 简要描述您碰到的问题
> 安装后无法启动服务,通过systemctl status kubeops查看状态发现.
> 
> * Mar 24 16:34:50 localhost.localdomain docker-compose[23168]: kubeops_task     | Error: celery start error
> * Mar 24 16:36:12 localhost.localdomain docker-compose[23168]: kubeops_task     | ProgrammingError
>   可以打开登录界面,但是无法登录,提示用户名密码错误.
> 
> **Bug 重现步骤**
> 
> 1. 安装成功,等待了五分钟,按照官方的文档一步一步执行的,但是安装成功后,启动出错.
> 
> ![image](https://user-images.githubusercontent.com/8263729/77406278-5c37e600-6def-11ea-8411-2acd342bb6b0.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/8263729/77406237-4e826080-6def-11ea-9962-5e7cf22064c4.png)
> 
> 1. 此时登录,报用户名和密码错误
>    ![image](https://user-images.githubusercontent.com/8263729/77406303-6823a800-6def-11ea-9253-c0f82c7d3b7e.png)
> 
> 请问以上问题该如何解决呢,我已经重装了n次了.一直不成功

看你的日志中有MYSQL连接不上的问题 具体问题需要查看详细日志 如果可以 请加微信 wzk727912172 方便沟通 。谢谢

**Comment by zhengkunwang223** [comment]
由于虚拟机IP为DHCP 导致此问题 现已解决 问题关闭
