### ISSUE TITLE
安装可以KubeOperator指定安装目录吗

### ISSUE THREAD

**Issue by yantop** [KubeOperator/KubeOperator#246]
**请描述您的需求或者改进建议.**
我看了下脚本没看到可以指定的地方

**请描述你建议的实现方案**
希望可以指定下目录，机器系统盘只有40G,挂载的磁盘是自己指定了一个

**Comment by KubeOperator** [comment]
收到，我们尽快支持可配置安装目录。

**Comment by KubeOperator** [comment]
3.0 已经支持。
