### ISSUE TITLE
添加主机后添加集群时没有可用主机

### ISSUE THREAD

**Issue by jx3775250** [KubeOperator/KubeOperator#247]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
 2.4.30
**Bug 描述**
简要描述您碰到的问题
添加主机后添加集群时没有可用主机，本地和云主机都一样

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/40455946/77644121-875f3880-6f9b-11ea-98b1-d55f7bcf1878.png)
![image](https://user-images.githubusercontent.com/40455946/77644205-a231ad00-6f9b-11ea-91f0-5728249e2205.png)

**Comment by KubeOperator** [comment]
需要先进行授权。

**Comment by Gavin-TW** [comment]
> 需要先进行授权。

在哪里授权呢？？？

**Comment by zhengkunwang223** [comment]
项目管理-资源
