### ISSUE TITLE
ssh/scp连接建立后没释放

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#248]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？

2.4.30

**Bug 描述**
简要描述您碰到的问题

ssh/scp连接建立后没释放

**Bug 重现步骤**

![image](https://user-images.githubusercontent.com/41712985/77822867-83fdb580-7131-11ea-9725-afd87b347b03.png)

**Comment by maninhill** [comment]
@Aaron3S

**Comment by KubeOperator** [comment]
已修复，待发布。

**Comment by KubeOperator** [comment]
已解决。
