### ISSUE TITLE
在手动模式情况下无法添加F5 BIGIP

### ISSUE THREAD

**Issue by liuchangfitcloud** [KubeOperator/KubeOperator#249]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
2.4 2.3
**Bug 描述**
简要描述您碰到的问题
手动模式下部署的集群无法添加F5配置提示部署计划不能为空
**Bug 重现步骤**
1.  手动模式创建集群
2. 部署集群
3. 配置F5 失败
4. 

**期待的正确结果**
正确情况下应该是什么样的？
手动模式下可以添加F5 BIGIP对外服务
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/44662176/77980079-fb516600-7338-11ea-9457-1d5540083eed.png)
![image](https://user-images.githubusercontent.com/44662176/77980086-fdb3c000-7338-11ea-8bcd-a3e446fd51f8.png)
![Uploading image.png…]()

**Comment by zhengkunwang223** [comment]
问题已解决，下个版本修复
