### ISSUE TITLE
创建可用区域无法获取集群信息

### ISSUE THREAD

**Issue by swimmingchar** [KubeOperator/KubeOperator#251]
**KubeOperator 版本**
v2.4.43

**Bug 描述**
在和 vsphere 做部署计划时，创建可用区的时候，第二部获取集群时，显示空白。

**Bug 重现步骤**
1.  点击可用区
2. 填写基本信息
3. 点击下一步
4. 下拉集群选项

**期待的正确结果**
没见过正确的样子，目前选择哪一个都会报错，没有选中。

**截图**
![20200407152316](https://user-images.githubusercontent.com/8534783/78641495-e601ac00-78e3-11ea-9fc7-5ed5b9ea2344.jpg)

**Comment by zhengkunwang223** [comment]
请问V-center中创建集群了吗？没有的话请新建集群

**Comment by swimmingchar** [comment]
不好意思，的确没有创建，非常感谢
