### ISSUE TITLE
安装argo-cd后，部分服务无法启动

### ISSUE THREAD

**Issue by sony9997** [KubeOperator/KubeOperator#258]
**KubeOperator 版本**
v2.5.28
**Helm Charts 离线包 版本**
kubeapps-plus-package-v1.2-48.tar.gz
**Bug 描述**
硬件信息：vbox虚拟机上安装的centos7.4，4核8G内存
在kubeapps-plus安装argo-cd，虽然显示成功，但是dex-server和server POD无法启动（显示CrashLoopBackOff），查看日志后发现报
standard_init_linux.go:207: exec user process caused "exec format error”
的错误。
在网上查了一下，是说镜像编译的环境与运行的环境不一致导致，文章如下：
https://cloud.tencent.com/developer/article/1576603

**Bug 重现步骤**
1.  在kubeapps-plus安装argo-cd
2. 安装显示成功
3. 服务未正常启动，查看日志发现启动报错

**期待的正确结果**
所有pod能正常启动。

**截图**
![4F2CDA20-F862-46B7-9565-D65FC51F7CF5](https://user-images.githubusercontent.com/17905583/79073403-ebfaf100-7d18-11ea-81b2-ad59aef5e0d1.png)

**Comment by lvxiaohu** [comment]
如你搜索的答案，应该问题产生于此。你现在使用的系统架构是 Arm 还是 x86 ？ 方便使用 docker version 命令将信息提供给我吗？

**Comment by sony9997** [comment]
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:51:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:22:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false

以上是docker version命令的信息

**Comment by lvxiaohu** [comment]
我也是用 linux/amd64 系统架构来创建 argo cd ，并未出现这个现象。

[root@master1 ~]# kubectl get pod -n demo
NAME                                                            READY   STATUS    RESTARTS   AGE
argo-cd-gt4mri-argocd-application-controller-57d49cd846-jxwwp   1/1     Running   0          12h
argo-cd-gt4mri-argocd-dex-server-8596b44d78-bqkq6               1/1     Running   0          12h
argo-cd-gt4mri-argocd-redis-757c6b5bf8-lf4wq                    1/1     Running   0          12h
argo-cd-gt4mri-argocd-repo-server-5f7b965757-f7jhn              1/1     Running   0          12h
argo-cd-gt4mri-argocd-server-64fb548b44-lqljn                   1/1     Running   0          12h
my-nginx-6c8fdfcd6f-lzpl4                                       1/1     Running   0          11h
my-nginx-6c8fdfcd6f-wb6lp                                       1/1     Running   0          11h

[root@master1 ~]# docker version
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:51:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:22:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by sony9997** [comment]
跟我用的vbox虚拟机有关吗？宿主是window7系统
