### ISSUE TITLE
KubeOperator部署集群时，在配置主机基础软件包时主机yum无法连接本地软件源

### ISSUE THREAD

**Issue by lipancs** [KubeOperator/KubeOperator#259]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.5.18
**Bug 描述**
KubeOperator部署集群时，在配置主机基础软件包时主机yum无法连接本地软件源，提示http://192.168.98.7:8180/repository/centos-base/7/extras/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.98.7:8180; 拒绝连接

**Bug 重现步骤**
1.  手动模式安装集群，开始安装后。已确认主机与KubeOperator主机之间网络是没有任何问题的。
**期待的正确结果**
正确情况下应该是什么样的？

**截图**

**Comment by zhengkunwang223** [comment]
解决办法： 防火墙问题，关掉防火墙 
步骤 ：在部署机执行
systemctl stop firewalld.service
systemctl restart docker.service
cd /opt/kubeoperator/ && docker-compose up -d

**Comment by lipancs** [comment]
docker版本的问题，导致nexus容器没启动，已解决
