### ISSUE TITLE
系统日志无法刷出

### ISSUE THREAD

**Issue by purplepalmdash** [KubeOperator/KubeOperator#261]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
2.5.18

**Bug 描述**
简要描述您碰到的问题
点击系统日志一栏后，鼠标一直转圈，页面无法刷出

**Bug 重现步骤**
1.  正常安装KubeOperator并部署集群
2.  点击`系统日志`

**期待的正确结果**
正确情况下应该是什么样的？
 系统日志一栏显示出日志列表。

**截图**
如果有截图，请附上截图.
![https://purplepalmdash.github.io/images/2020_04_20_17_06_50_906x423.jpg](https://purplepalmdash.github.io/images/2020_04_20_17_06_50_906x423.jpg)

**Comment by zhengkunwang223** [comment]
已知问题 下个版本修复
