### ISSUE TITLE
修复CIS扫描出来的问题

### ISSUE THREAD

**Issue by zhengkunwang223** [KubeOperator/KubeOperator#262]
**请描述您的需求或者改进建议.**

使用KO全新部署K8S集群之后使用CIS扫描集群，目前总共发现8个FAILED，建议修复。

**请描述你建议的实现方案**

详情请看附件。

[cluster-zk-2020-04-21-14-36-03 (1).xlsx](https://github.com/KubeOperator/KubeOperator/files/4508820/cluster-zk-2020-04-21-14-36-03.1.xlsx)

**Comment by maninhill** [comment]
2.6 已经解决，关闭。
