### ISSUE TITLE
在自行准备的主机上部署K8S集群，手动模式报错 部署kubeapps-plus报错

### ISSUE THREAD

**Issue by du86796922** [KubeOperator/KubeOperator#263]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
v2.5.28
**Bug 描述**
master2.dy.local-test.com | FAILED | rc=1 >>
Release "kubeapps-plus" does not exist. Installing it now.Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the requestnon-zero return code
简要描述您碰到的问题
在自行准备的主机上部署K8S集群，手动模式
出错日志信息
![image](https://user-images.githubusercontent.com/25892640/80049839-97d8e380-8546-11ea-84d9-2043199589e2.png)
可能是 metrics 服务没有部署成功，查看metrics 服务 ansible部署过程发现超时
![image](https://user-images.githubusercontent.com/25892640/80049958-f1411280-8546-11ea-9620-c8b06f43784e.png)

**Bug 重现步骤**
节点信息
![image](https://user-images.githubusercontent.com/25892640/80050063-3107fa00-8547-11ea-998c-47dbe87c483f.png)

**期待的正确结果**
正确情况下应该是什么样的？
希望能正常部署成功,怎么调试这个问题？或者怎么获得 metrics  部署失败的原因？

**Comment by myzhongguo** [comment]
我的问题是安装内置应用报错
```
TASK [kubeapps : 等待 kubeapps-plus chartmuseum running] *************************
FAILED - RETRYING: 等待 kubeapps-plus chartmuseum running (30 retries left).
master1.batch.pukka.cn | SUCCESS | rc=0 >>
1

TASK [kubeapps : helm init] ****************************************************
changed: [master1.batch.pukka.cn -> None] => (item=master1.batch.pukka.cn)
master1.batch.pukka.cn | SUCCESS | rc=-1 >>
All items completed

TASK [kubeapps : 添加 chartmuseum 仓库] ********************************************
failed: [master1.batch.pukka.cn -> None] (item=master1.batch.pukka.cn) => {"changed": true, "cmd": "helm repo add chartmuseum http://chartmuseum.kubeapps.fit2cloud.com", "delta": "0:00:00.079484", "end": "2020-04-23 12:38:16.429287", "item": "master1.batch.pukka.cn", "msg": "non-zero return code", "rc": 1, "start": "2020-04-23 12:38:16.349803", "stderr": "Error: Looks like \"http://chartmuseum.kubeapps.fit2cloud.com\" is not a valid chart repository or cannot be reached: Failed to fetch http://chartmuseum.kubeapps.fit2cloud.com/index.yaml : 404 Not Found", "stderr_lines": ["Error: Looks like \"http://chartmuseum.kubeapps.fit2cloud.com\" is not a valid chart repository or cannot be reached: Failed to fetch http://chartmuseum.kubeapps.fit2cloud.com/index.yaml : 404 Not Found"], "stdout": "", "stdout_lines": []}
master1.batch.pukka.cn | FAILED | rc=-1 >>
All items completed

PLAY RECAP *********************************************************************
master1.batch.pukka.cn     : ok=63   changed=59   unreachable=0    failed=1   
:cluster batch exec install error
NoneType: None
Task kubeops_api.tasks.start_deploy_execution[9b5cfdbb-2ad3-4650-9ed2-254792d6f844] succeeded in 746.8270649660003s: {'raw': {}, 'summary': {'contacted': {'master1.batch.pukka.cn': {...}}, 'dark': {'master1.batch.pukka.cn': {...}}, 'success': False}}
```
![image](https://user-images.githubusercontent.com/21257097/80067870-37ab6700-8571-11ea-8211-38cc9708617b.png)

原因猜想
1. 服务没有启动：80端口启动但是访问没有对应服务的界面
2. 浏览器跨域失败。不知道怎么搞的请求的80端口实际三个服务怎么找到对应网络
三个服务分别对应哪个时间端口，容器是哪个？80转发的配置组件在哪？

**Comment by du86796922** [comment]
问一下 你的80 服务是什么？是不是haproxy 转发到 api server?

**Comment by myzhongguo** [comment]
> 问一下 你的80 服务是什么？是不是haproxy 转发到 api server?@myzhongguo

是httpd服务，可能我原来有http服务占用80端口所以应用中心各个服务的地址服务访问。
如下这是kubeops设定的域名映射地址 http://chartmuseum.kubeapps.fit2cloud.com应该是访问80端口因为端口占用所以访问了httpd的服务而不是kubeops配置的服务

**Comment by myzhongguo** [comment]
> 问一下 你的80 服务是什么？是不是haproxy 转发到 api server?@myzhongguo

缺失是httpd服务的原因停掉即可。
