### ISSUE TITLE
k8s节点，yum源地址被改了？

### ISSUE THREAD

**Issue by yorkexing** [KubeOperator/KubeOperator#268]
**请描述您的需求或者改进建议.**
在node节点安装的时候，全部指向了kubeOprator的机器地址？
这个是正常的嘛？

**请描述你建议的实现方案**

**Comment by lvxiaohu** [comment]
没有明白你的具体问题。node节点在安装的时候，会去 KubeOperator 这台机器下载对应的 rpm 依赖包以及集群安装所需要的其他的离线依赖包。

**Comment by yorkexing** [comment]
感谢
但是我测试了下
在kubeOperator可以安装：yum -y install bind-utils
在K8S Node上面，还是提示找不到包
![image](https://user-images.githubusercontent.com/15082551/81261297-698ef400-906e-11ea-8c33-8b2d14f1d7df.png)

**Comment by lvxiaohu** [comment]
1. 你可以前往这两台机器的 /etc/yum.repos.d 目录，或者执行 $ yum repolist 命令查看、对比查看 Yum 源及配置文件是否一致。我觉得可能是KubeOperator 这个机器上你配置的有其他 Yum 源
2. KubeOperator 只提供 Kubernets 集群安装所需要的依赖包，你如果需要其他的软件包，可能就没有，需要你自己去手动下载对应离线安装包进行安装
