### ISSUE TITLE
https访问 UI 发现 WebKubeCtl 的请求地址时候，并不跟随协议。

### ISSUE THREAD

**Issue by bingoku** [KubeOperator/KubeOperator#271]
**KubeOperator 版本**

v2.5.33

**Bug 描述**

代理 KubeOperator 的 UI 已经启用了 wss

假设所在机房或者机器自身没有开80的话，是无法访问http的。只能通过https访问。

所以，通过浏览器访问显示空白。

![image](https://user-images.githubusercontent.com/4134788/81366905-5f2c3300-911e-11ea-91d5-aa6f5b1c24d8.png)

**期待的正确结果**

根据 ui 地址的协议，请求WebKubeCtl

**Comment by KubeOperator** [comment]
fixed on 2.6
