### ISSUE TITLE
[求助]部署集群出错

### ISSUE THREAD

**Issue by wzker** [KubeOperator/KubeOperator#274]
![Snipaste_2020-05-13_01-01-45](https://user-images.githubusercontent.com/43431427/81723496-7ddf5080-94b5-11ea-8373-099b403cf3ee.png)
这个是什么问题吗?创建集群的参数改过很多种,也是这个错误,master的错误
版本: v2.5.33

**Comment by zhengkunwang223** [comment]
这个问题是已知问题，下个版本修复

**Comment by wzker** [comment]
> 这个问题是已知问题，下个版本修复

搜嘎~谢谢

**Comment by RobotGao** [comment]
希望集群安装的时候不要修改在线yum仓库信息,同一个集群下部署,修改yum仓库地址导致下载包404, 自己手工打开对应163地址的路径,下面对应的包版本都不对,刚开始以为是操作系统内软件版本的问题,更新到最新版本后同样安装失败.仔细看了一下yum配置才知道地址已经被改掉了,到kubeoperator目录里没有找到禁用本地nexus的地方, 安装脚本可以指定版本,但是尽量不要禁用在线安装方式,因为发现过几次都是网络上对应的mirror地址包已经失效导致的包安装失败, 希望release版本的时候也注明哪些kubeoperator版本是稳定的,看来下最新版本出现问题的解决成本很高...
版本: v2.5.33
centos:7.4.1708
