### ISSUE TITLE
支持在线安装模式

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#276]
**请描述您的需求或者改进建议.**
目前 KubeOperator 和 K8s 集群的安装都是纯离线的，安装包特别大，下载时间很长。

**请描述你建议的实现方案**

希望能同时支持在线安装模式和离线安装博模式。如果安装 KubeOperator 的部署机器可以联网，那么用户可以采用在线安装模式，具体：

1. 用户可以使用一条命令完成 KubeOperator 自身的安装。
2. KubeOperator 启动后会自动同步离线包（RPM 库、Docker 镜像等）到本地 Nexus 仓库。
3. 用户部署 K8s 集群时，都是从本地 Nexus 仓库下载所需材料。

仅供参考。

**Comment by wanghe-fit2cloud** [comment]
上述优化建议 在v3.0版本中体现

**Comment by KubeOperator** [comment]
3.0 已经解决。
