### ISSUE TITLE
「建议」兼容 kubeadm 工具

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#277]
**请描述您的需求或者改进建议.**

希望 KubeOperator 是通过 Ansible 调用原生的 kubeadm 工具来操作 K8s 集群，这样后续即便客户不用 KubeOperator 了，也可以继续使用 kubeadm 工具来维护已经部署的 K8s 集群。

**请描述你建议的实现方案**

使用 kubeadm 替代 Kubeasz 中 的相关 K8s 安装和运维脚本。

**Comment by wanghe-fit2cloud** [comment]
上述优化建议 在v3.0版本中体现

**Comment by KubeOperator** [comment]
3.0 已经解决。
