### ISSUE TITLE
「建议」使用 out of tree 的云供应商插件

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#278]
**请描述您的需求或者改进建议.**

K8s 后续将不再推荐使用 in tree 的云和网络插件，希望 KO 尽快切换到 out of tree 的插件。

**请描述你建议的实现方案**

vSphere: https://github.com/kubernetes/cloud-provider-vsphere
Openstack: https://kubernetes.io/blog/2020/02/07/deploying-external-openstack-cloud-provider-with-kubeadm/

**Comment by wanghe-fit2cloud** [comment]
上述优化建议 在v3.0版本中体现
