### ISSUE TITLE
HBase连接问题

### ISSUE THREAD

**Issue by fourierr** [KubeOperator/KubeOperator#280]
**请描述您的需求或者改进建议.**
想咨询一下贵司的KubeOperator是否支持从HBase中直接导入数据到容器中？

**请描述你建议的实现方案**

**Comment by maninhill** [comment]
这个建议你 Google 下，KubeOperator 自身不支持。

**Comment by fourierr** [comment]
> 这个建议你 Google 下，KubeOperator 自身不支持。
k8s本身也是不支持的
