### ISSUE TITLE
region信息无法编辑

### ISSUE THREAD

**Issue by andyguo1985** [KubeOperator/KubeOperator#281]
**请描述您的需求或者改进建议.**

对于部署计划，region信息添加后无法修改，假设VMware的用户密码修改了（顺便说一下，数据库里面VMware的密码是明文保存的，安全风险比较大），但在KO上完全没有入口进行手动修改，无论是什么角色。所以针对这个情况建议 KO 管理员是有权限进行修改的，但对其他角色的人员是透明的。

**请描述你建议的实现方案**

可以根据角色来区分不同的编辑、删除、查看权限。

**Comment by wanghe-fit2cloud** [comment]
上述优化建议 在v3.0版本中体现
