### ISSUE TITLE
vmware环境集群安装失败

### ISSUE THREAD

**Issue by dev-rookie** [KubeOperator/KubeOperator#283]
KubeOperator 版本 v2.6.18
问题描述：
在VMware环境下，创建三台服务器，分别用于安装kubeoperator，master ，worker
1、集群采用手动部署方式，iptables+traefix+flannel方式，集群部署到worker节点，出现下图报错，显示集群安装失败
![flannel](https://user-images.githubusercontent.com/65885527/82783103-6b3f2100-9e90-11ea-87e0-fd2c88207b4f.PNG)
2、集群采用手动部署方式，iptables+traefix+calico方式，集群部署至“安装内置应用”节点，出现如下错误信息，显示集群部署成功
![安装内置应用](https://user-images.githubusercontent.com/65885527/82783287-bfe29c00-9e90-11ea-9850-f187d2a5d589.PNG)
![安装内置应用2](https://user-images.githubusercontent.com/65885527/82783301-c4a75000-9e90-11ea-8748-71b065ddc0b2.PNG)
在集群控制台，安装“应用商店”过程中，日志中依次报如下错误，最终显示“应用商店”安装失败
![应用商店1](https://user-images.githubusercontent.com/65885527/82783477-223b9c80-9e91-11ea-85bf-1d074aa48dc3.PNG)
![应用商店2](https://user-images.githubusercontent.com/65885527/82783489-2667ba00-9e91-11ea-8b87-ad0acd814bac.PNG)
![应用商店3](https://user-images.githubusercontent.com/65885527/82783501-2b2c6e00-9e91-11ea-9725-6267ca59f91d.PNG)
疑问：
经过多次尝试，在VMware环境下，一直出现上述问题，是由于kubeoperator对VMware环境支持问题，还是VMware虚拟机配置问题，如果是配置问题，那应该进行如何配置，才能确保集群及应用安装成功。

**Comment by wanghe-fit2cloud** [comment]
1、flannel安装失败 
kubectl -n kube-system describe pod kube-flannel***  定位具体问题

2、metrics apiservice 不可用
kubectl describe apiservices v1beta1.metrics.k8s.io 定位具体问题
很可能是网络问题导致的
确定跨node节点的pod ip是否能ping通

3、应用商店安装失败
先处理问题2的网络问题

**Comment by dev-rookie** [comment]
1、运行“kubectl -n kube-system describe pod kube-flannel”命令，详细如flannel.txt内所示，
[flannel.txt](https://github.com/KubeOperator/KubeOperator/files/4675714/flannel.txt)
2、运行“kubectl describe apiservices v1beta1.metrics.k8s.io”命令，结果如下图所示：
![metrics apiservices](https://user-images.githubusercontent.com/65885527/82787899-012b7980-9e9a-11ea-96a9-ba131c8be7d1.PNG)
3、如果是网络问题，那VMware虚拟机至少要配置几个网卡，网络应该如何规划？

**Comment by wanghe-fit2cloud** [comment]
1、提供具体kube-flannel***的日志
2、网络问题指的是flannel或calico（解决集群跨节点网络通信问题）
3、网络规划时，注意pod_cidr、service_cidr和docker0网段不要和现有网络冲突（kubeoperator已给出默认值）

**Comment by dev-rookie** [comment]
![kube-flannel](https://user-images.githubusercontent.com/65885527/82791632-b06b4f00-9ea0-11ea-99fc-4394f3efcfd7.PNG)

**Comment by dev-rookie** [comment]
VMware环境，master和worker配置双网卡，docker网络地址可以访问，179.20.210.0可以访问，其它pod节点ip无法访问。
请问：
1、有可用的主机网络的配置样例作参考么，便于解决网络通讯问题；

**Comment by wanghe-fit2cloud** [comment]
请加入下面QQ群或微信群交流～

QQ群：825046920
搜索微信号 wh_it0224，添加好友，备注（城市-github用户名）, 验证通过会加入群聊。

**Comment by dev-rookie** [comment]
问题已解决，VMware环境主机未设置默认网关，导致安装失败。
