### ISSUE TITLE
pod 跳板机基于ssh

### ISSUE THREAD

**Issue by FrelDX** [KubeOperator/KubeOperator#287]
**请描述您的需求或者改进建议.**
pod 跳板机基于ssh

**请描述你建议的实现方案**
pod 跳板机基于ssh
![image](https://user-images.githubusercontent.com/32826879/83620843-7b59ad80-a5c0-11ea-969d-e7b809dc6e23.png)

**Comment by FrelDX** [comment]
和coco功能差不多

**Comment by KubeOperator** [comment]
可以用 webkubectrl
