### ISSUE TITLE
测试需要没有那么大内存，怎么改配置要求

### ISSUE THREAD

**Issue by leitinglvke** [KubeOperator/KubeOperator#289]
您好，我测试需要，设备没有那么大内存，要怎么改kubeoprator配置要求呢，我修改了 cluster/config.yml下的device_require 内存参数，kubeoprator restart后查看配置要求居然不生效，请指导修改，谢谢。

**Comment by wanghe-fit2cloud** [comment]
更改配置要求这部分功能，涉及到的更改不只是cofnig.yml文件

建议申请加入技术交流群一起讨论
技术交流 QQ 群：825046920
微信群： 搜索微信号 wzk727912172，添加好友，备注（城市-github用户名）, 验证通过会加入群聊
