### ISSUE TITLE
如何新增其他网络插件安装

### ISSUE THREAD

**Issue by aixushuai** [KubeOperator/KubeOperator#290]
**请描述您的需求或者改进建议.**
目前kubeoperator支持的网络插件太少了，现在不支持的，自己想新增网络该如何接入？

**请描述你建议的实现方案**
kubespray支持的网络插件就特别多，对于底层使用的（kubeasz）ansilbe roles是否可以考虑使用kubespray
https://github.com/kubernetes-sigs/kubespray

**Comment by wanghe-fit2cloud** [comment]
目前支持flannel vxlan host-gw和calico bgp ipip
后续会根据需求增加网络插件
