### ISSUE TITLE
创建可用区时无法加载出配置选项，一直转圈

### ISSUE THREAD

**Issue by yanzu888** [KubeOperator/KubeOperator#291]
**KubeOperator 版本**
v2.6.18

**Bug 描述**
1. 创建区域完成后，且验证参数有效；
2. 在创建可用区域时，【配置参数】步骤却一直加载转圈圈

**Bug 重现步骤**
1.  使用chrome、IE、Edge 浏览器均复现同样的问题

**期待的正确结果**
从官方提供的教程，这里应该会显示提供商(openstack)配置信息才对

**截图**
![image](https://user-images.githubusercontent.com/20461842/84729415-3a9d6380-afc6-11ea-8395-3150dcae61f7.png)

**Comment by wanghe-fit2cloud** [comment]
openstack使用的是哪个版本？

技术交流 QQ 群：825046920
微信群： 搜索微信号 wzk727912172，添加好友，备注（城市-github用户名）, 验证通过会加入群聊

**Comment by yanzu888** [comment]
> openstack使用的是哪个版本？
> 
> 技术交流QQ群：825046920
> 微信群：搜索微信号wzk727912172，添加好友，备注（城市-github用户名），验证通过会加入群聊

**Comment by yanzu888** [comment]
Openstack Pike
openstack 3.12.1

**Comment by yanzu888** [comment]
> openstack使用的是哪个版本？
> 
> 技术交流QQ群：825046920
> 微信群：搜索微信号wzk727912172，添加好友，备注（城市-github用户名），验证通过会加入群聊

Openstack Pike
openstack 3.12.1
