### ISSUE TITLE
KubeOperator 如何安全停机和再启动？

### ISSUE THREAD

**Issue by yorkexing** [KubeOperator/KubeOperator#294]
**请描述您的需求或者改进建议.**
目前已经在线下开发环境使用上了KO
但在文档里面，没有看到如何对 KO和所管理的集群进行安全停机和重新启动的描述。
实际的需求就是：在后续机房逐渐的建立过程中，需要堆物理机停机、停电改造。

**请描述你建议的实现方案**
能否把这部分补上？

**Comment by wanghe-fit2cloud** [comment]
kubeoperator部署机上kubeops和docker等服务都是服务自启动，如需手动操作，直接systemctl操作
kubernetes集群节点上k8s等服务都是服务自启动，如需手动操作，直接systemctl操作
