### ISSUE TITLE
PPT 中的图片是空白 https://github.com/KubeOperator/KubeOperator/blob/master/KubeOperator_Intro.pdf

### ISSUE THREAD

**Issue by chengweiv5** [KubeOperator/KubeOperator#296]
https://github.com/KubeOperator/KubeOperator/blob/master/KubeOperator_Intro.pdf

![20200713164932](https://user-images.githubusercontent.com/689798/87284501-05ceee80-c529-11ea-97cc-9db1010d4243.png)

上面的图片是空白，应该是不正常的。

**Comment by KubeOperator** [comment]
我们这边是正常，是不是跟你的pdf工具有关系？

**Comment by chengweiv5** [comment]
我直接在浏览器中看的，debian + google chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by chengweiv5** [comment]
下载下来用浏览器打开是好的，可能是 github 本身渲染的问题。
