### ISSUE TITLE
官方文档有两张图片打不开 https://docs.kubeoperator.io/KubeOperator-v2.6/userguide-manual/

### ISSUE THREAD

**Issue by chengweiv5** [KubeOperator/KubeOperator#298]
5.2 集群升级 一节，如下截图

![20200714161433](https://user-images.githubusercontent.com/689798/87401753-26f91300-c5ed-11ea-9c8f-f172875bd5ff.png)

5.3 集群伸缩 一节，如下截图

![20200714161442](https://user-images.githubusercontent.com/689798/87401782-337d6b80-c5ed-11ea-9216-9f548f506ad5.png)

**Comment by wanghe-fit2cloud** [comment]
你好，感谢反馈信息，但我们内部没有复现此问题。

1、清除浏览器缓存重试看能否刷新出图片
2、更换其他浏览器重试

**Comment by chengweiv5** [comment]
多谢，确认是我这边的问题。
