### ISSUE TITLE
Spelling: Operator vs. Operater?

### ISSUE THREAD

**Issue by cclauss** [KubeOperator/KubeOperator#301]
Is it Operat[__or__](https://github.com/KubeOperator/KubeOperator/search?q=operator) or  Operat[__er__](https://github.com/KubeOperator/KubeOperator/search?q=operater)?  Consist usage might help.

**Comment by maninhill** [comment]
Operator

**Comment by cclauss** [comment]
So, should all these instances be corrected? https://github.com/KubeOperator/KubeOperator/search?q=operater
