### ISSUE TITLE
关于步骤无法跳过，一直处于复制 manifests至 deploy节点”这个步骤

### ISSUE THREAD

**Issue by bmw8080** [KubeOperator/KubeOperator#302]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？v2.6.23

**Bug 描述**
简要描述您碰到的问题
我还以为是我的环境问题。。
反复一直卡在“manifests : 复制 manifests至 deploy节点”这个步骤
**Bug 重现步骤**
TASK [deploy : 设置集群参数] *********************************************************
master1.kube.kube.com | SUCCESS | rc=0 >>
Cluster "kubernetes" set.

TASK [deploy : 设置客户端认证参数] ******************************************************
master1.kube.kube.com | SUCCESS | rc=0 >>
User "kube-proxy" set.

TASK [deploy : 设置上下文参数] ********************************************************
master1.kube.kube.com | SUCCESS | rc=0 >>
Context "default" created.

TASK [deploy : 选择默认上下文] ********************************************************
master1.kube.kube.com | SUCCESS | rc=0 >>
Switched to context "default".

TASK [deploy : 移动 kube-proxy.kubeconfig] ***************************************
master1.kube.kube.com | SUCCESS | rc=0 >>

TASK [manifests : 安装 rsync] ****************************************************
ok: [master1.kube.kube.com]
TASK [manifests : 复制 manifests至 deploy节点] **************************************

**期待的正确结果**
正确情况下应该是什么样的？
进入 kubeadmin init（貌似没有）
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/39630029/88082261-21369b00-cbb4-11ea-91da-da50535db55b.png)

**Comment by KubeOperator** [comment]
3.0 已经解决。
