### ISSUE TITLE
集群节点数量和项目下不符合

### ISSUE THREAD

**Issue by plateauandsp** [KubeOperator/KubeOperator#309]
1.做过节点减少后，又加节点，项目下资源数量统计和集群节点数量不符合
![image](https://user-images.githubusercontent.com/30932762/90251329-1815b280-de70-11ea-9530-94b9f020321c.png)
![image](https://user-images.githubusercontent.com/30932762/90251352-22d04780-de70-11ea-90cc-82a4ec8611f4.png)

**Comment by zhengkunwang223** [comment]
感谢您提出的问题，我们会在下个小版本进行修复
