### ISSUE TITLE
部署完成后页面 无法显示出来 好像是token没有获取到

### ISSUE THREAD

**Issue by liyansong** [KubeOperator/KubeOperator#315]
![image](https://user-images.githubusercontent.com/20124391/90352425-ec641980-e075-11ea-8ce5-0473be8348a5.png)
![image](https://user-images.githubusercontent.com/20124391/90352438-f84fdb80-e075-11ea-806b-9ca849821d85.png)
![image](https://user-images.githubusercontent.com/20124391/90352472-11f12300-e076-11ea-9e1a-5f42470d50a7.png)

**Comment by wanghe-fit2cloud** [comment]
最新发布的版本已修复该问题
