### ISSUE TITLE
ARM64架构版本无法正常启动

### ISSUE THREAD

**Issue by FrancisDrakeK** [KubeOperator/KubeOperator#316]
kubeoperator_server 与kubeoperator_kotf 一直在重启，详见下图

![image](https://user-images.githubusercontent.com/42175430/90356546-76b27a80-e082-11ea-9b9e-264e3743d98a.png)

kotf docker logs 如下
![image](https://user-images.githubusercontent.com/42175430/90356626-baa57f80-e082-11ea-9a29-42149feb3467.png)

server 无docker logs

**Comment by lvxiaohu** [comment]
暂时 kubeOperator 只支持部署在 x86的操作系统上。Kubernetes 节点可以支持 ARM64. 
![image](https://user-images.githubusercontent.com/29087369/90357139-7f0bb500-e084-11ea-9fc7-2867c16160ae.png)

**Comment by KubeOperator** [comment]
主要原因是 Terraform 官方不支持 arm 64，我们在寻找解决办法。
