### ISSUE TITLE
工具-kubeapps，点击“启用”按钮后页面无响应

### ISSUE THREAD

**Issue by wildish** [KubeOperator/KubeOperator#318]
F12查看响应，如下图

![image](https://user-images.githubusercontent.com/5975628/90387458-cc097e80-e0b8-11ea-9b21-2bf2a76dc439.png)

使用`koctl logs -f`查看服务端日志，可能有关联的如下：
```log
kobe_1        | time="2020-08-17T10:35:08Z" level=info msg="id:%s  content :%s8504bdf7-5712-401a-a07e-0bb0980a3469/usr/bin/ansible -e host_key_checking=False -i /usr/local/bin/kobe-inventory master -m setup" source="runner.go:56"
```

**Comment by Jimgong826** [comment]
离线部署，工具启用失败，一直在初始化转圈圈。。。
f12调试查看返回信息，kubeapps状态为Initializing，message:"failed post-install;unable to build kubenetes object for deleting hook kubeapps/templates/ apprepositories.yaml: unable to recognize "": no matches for kind "AppRepository"in version "kubeapps . com/v1alpha1""

**Comment by wanghe-fit2cloud** [comment]
进集群节点，观察所启用工具的pod处于什么状态，并提供一下日志信息。

**Comment by Jimgong826** [comment]
![日志1](https://user-images.githubusercontent.com/45098789/91800244-3c88d180-ec5b-11ea-9d2e-07b534d1ce79.png)
![日志2](https://user-images.githubusercontent.com/45098789/91800265-414d8580-ec5b-11ea-8c84-06c3be9c8aed.png)
![日志3](https://user-images.githubusercontent.com/45098789/91800288-46123980-ec5b-11ea-8750-e4c5d784e2d3.png)
![日志4](https://user-images.githubusercontent.com/45098789/91800312-4f030b00-ec5b-11ea-8de1-116729d9d082.png)
![日志5](https://user-images.githubusercontent.com/45098789/91800342-5f1aea80-ec5b-11ea-9389-1054a31b2337.png)
![日志6](https://user-images.githubusercontent.com/45098789/91800356-6510cb80-ec5b-11ea-8361-97c473330d96.png)

**Comment by wanghe-fit2cloud** [comment]
去节点上手动pull镜像 查看下失败原因

**Comment by Jimgong826** [comment]
> 去节点上手动pull镜像 查看下失败原因

由于是导入的已有集群（非ko创建），通过在每个节点配置/etc/docker/daemon.json文件，加入kubeoperator-ip:8082配置已成功解决，希望对其他人有所帮助！还是得仔细看文档（https://kubeoperator.io/docs/user_manual/cluster_import/），尴尬！！

**Comment by wanghe-fit2cloud** [comment]
文档链接: https://kubeoperator.io/docs/user_manual/cluster_import
