### ISSUE TITLE
自动模式Day0可用区部署上传镜像失败

### ISSUE THREAD

**Issue by toclyc** [KubeOperator/KubeOperator#323]
环境：Centos7.8  离线包安装KubeOperatorV3.0.2
部署模式：自动部署（vsphere）    Vcenter版本6.7
问题：Day0阶段，区域设置正常，到可用区设置的时候，不论默认模板或者采用自定义模板，状态均为上传镜像失败

**Comment by zhengkunwang223** [comment]
您好。已经复现了您说的问题，正在修复。马上就会发新版本。

**Comment by wanghe-fit2cloud** [comment]
v3.0.3版本已修复
