### ISSUE TITLE
希望备份存储增加本地存储方案

### ISSUE THREAD

**Issue by Jimgong826** [KubeOperator/KubeOperator#324]
目前备份存储只支持oss,s3,azure三种云端存储方案，希望增加本地存储方案（Ceph,nfs,nas）

**Comment by toclyc** [comment]
表示举手赞同，想做本地备份

**Comment by zhengkunwang223** [comment]
你好，感谢您提的建议，我们已经采纳，预计下个版本增加此功能。

**Comment by Jimgong826** [comment]
> 你好，感谢您提的建议，我们已经采纳，预计下个版本增加此功能。

感谢你们的回复与采纳，期待能早点看到！

**Comment by Jimgong826** [comment]
请问一下，此本地存储方案大概在你们那个版本会更新？大概时间是什么时候？

**Comment by zhengkunwang223** [comment]
> 请问一下，此本地存储方案大概在你们那个版本会更新？大概时间是什么时候？
大概在3.2版本更新 时间10月中旬

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持sftp
