### ISSUE TITLE
关于Day1阶段添加项目集群失败的问题

### ISSUE THREAD

**Issue by toclyc** [KubeOperator/KubeOperator#325]
环境：Centos7.8 离线包安装KubeOperatorV3.0.2
部署模式：自动部署（vsphere） Vcenter版本6.7
问题：Day0阶段，区域设置正常，到可用区设置的时候，不论默认模板或者采用自定义模板，状态均为上传镜像失败,此时采用应急方法，将vcenter内Centos7.8模板名称更改为kubeoperator_centos_7.6.1810，然后配置可用区模板为kubeoperator_centos_7.6.1810，此时可用区正常
在Day1阶段，创建项目集群的时候,显示状态为Failed

Failed内容：
rpc error: code = Unknown desc = data.vsphere_datacenter.dc: Refreshing state... data.vsphere_network.binjiangzongyuan: Refreshing state... data.vsphere_resource_pool.binjiangzongyuan: Refreshing state... data.vsphere_datastore.binjiangzongyuan: Refreshing state... data.vsphere_virtual_machine.binjiangzongyuan: Refreshing state... vsphere_virtual_machine.test-worker-1: Creating... vsphere_virtual_machine.test-master-1: Creating...  Error: folder '/test/vm/kubeoperator' not found  on main.tf line 44, in resource "vsphere_virtual_machine" "test-master-1":  44: resource "vsphere_virtual_machine" "test-master-1" {  Error: folder '/test/vm/kubeoperator' not found   on main.tf line 90, in resource "vsphere_virtual_machine" "test-worker-1":  90: resource "vsphere_virtual_machine" "test-worker-1" {  
重试
End of Modal Content

**Comment by toclyc** [comment]
并且，目前该集群在web无法被删除

**Comment by zhengkunwang223** [comment]
您好，感谢您提的问题。这个问题我们已经修复。不久就会发新版本，请耐心等待。

**Comment by Jimgong826** [comment]
> 并且，目前该集群在web无法被删除

同样创建失败的集群无法删除

**Comment by wanghe-fit2cloud** [comment]
v3.0.3版本已修复上述问题
