### ISSUE TITLE
kubeapps没有默认的CI/CD应用

### ISSUE THREAD

**Issue by lovese** [KubeOperator/KubeOperator#328]
转到 kubeapps 后，看不到 CI/CD 应用

![image](https://user-images.githubusercontent.com/13268438/92068530-bf379b00-edd9-11ea-8da0-9a47e8bd0fc7.png)

![image](https://user-images.githubusercontent.com/13268438/92068552-cf4f7a80-edd9-11ea-8f7c-c7299d8889fa.png)

**Comment by wanghe-fit2cloud** [comment]
kubectl -n kube-operator get pod  查看一下是否有不健康状态的应用

**Comment by lovese** [comment]
![image](https://user-images.githubusercontent.com/13268438/92080365-07fc4d80-edf4-11ea-8f71-f0ec42c57fdd.png)

**Comment by lovese** [comment]
有一个错误的

**Comment by wanghe-fit2cloud** [comment]
定位一下postgresql的错误日志

**Comment by lovese** [comment]
日志就一句
`chown: /bitnami/postgresql/data: Operation not permitted`

**Comment by lovese** [comment]
第一个 pod 的错误日志是：
`time="2020-09-03T09:23:22Z" level=fatal msg="Can't add chart repository to database: dial tcp 179.20.240.253:5432: connect: connection refused"`

**Comment by wanghe-fit2cloud** [comment]
> 日志就一句
> `chown: /bitnami/postgresql/data: Operation not permitted`

持久化存储权限问题啊

**Comment by lovese** [comment]
![image](https://user-images.githubusercontent.com/13268438/92103532-aac3c480-ee12-11ea-8f0c-93ab2bf1f9b5.png)
我的NAS里面有自动创建目录，这权限要怎么设置

**Comment by lovese** [comment]
![image](https://user-images.githubusercontent.com/13268438/92103898-29b8fd00-ee13-11ea-9621-2cfc9b086dfb.png)

**Comment by lovese** [comment]
![image](https://user-images.githubusercontent.com/13268438/92104812-75b87180-ee14-11ea-946c-f6bdd6d716ed.png)

**Comment by lovese** [comment]
感觉配置没什么问题呀

**Comment by wanghe-fit2cloud** [comment]
> 感觉配置没什么问题呀

问题在于容器内访问 nas 没有写的权限。
是否已将 pod ip 添加到白名单？
