### ISSUE TITLE
资产显示优化， Initializing显示优化

### ISSUE THREAD

**Issue by wojiushixiaobai** [KubeOperator/KubeOperator#329]
1、资产排序有点问题
项目-资源
![1](https://user-images.githubusercontent.com/24326988/92186175-873b6100-ee88-11ea-95fb-1694a74a956e.png)
项目-集群-资产
![2](https://user-images.githubusercontent.com/24326988/92186235-b6ea6900-ee88-11ea-834c-8551e5069f4a.png)

2、初始化页面显示的错误不友好，格式化一下比较好（或者只打印关键错误）。

**Comment by wanghe-fit2cloud** [comment]
我们会在近期版本中优化
