### ISSUE TITLE
希望支持对命名空间的动态管理

### ISSUE THREAD

**Issue by Jimgong826** [KubeOperator/KubeOperator#331]
目前命名空间只是一个静态的展示功能，希望能增加类似与新建这种动态管理功能，以及集群内变量的修改

**Comment by wanghe-fit2cloud** [comment]
近期发布版本会包含新建 namespace 功能。
有哪些集群变量准备通过ko页面来修改呢？能否按照优先级列举一清单。审核通过后，在后续版本加入。

**Comment by Jimgong826** [comment]
> 近期发布版本会包含新建 namespace 功能。
> 有哪些集群变量准备通过ko页面来修改呢？能否按照优先级列举一清单。审核通过后，在后续版本加入。

主要是一些全局变量与命名空间变量，例如仓库域名，项目ID这些可能在项目中被引用的值
