### ISSUE TITLE
手动模式提示用户进行资源授权

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#335]
1. 新增主机
2. 创建集群，找不到主机，这是因为主机没有授权给项目。建议在这个页面进行「显示」的提示。

![image](https://user-images.githubusercontent.com/41712985/92844885-ec5afd80-f418-11ea-92cd-a75b0e8ec0f9.png)

**Comment by awklinux** [comment]
出现同样的问题，不知道跟区域是不是有关系，但建立区域的地方，没有跟手动有关的选项

**Comment by awklinux** [comment]
找到了，在项目里，点击添加的项目，上面有三个选项 集群  成员  资源
选择资源，把之前添加的主机选中即可

**Comment by zhengkunwang223** [comment]
收到建议 感谢

**Comment by wanghe-fit2cloud** [comment]
新版本已添加提示
