### ISSUE TITLE
时间时区问题

### ISSUE THREAD

**Issue by byliyong** [KubeOperator/KubeOperator#336]
kubeopertator的web界面里大多数时间都和后台Linux系统一样，是**CST格式**的时间；

- 但在WebKubeCtl里，时间是**UTC制式**（相差八个小时，这个还好理解）；

- 另外，在**项目**->**集群**->**历史**记录里（如添加/删除节点的操作），这里记录的时间相差了12个小时，这个时区在国内用的少，可能会引起误解，望修正！

**Comment by byliyong** [comment]
**update:** 历史记录里相差12小时是因为那里设置的是12小时制，建议统一改为24小时制！

**Comment by Aaron3S** [comment]
最新的版本已经修复。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
