### ISSUE TITLE
ko 3.0.3 版本未能关闭 ssh 连接进程，导致占满系统进程资源

### ISSUE THREAD

**Issue by JokerDevops** [KubeOperator/KubeOperator#338]
# os version
CentOS Linux release 7.7.1908 (Core)
# kernel version
4.19.12-1.el7.elrepo.x86_64
# ko version 
3.0.3

# 问题现象
开启 ko 之后，进行 webkubectl 、安装升级 Kubernetes 集群。出现大量 ssh 连接未能关闭的情况。
![image](https://user-images.githubusercontent.com/41281305/93417115-d39b8d80-f8d9-11ea-9649-ebe7ab8ad636.png)

**Comment by Aaron3S** [comment]
已修复

**Comment by JokerDevops** [comment]
修复版本发布了吗？

**Comment by lvxiaohu** [comment]
> 修复版本发布了吗？

下一个版本修复

**Comment by lvxiaohu** [comment]
V3.2.0 已修复此问题
