### ISSUE TITLE
添加vsphere或者手动添加节点报错

### ISSUE THREAD

**Issue by xuze1993** [KubeOperator/KubeOperator#339]
ko的状态
![image](https://user-images.githubusercontent.com/35798540/93765296-388f1480-fc47-11ea-9793-bd485950998b.png)

vsphere的话第一步区域可以正常认证通过，添加可用区的时候就会ip范围报错；

![image](https://user-images.githubusercontent.com/35798540/93765097-ec43d480-fc46-11ea-90cf-0ebc09b17a31.png)
![image](https://user-images.githubusercontent.com/35798540/93765119-f2d24c00-fc46-11ea-9906-426b1fa754dc.png)

然后试了下手动添加节点，会卡在ssh报错，不知道怎么处理。ssh-keygen -R 清理过
![image](https://user-images.githubusercontent.com/35798540/93765208-16959200-fc47-11ea-87a7-b11202e97a91.png)
![image](https://user-images.githubusercontent.com/35798540/93765230-1d240980-fc47-11ea-9278-6c401311401a.png)

**Comment by zhengkunwang223** [comment]
> ko的状态
> ![image](https://user-images.githubusercontent.com/35798540/93765296-388f1480-fc47-11ea-9793-bd485950998b.png)
> 
> vsphere的话第一步区域可以正常认证通过，添加可用区的时候就会ip范围报错；
> 
> ![image](https://user-images.githubusercontent.com/35798540/93765097-ec43d480-fc46-11ea-90cf-0ebc09b17a31.png)
> ![image](https://user-images.githubusercontent.com/35798540/93765119-f2d24c00-fc46-11ea-9906-426b1fa754dc.png)
> 
> 然后试了下手动添加节点，会卡在ssh报错，不知道怎么处理。ssh-keygen -R 清理过
> ![image](https://user-images.githubusercontent.com/35798540/93765208-16959200-fc47-11ea-87a7-b11202e97a91.png)
> ![image](https://user-images.githubusercontent.com/35798540/93765230-1d240980-fc47-11ea-9278-6c401311401a.png)

1.您好 添加vsphere区域失败，您这个情况可能是vcenter没有创建集群
2.手动添加主机失败 看日志显示是链接失败 请检查KO部署机和添加主机之间的网络

**Comment by xuze1993** [comment]
> 
> 
> > ko的状态
> > ![image](https://user-images.githubusercontent.com/35798540/93765296-388f1480-fc47-11ea-9793-bd485950998b.png)
> > vsphere的话第一步区域可以正常认证通过，添加可用区的时候就会ip范围报错；
> > ![image](https://user-images.githubusercontent.com/35798540/93765097-ec43d480-fc46-11ea-90cf-0ebc09b17a31.png)
> > ![image](https://user-images.githubusercontent.com/35798540/93765119-f2d24c00-fc46-11ea-9906-426b1fa754dc.png)
> > 然后试了下手动添加节点，会卡在ssh报错，不知道怎么处理。ssh-keygen -R 清理过
> > ![image](https://user-images.githubusercontent.com/35798540/93765208-16959200-fc47-11ea-87a7-b11202e97a91.png)
> > ![image](https://user-images.githubusercontent.com/35798540/93765230-1d240980-fc47-11ea-9278-6c401311401a.png)
> 
> 1.您好 添加vsphere区域失败，您这个情况可能是vcenter没有创建集群
> 2.手动添加主机失败 看日志显示是链接失败 请检查KO部署机和添加主机之间的网络


1.vcentre的话是有集群的，第二步里的主机也是用这个登陆的账号创建的。
2.部署机和节点的ping是通的，手动ssh也可以登陆

**Comment by xuze1993** [comment]
我在群里问吧  这里问好像不太方便
