### ISSUE TITLE
pvc无法绑定pv

### ISSUE THREAD

**Issue by liwh1111** [KubeOperator/KubeOperator#340]
您好, 我创建了一个rook-ceph的储存类, 但是不知道为什么pv一直绑定不上, 这是我创建时一些相关的参数, 请帮忙看下

本地磁盘
![image](https://user-images.githubusercontent.com/63097736/94254404-4ef3e380-ff59-11ea-9e52-bc026580af62.png)

储存供应商, 状态是running
![image](https://user-images.githubusercontent.com/63097736/94254500-72b72980-ff59-11ea-8bc3-e61cc076bb8c.png)
![image](https://user-images.githubusercontent.com/63097736/94254567-8793bd00-ff59-11ea-9c58-8abb335a26ba.png)

我工具中启用了registy, 并且启用了存储,  但是相关的pvc一直pending
![image](https://user-images.githubusercontent.com/63097736/94254689-b6aa2e80-ff59-11ea-95af-679aea4da545.png)

![image](https://user-images.githubusercontent.com/63097736/94254799-d8a3b100-ff59-11ea-8ba8-3eba0bf440d0.png)

describe pvc
![image](https://user-images.githubusercontent.com/63097736/94254946-13a5e480-ff5a-11ea-894b-31a432f4f18d.png)

describe pod

**Comment by lvxiaohu** [comment]
使用 rook_ceph 你需要给每一个k8s集群节点单独添加一块 Disk，并且无需格式化。

**Comment by liwh1111** [comment]
谢谢, 添加了一个单独的disk解决了.

**Comment by lvxiaohu** [comment]
赞，我将关闭此 issue。
