### ISSUE TITLE
kubeOperator所在机器重启后, kubeOperator会报502错误

### ISSUE THREAD

**Issue by liwh1111** [KubeOperator/KubeOperator#342]
你好, kubeOperator所在机器重启后, kubeOperator会报502错误, 请问你们遇到过吗, 有什么解决办法吗

![image](https://user-images.githubusercontent.com/63097736/94512182-02a4ee00-024e-11eb-8948-a655101f0fae.png)

**Comment by wanghe-fit2cloud** [comment]
koctl restart 重启kubeoperator

**Comment by lvxiaohu** [comment]
重启可解决当前问题，升级至最新版本，已修复此问题。
