### ISSUE TITLE
初始化控制平面报错

### ISSUE THREAD

**Issue by 402309718** [KubeOperator/KubeOperator#343]
测试部署直接报错，命令单独机器可以执行
![image](https://user-images.githubusercontent.com/7498000/94517707-1571ef80-025b-11eb-89b6-5c443ad3f01d.png)

**Comment by wanghe-fit2cloud** [comment]
可以点击重试按钮，再次执行任务。
如还存在问题，请扫描官网交流群二维码，进群讨论。
