### ISSUE TITLE
3.1.1版本创建部署计划失败

### ISSUE THREAD

**Issue by yjeric2011** [KubeOperator/KubeOperator#345]
3.1.1版本测试了一下，在创建部署计划的时候对接VCENTER一直认证不通过。vc版本是6.7的。不知道是啥问题。确认我的VC账号密码是没问题的

**Comment by zhengkunwang223** [comment]
> 3.1.1版本测试了一下，在创建部署计划的时候对接VCENTER一直认证不通过。vc版本是6.7的。不知道是啥问题。确认我的VC账号密码是没问题的

您好 认证不通过是创建区域认证不通过吗？ 具体的报错信息有吗？

**Comment by yjeric2011** [comment]
> 
> 
> > 3.1.1版本测试了一下，在创建部署计划的时候对接VCENTER一直认证不通过。vc版本是6.7的。不知道是啥问题。确认我的VC账号密码是没问题的
> 
> 您好 认证不通过是创建区域认证不通过吗？ 具体的报错信息有吗？

![图片](https://user-images.githubusercontent.com/30171519/95645410-3f47d380-0af1-11eb-872c-a49b720b8b3c.png)
是的，在创建区域的时候添加VC，提示认证不通过，这个和license有没有关系？
![图片](https://user-images.githubusercontent.com/30171519/95645423-60102900-0af1-11eb-8008-0f2a0f259c30.png)

**Comment by zhengkunwang223** [comment]
> > > 3.1.1版本测试了一下，在创建部署计划的时候对接VCENTER一直认证不通过。vc版本是6.7的。不知道是啥问题。确认我的VC账号密码是没问题的
> > 
> > 
> > 您好 认证不通过是创建区域认证不通过吗？ 具体的报错信息有吗？
> 
> ![图片](https://user-images.githubusercontent.com/30171519/95645410-3f47d380-0af1-11eb-872c-a49b720b8b3c.png)
> 是的，在创建区域的时候添加VC，提示认证不通过，这个和license有没有关系？
> ![图片](https://user-images.githubusercontent.com/30171519/95645423-60102900-0af1-11eb-8008-0f2a0f259c30.png)

您好 验证未通过有用户名密码的原因  也有网络的原因 请检查KO主机和VC主机之间的网络连通性

**Comment by yjeric2011** [comment]
> 
> 
> > > > 3.1.1版本测试了一下，在创建部署计划的时候对接VCENTER一直认证不通过。vc版本是6.7的。不知道是啥问题。确认我的VC账号密码是没问题的
> > > 
> > > 
> > > 您好 认证不通过是创建区域认证不通过吗？ 具体的报错信息有吗？
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/30171519/95645410-3f47d380-0af1-11eb-872c-a49b720b8b3c.png)
> > 是的，在创建区域的时候添加VC，提示认证不通过，这个和license有没有关系？
> > ![图片](https://user-images.githubusercontent.com/30171519/95645423-60102900-0af1-11eb-8008-0f2a0f259c30.png)
> 
> 您好 验证未通过有用户名密码的原因 也有网络的原因 请检查KO主机和VC主机之间的网络连通性

网络没问题KUBEOPS的网络是和VC同网段的，KUBEOPS是172.20.56.15
![图片](https://user-images.githubusercontent.com/30171519/95645486-13791d80-0af2-11eb-9c7b-29a9e74e29df.png)

**Comment by zhengkunwang223** [comment]
> > > > > 3.1.1版本测试了一下，在创建部署计划的时候对接VCENTER一直认证不通过。vc版本是6.7的。不知道是啥问题。确认我的VC账号密码是没问题的
> > > > 
> > > > 
> > > > 您好 认证不通过是创建区域认证不通过吗？ 具体的报错信息有吗？
> > > 
> > > 
> > > ![图片](https://user-images.githubusercontent.com/30171519/95645410-3f47d380-0af1-11eb-872c-a49b720b8b3c.png)
> > > 是的，在创建区域的时候添加VC，提示认证不通过，这个和license有没有关系？
> > > ![图片](https://user-images.githubusercontent.com/30171519/95645423-60102900-0af1-11eb-8008-0f2a0f259c30.png)
> > 
> > 
> > 您好 验证未通过有用户名密码的原因 也有网络的原因 请检查KO主机和VC主机之间的网络连通性
> 
> 网络没问题KUBEOPS的网络是和VC同网段的，KUBEOPS是172.20.56.15
> ![图片](https://user-images.githubusercontent.com/30171519/95645486-13791d80-0af2-11eb-9c7b-29a9e74e29df.png)

有检查防火墙吗 你进入kubeoperator_server容器中 ping一下 VC的IP
