### ISSUE TITLE
请问部署机和master放在一台机器上会有问题吗

### ISSUE THREAD

**Issue by liwh1111** [KubeOperator/KubeOperator#346]
你好, 由于前期测试只有三台机器, 部署机和master放在一台配置比较高的机器上可以吗

**Comment by wanghe-fit2cloud** [comment]
你好，需要单独提供一台部署机，不能和集群节点公用

**Comment by zhengkunwang223** [comment]
> 你好, 由于前期测试只有三台机器, 部署机和master放在一台配置比较高的机器上可以吗

三台机器可以一台装KO  另外两台用作master和worker节点

**Comment by liwh1111** [comment]
好的,谢谢
