### ISSUE TITLE
在控制面板上开启prometheus监控工具，禁用后重新打开，一直无法正常使用

### ISSUE THREAD

**Issue by GDkunban** [KubeOperator/KubeOperator#349]
后面在官方的大佬协助下：原来是在ko的面板上禁用掉prometheus后，其数据源信息并没有及时更新。
解决方案：
1.打开grafana界面，一般是IP/grafana（如我的地址为192.168.3.152/grafana/dashboards）
2.删除选择已有的集群信息（如我的集群名字为test）
![image](https://user-images.githubusercontent.com/49048640/95728750-74e5eb80-0cae-11eb-8dd6-f1ad23c521ba.png)
3.删除旧的prometheus数据源（如我的地址为：192.168.3.152/grafana/dataSources）：
![image](https://user-images.githubusercontent.com/49048640/95729187-1705d380-0caf-11eb-9264-9b9638294fa7.png)

4.重新在ko的web控制界面开启监控功能

**Comment by lvxiaohu** [comment]
改问题已定位解决！
