### ISSUE TITLE
手动安装的集群删除后不能删除主机资源

### ISSUE THREAD

**Issue by MignonZhang** [KubeOperator/KubeOperator#352]
手动安装的集群删除后不能删除主机资源

**Comment by zhengkunwang223** [comment]
> 手动安装的集群删除后不能删除主机资源

您好 删除的时候有提示吗？

**Comment by wanghe-fit2cloud** [comment]
进入项目-资源，取消授权，错误信息如下：
![image](https://user-images.githubusercontent.com/46734380/96397176-832a8f00-11fb-11eb-8dcf-facf2f73be42.png)

**Comment by dorothytiner0324** [comment]
我是扩容的时候一直显示销毁中，可能是虚机因为虚机不是新建的，但是想把这个主机资源删除的时候，也是上面这个报错，点击删除没反应
