### ISSUE TITLE
3.2.0版本在OpenStack集群R版创建kubernetes集群无响应

### ISSUE THREAD

**Issue by ningdaqing** [KubeOperator/KubeOperator#354]
3.2.0版本OpenStack集群R版本创建Kubernetes集群一支处于创建状态
web界面现象：
![image](https://user-images.githubusercontent.com/29521063/96976715-bdbf5f00-154e-11eb-8649-e06ac7ef9dc8.png)

后台日志报错：
![image](https://user-images.githubusercontent.com/29521063/96976506-881a7600-154e-11eb-8111-9f396c47fa35.png)

**Comment by zhengkunwang223** [comment]
> 3.2.0版本OpenStack集群R版本创建Kubernetes集群一支处于创建状态
> web界面现象：
> ![image](https://user-images.githubusercontent.com/29521063/96976715-bdbf5f00-154e-11eb-8649-e06ac7ef9dc8.png)
> 
> 后台日志报错：
> ![image](https://user-images.githubusercontent.com/29521063/96976506-881a7600-154e-11eb-8111-9f396c47fa35.png)

后台日志报错的截图能发全一点吗
