### ISSUE TITLE
required authorization token not found

### ISSUE THREAD

**Issue by zzq900503** [KubeOperator/KubeOperator#356]
KubeOperator版本3.2
使用离线安装包安装
kubeoperator-release-v3.2.0.tar.gz

系统:
centos 7.5

k8s集群项目 安装完成后 概览以及节点等页面显示不出来，F12查看 页面请求 相关api报错required authorization token not found

k8s集群项目基本信息

名称 k8s-private
版本 v1.18.6
网络类型 flannel
容器运行时  docker
架构  amd64
来源  本地

例如:
http://192.168.30.130/api/v1/clusters/secret/k8s-private?l=zh-CN

返回为:
{"data":null,"msg":"required authorization token not found"}

@shenchenyang   有大佬帮忙看看么

**Comment by zhengkunwang223** [comment]
> KubeOperator版本3.2
> 使用离线安装包安装
> kubeoperator-release-v3.2.0.tar.gz
> 
> 系统:
> centos 7.5
> 
> k8s集群项目 安装完成后 概览以及节点等页面显示不出来，F12查看 页面请求 相关api报错required authorization token not found
> 
> k8s集群项目基本信息
> 
> 名称 k8s-private
> 版本 v1.18.6
> 网络类型 flannel
> 容器运行时 docker
> 架构 amd64
> 来源 本地
> 
> 例如:
> http://192.168.30.130/api/v1/clusters/secret/k8s-private?l=zh-CN
> 
> 返回为:
> {"data":null,"msg":"required authorization token not found"}
> 
> @shenchenyang 有大佬帮忙看看么

您好 进一下企业微信群吧，群里可以帮你解决

**Comment by zzq900503** [comment]
https://github.com/KubeOperator/KubeOperator/issues/315  好的 谢谢 应该不是我一个人 遇到同样的问题

**Comment by Aaron3S** [comment]
fixed
