### ISSUE TITLE
kubeoperator 创建集群失败

### ISSUE THREAD

**Issue by zhaolao** [KubeOperator/KubeOperator#360]
各位专家，我是个新人，安装了好几次；每一次都报这个错误，请大师指点迷津；
日志信息：PLAY [all] *********************************************************************

TASK [prepare/docker : Get whether Containerd has been installed] **************
changed: [zhao-worker-1]
changed: [zhao-master-1]
changed: [zhao-worker-2]

TASK [prepare/docker : Fail info] **********************************************
fatal: [zhao-master-1]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
fatal: [zhao-worker-1]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
fatal: [zhao-worker-2]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}

PLAY RECAP *********************************************************************
zhao-master-1              : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
zhao-worker-1              : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
zhao-worker-2              : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

PLAY [all] *********************************************************************

TASK [prepare/docker : Get whether Containerd has been installed] **************
changed: [zhao-worker-2]
changed: [zhao-master-1]
changed: [zhao-worker-1]

TASK [prepare/docker : Fail info] **********************************************
fatal: [zhao-master-1]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
fatal: [zhao-worker-1]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
fatal: [zhao-worker-2]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}

PLAY RECAP *********************************************************************
zhao-master-1              : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
zhao-worker-1              : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
zhao-worker-2              : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=

**Comment by zhengkunwang223** [comment]
> 各位专家，我是个新人，安装了好几次；每一次都报这个错误，请大师指点迷津；
> 日志信息：PLAY [all] *********************************************************************
> 
> TASK [prepare/docker : Get whether Containerd has been installed] **************
> changed: [zhao-worker-1]
> changed: [zhao-master-1]
> changed: [zhao-worker-2]
> 
> TASK [prepare/docker : Fail info] **********************************************
> fatal: [zhao-master-1]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
> fatal: [zhao-worker-1]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
> fatal: [zhao-worker-2]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
> 
> PLAY RECAP *********************************************************************
> zhao-master-1 : ok=1 changed=1 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
> zhao-worker-1 : ok=1 changed=1 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
> zhao-worker-2 : ok=1 changed=1 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
> 
> PLAY [all] *********************************************************************
> 
> TASK [prepare/docker : Get whether Containerd has been installed] **************
> changed: [zhao-worker-2]
> changed: [zhao-master-1]
> changed: [zhao-worker-1]
> 
> TASK [prepare/docker : Fail info] **********************************************
> fatal: [zhao-master-1]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
> fatal: [zhao-worker-1]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
> fatal: [zhao-worker-2]: FAILED! => {"changed": false, "msg": "Containerd already installed!"}
> 
> PLAY RECAP *********************************************************************
> zhao-master-1 : ok=1 changed=1 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
> zhao-worker-1 : ok=1 changed=1 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
> zhao-worker-2 : ok=1 changed=1 unreachable=0 failed=1 skipped=0 rescued=

您好，您版本是多少 ，手动模式还是自动模式？公网环境还是内网环境？操作系统版本是多少？

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/99239483-158f7400-2836-11eb-9198-5e89a80994c3.png)
你选择安装的运行时是docker，但主机中已经安装了Containerd，需卸载
最好能提供全新的主机环境
