### ISSUE TITLE
咨询一下kubeoperator企业版本

### ISSUE THREAD

**Issue by houfangdong** [KubeOperator/KubeOperator#361]
hello，有三个问题想咨询一下，
1、企业版本的主要用途是可以离线安装？
2、企业试用怎么理解？
3、社区代码支持构建企业版本吗？

**Comment by zhengkunwang223** [comment]
1、主要是提供x-pack包，在线、离线安装都支持
2、https://kubeoperator.io/docs/#_5 企业版试用
3、不支持

**Comment by cnwelee** [comment]
现在用的开源版，是可以通过安装x-pack包升级到企业版本吗？ @zhengkunwang223 
LDAP这种功能对企业还是很有用的

**Comment by zhengkunwang223** [comment]
> 现在用的开源版，是可以通过安装x-pack包升级到企业版本吗？ @zhengkunwang223
> LDAP这种功能对企业还是很有用的

通过导入license 可以升级到企业版本 使用 x-pack 包含的功能
