### ISSUE TITLE
请问如何重置管理员密码？

### ISSUE THREAD

**Issue by yearnxiao** [KubeOperator/KubeOperator#364]
请问如何重置管理员密码？

**Comment by wanghe-fit2cloud** [comment]
3.4.0版本将提供密码重置功能（12月10号发布）

之前版本要重置密码，可以手动修改数据库，命令如下：
1、进入mysql容器：
$ docker exec -it kubeoperator_mysql mysql -uroot -pKubeOperator123@mysql
2、执行mysql命令：
$ use ko;
$ update ko_user set password='47zHCOqO84rdzGgxw5XPfgDEapoOMXbgJnryG32xp6Y='  where name='admin';

**Comment by lvxiaohu** [comment]
在 v3.4.0 版本也可通过邮箱找回密码，前提配置好邮箱服务器，用户邮箱信息填写正确。

**Comment by yearnxiao** [comment]
> 在 v3.4.0 版本也可通过邮箱找回密码，前提配置好邮箱服务器，用户邮箱信息填写正确。

开发者上面已经说了，你再重复一遍是几个意思？
