### ISSUE TITLE
3.3.1版本手动创建集群，发现主机未加入集群中

### ISSUE THREAD

**Issue by cjwts** [KubeOperator/KubeOperator#365]
![图片](https://user-images.githubusercontent.com/30405402/100697642-835ca380-33d1-11eb-9568-67ef71e22252.png)
![图片](https://user-images.githubusercontent.com/30405402/100697619-750e8780-33d1-11eb-9eda-4dcb7bec138e.png)
![图片](https://user-images.githubusercontent.com/30405402/100697563-4b556080-33d1-11eb-805f-a71ebc213425.png)
222节点已经加入至集群中了，但是未在主机列表中显示

**Comment by wanghe-fit2cloud** [comment]
开发环境已复现该问题，在下个版本中修复。
