### ISSUE TITLE
初始化控制平面 异常

### ISSUE THREAD

**Issue by xiaoliang1** [KubeOperator/KubeOperator#366]
这是拉不到镜像嘛，应该如何去修正呢
{"ticket-master-1":"{\"_ansible_no_log\":false,\"action\":\"command\",\"changed\":true,\"cmd\":\"kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml\",\"delta\":\"0:00:21.633815\",\"end\":\"2020-12-02 17:34:55.535206\",\"failed\":true,\"invocation\":{\"module_args\":{\"_raw_params\":\"kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml\",\"_uses_shell\":true,\"argv\":null,\"chdir\":null,\"creates\":null,\"executable\":null,\"removes\":null,\"stdin\":null,\"stdin_add_newline\":true,\"strip_empty_ends\":true,\"warn\":true}},\"msg\":\"non-zero return code\",\"rc\":1,\"start\":\"2020-12-02 17:34:33.901391\",\"stderr\":\"W1202 17:34:34.125516 1042 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]\\n\\t[WARNING IsDockerSystemdCheck]: detected \\\"cgroupfs\\\" as the Docker cgroup driver. The recommended driver is \\\"systemd\\\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\\nerror execution phase preflight: [preflight] Some fatal errors occurred:\\n\\t[ERROR ImagePull]: failed to pull image 172.26.156.150:8082/coredns/coredns:1.6.7: output: Error response from daemon: manifest for 172.26.156.150:8082/coredns/coredns:1.6.7 not found: manifest unknown: manifest unknown\\n, error: exit status 1\\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\\nTo see the stack trace of this error execute with --v=5 or higher\",\"stderr_lines\":[\"W1202 17:34:34.125516 1042 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]\",\"\\t[WARNING IsDockerSystemdCheck]: detected \\\"cgroupfs\\\" as the Docker cgroup driver. The recommended driver is \\\"systemd\\\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\",\"error execution phase preflight: [preflight] Some fatal errors occurred:\",\"\\t[ERROR ImagePull]: failed to pull image 172.26.156.150:8082/coredns/coredns:1.6.7: output: Error response from daemon: manifest for 172.26.156.150:8082/coredns/coredns:1.6.7 not found: manifest unknown: manifest unknown\",\", error: exit status 1\",\"[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\",\"To see the stack trace of this error execute with --v=5 or higher\"],\"stdout\":\"[init] Using Kubernetes version: v1.18.10\\n[preflight] Running pre-flight checks\\n[preflight] Pulling images required for setting up a Kubernetes cluster\\n[preflight] This might take a minute or two, depending on the speed of your internet connection\\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'\",\"stdout_lines\":[\"[init] Using Kubernetes version: v1.18.10\",\"[preflight] Running pre-flight checks\",\"[preflight] Pulling images required for setting up a Kubernetes cluster\",\"[preflight] This might take a minute or two, depending on the speed of your internet connection\",\"[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'\"]}"}

**Comment by wanghe-fit2cloud** [comment]
$ koctl status 
查看服务运行状态，检测kubeoperator_nexus服务运行是否正常

**Comment by xiaoliang1** [comment]
状态属于正常
![image](https://user-images.githubusercontent.com/13740826/100858521-10ceef00-34c9-11eb-85aa-afc5e38cac63.png)

**Comment by wanghe-fit2cloud** [comment]
部署机firewalld什么状态

**Comment by xiaoliang1** [comment]
防火墙关闭状态，setlinux  disabled 状态 ，系统是centos7.4

**Comment by wanghe-fit2cloud** [comment]
1、看下kubeoperator_nexus日志，是否有异常
2、在集群节点手动pull coredns镜像，看能否成功

**Comment by xiaoliang1** [comment]
![image](https://user-images.githubusercontent.com/13740826/100860936-1da11200-34cc-11eb-8e59-a7ef4197d1cb.png)
不知，是不是这个日志，节点手动操作错误：

![image](https://user-images.githubusercontent.com/13740826/100861214-796b9b00-34cc-11eb-9a70-d1089145034d.png)

**Comment by xiaoliang1** [comment]
nexus 日志
![image](https://user-images.githubusercontent.com/13740826/100861301-9902c380-34cc-11eb-9ab8-20ed93162131.png)
节点手动操作
![image](https://user-images.githubusercontent.com/13740826/100861342-a91aa300-34cc-11eb-9d05-5440be185727.png)

**Comment by xiaoliang1** [comment]
nexus日志 超时：
![image](https://user-images.githubusercontent.com/13740826/100861438-c7809e80-34cc-11eb-9385-27f6e403653e.png)

节点shoud手动操作：
![image](https://user-images.githubusercontent.com/13740826/100861473-d6ffe780-34cc-11eb-9ae9-0db3593ff238.png)

**Comment by wanghe-fit2cloud** [comment]
docker pull 172.26.156.150:8082/coredns/coredns:1.6.7

**Comment by xiaoliang1** [comment]
已经找到原因，我重启一下服务器，应该是网络问题，有的配置修改完了，忘记重启，谢谢大佬支持
