### ISSUE TITLE
在部署时 mysql容器启动不起来

### ISSUE THREAD

**Issue by 1212W** [KubeOperator/KubeOperator#372]
在部署时 mysql容器启动不起来

**Comment by wanghe-fit2cloud** [comment]
1、使用的哪个版本？
2、部署KO的服务器操作系统是什么？
3、提供一下错误信息。

提供一下可参考的信息

**Comment by 1212W** [comment]
使用的是 v3.2.0
服务器操作系统是Centos7.9








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KubeOperator/KubeOperator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月6日(星期三) 中午1:54
收件人:&nbsp;"KubeOperator/KubeOperator"<KubeOperator@noreply.github.com&gt;;
抄送:&nbsp;"吴法无天"<2915130958@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KubeOperator/KubeOperator] 在部署时 mysql容器启动不起来 (#372)





 
1、使用的哪个版本？
 2、部署KO的服务器操作系统是什么？
 3、提供一下错误信息。
 
提供一下可参考的信息

**Comment by 1212W** [comment]
使用的是 v3.2.0
服务器操作系统是Centos7.9
![image](https://user-images.githubusercontent.com/37301525/103740566-6c454d00-5032-11eb-9c33-4586a7945125.png)
![image](https://user-images.githubusercontent.com/37301525/103740585-78310f00-5032-11eb-8dff-1fe642daa396.png)
