### ISSUE TITLE
页面显示的storage provider的状态对不上

### ISSUE THREAD

**Issue by liuchangfitcloud** [KubeOperator/KubeOperator#373]
存储提供商pod的状态与页面无法对应
![1251610100151_ pic](https://user-images.githubusercontent.com/44662176/104002643-4fe51400-51dc-11eb-8c39-ee8e298e2bef.jpg)
![1221610100128_ pic_hd](https://user-images.githubusercontent.com/44662176/104002649-51aed780-51dc-11eb-9b1b-5221533dfea1.jpg)

**Comment by wanghe-fit2cloud** [comment]
感谢！该问题在后续版本中解决

**Comment by wanghe-fit2cloud** [comment]
新版本该问题已修复
