### ISSUE TITLE
kubeOperator部署的k8s高可用具体的实现是什么? 

### ISSUE THREAD

**Issue by oldthreefeng** [KubeOperator/KubeOperator#378]
比如 sealyun 采用的是worker节点守护一个ipvs规则去实现高可用
比如 kubespray采用的是部署 haproxy 实现的高可用.

kubeOperator呢?  具体的实现架构图上好像没说明.

**Comment by wanghe-fit2cloud** [comment]
worker 节点部署 haproxy.

**Comment by oldthreefeng** [comment]
感谢.
