### ISSUE TITLE
自定义安装路径，在线升级完成后koctl脚本中KO_BASE为默认值/opt而不是自定义安装的值

### ISSUE THREAD

**Issue by 4021019** [KubeOperator/KubeOperator#380]
自定义安装路径，在线升级完成后koctl脚本中KO_BASE为默认值/opt而不是自定义安装的值/u01
升级后启动异常，为找不到/opt
![image](https://user-images.githubusercontent.com/5188916/107133117-ee6dad80-691f-11eb-8e33-ad778c961637.png)

在线升级下载的包已经自动更新KO_BASE
![image](https://user-images.githubusercontent.com/5188916/107133171-51f7db00-6920-11eb-81fa-03b71f2b8e7f.png)

而执行路径 /usr/local/bin/koctl 脚本则没有更新为自定义值
![image](https://user-images.githubusercontent.com/5188916/107133196-9b482a80-6920-11eb-9d9e-d8f8ea9d9128.png)

更新后启动正常
![image](https://user-images.githubusercontent.com/5188916/107133385-7359c680-6922-11eb-9933-2ef4dd6ee5a0.png)

**Comment by lvxiaohu** [comment]
你好，我看到并验证了这个问题，在自定义安装目录的环境中的确是存在的，首先不需要过于担心，此问题不会影响你到你的集群和数据等。非常抱歉，原因是此次安装升级做了较大调整，包括对密码高度加密等，同时也是为了方便后面的升级和优化，升级脚本本身没有问题，但是升级从低版本升级到 v3.5.1无法特别好到兼容。出现以上问题可通过以下方法解决：


- 执行koctl upgrade 失败后，如出现上述错误
```
$ vim /usr/local/bin/koctl +5
# 将 /data 替换为你 KubeOperator 安装目录
KO_BASE=/data

# 替换完成后重新执行升级
$ koctl upgrade
```

如升级过程中出现错误，可以尝试重新执行 koctl upgrade 进行升级
