### ISSUE TITLE
kubeapps商店应用问题反馈

### ISSUE THREAD

**Issue by wojiushixiaobai** [KubeOperator/KubeOperator#383]
版本 v3.5.2
    v3.5.0 升级到 v3.5.2

- [ ] 应用 logo 加载失败
- [ ] 如果在启用 kubeapps 时开启了存储，商店里面的应用为空

**Comment by lvxiaohu** [comment]
1. 应用 logo 加载失败
应用 logo 都为官方知道logo地址，可以F12看下logo都地址是否可以正常访问到

2. 如果在启用 kubeapps 时开启了存储，商店里面的应用为空
应用商店到应用为空和开启存储没有关系，可以检查一下几个方面：
- [ ] kubeapps配置的chartmuseum仓库有chart
- [ ] kubeapps的同步任务是正常的，如不正常，可能是由于网络等方面等原因，再进一步排查

- [ ]

**Comment by lvxiaohu** [comment]
1. 应用 logo 加载失败
应用 logo 都为官方知道logo地址，可以F12看下logo都地址是否可以正常访问到

2. 如果在启用 kubeapps 时开启了存储，商店里面的应用为空
应用商店到应用为空和开启存储没有关系，可以检查一下几个方面：
- [ ] kubeapps配置的chartmuseum仓库有chart
- [ ] kubeapps的同步任务是正常的，如不正常，可能是由于网络等方面等原因，再进一步排查
