### ISSUE TITLE
对接OpenStack遇到的问题

### ISSUE THREAD

**Issue by shake** [KubeOperator/KubeOperator#385]
希望通过这个issue，解决所有KO对接OpenStack的相关问题。把我一周测试遇到的问题总结一下。

1: 目前无法实现自动安装，这个问题，已经反馈和定位，已经会在下一个版本发布修复，这个密切关注。

2: 创建的虚拟机的密码，是自己指定的，而不是KO默认的，这个问题也确认，等待修复。

3: CSI 对接Cinder，我这边遇到问题，https://github.com/kubernetes/cloud-provider-openstack/issues/1435 ，具体的bug描述。目前还不能确实这是bug。不知道大家对接cinder的情况如何。

对于KO来说，在产品上直接集成对接Cinder存储，降低用户使用容器的存储的难度。这是很有价值的东西。

**Comment by zhengkunwang223** [comment]
> 希望通过这个issue，解决所有KO对接OpenStack的相关问题。把我一周测试遇到的问题总结一下。
> 
> 1: 目前无法实现自动安装，这个问题，已经反馈和定位，已经会在下一个版本发布修复，这个密切关注。
> 
> 2: 创建的虚拟机的密码，是自己指定的，而不是KO默认的，这个问题也确认，等待修复。
> 
> 3: CSI 对接Cinder，我这边遇到问题，[kubernetes/cloud-provider-openstack#1435](https://github.com/kubernetes/cloud-provider-openstack/issues/1435) ，具体的bug描述。目前还不能确实这是bug。不知道大家对接cinder的情况如何。
> 
> 对于KO来说，在产品上直接集成对接Cinder存储，降低用户使用容器的存储的难度。这是很有价值的东西。

您好 前两个问题我们已经修复 请等待3.6版本的发布 
第三个问题是kubernetes的使用问题 不是我们平台的BUG 这个问题我们会关注

**Comment by shake** [comment]
关于第三个问题，需要定位，确认是csi的驱动的问题。在你们的环境中也是一样的话。那么就好办了。

这个csi的插件的项目负责人，我已经联系，等待确认，修复应该不难。就是多了一个反斜杠而已。

**Comment by shake** [comment]
还有一个小小建议，填写keystone地址的地方，提示，有点误解  。写成这样，估计会大幅减少错误

x.x.x.x:5000/v3

**Comment by shake** [comment]
KO 使用CSI，对接Cinder，已经测试通过。主要原因是因为我们使用的是OpenStack的R版本，cinder的正则有bug，你需要打一个patch就可以，在上面的地址有相关的信息。最新的两个版本的的Cinder，应该是没这个问题。

https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md

希望KO早日集成。
