### ISSUE TITLE
install kubeapps-plus

### ISSUE THREAD

**Issue by ckgmg** [KubeOperator/KubeOperator#386]
helm install kubeapps-plus --namespace kubeapps-plus ./chart
 
Secret "sh.helm.release.v1.kubeapps-plus.v1" is invalid: data: Too long: must have at most 1048576 characters

**Comment by wanghe-fit2cloud** [comment]
该项目已停止维护，如有问题，可参考官方项目：https://github.com/kubeapps/kubeapps
