### ISSUE TITLE
Wrong grafana image on v3.6.0

### ISSUE THREAD

**Issue by foofalse** [KubeOperator/KubeOperator#388]
When deploy grafana from tools plane, got  error 'Failed to pull image "registry.kubeoperator.io:8082/grafana/grafana:7.3.3": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.kubeoperator.io:8082/grafana/grafana:7.3.3 not found: manifest unknown: manifest unknown'.

From Nexus, I found the right image is registry.kubeoperator.io:8082/kubeoperator/grafana:7.3.3 .

so, need to fixup the image name in the deploy yaml.

**Comment by wanghe-fit2cloud** [comment]
ok, which version do you have installed?

**Comment by wanghe-fit2cloud** [comment]
the grafana image cached in the offline package is incorrect, we will fix it in the next version

**Comment by wanghe-fit2cloud** [comment]
This issue has been fixed in a new release
