### ISSUE TITLE
在线安装nexus URL 配置错误 导致安装失败

### ISSUE THREAD

**Issue by shake** [KubeOperator/KubeOperator#391]
我是在阿里云做的这个测试，可以反复重现，

1： 登陆阿里云，创建一个vpc，lan，安全组打开所有的端口
2：创建虚拟机，放在vpc 里面，我专门设置的固定ip地址：192.168.10.10，用来安装kubeoperator
3：对于阿里云来说，你让vpc里的虚拟机访问公网，有2种方式，一种是使用NAT网关，一种是直接绑定公网IP地址给这个虚拟机。如果是通过NAT网关，应该是没问题，如果是给虚拟机直接绑定公网ip地址，来安装kubeoperator，就有问题。
4：装完kubeoperator后，你登陆nexus，你会发现repo 地址，都是公网的IP，甚至我创建一个新的repo，repo的URL，也是公网的URL。
5: 我尝试吧kubeoperator的机器的repo，修改成 指向内网的IP，访问时失败的，指向公网的ip是没问题的。

[Centos-Base]
name=CentOS Base
baseurl=http://192.168.10.10:8081/repository/centos-base/7/extras/$basearch/
enabled=1
gpgcheck=0
protect=1

[Centos-Extras]
name=CentOS Extras
baseurl=http://192.168.10.10:8081/repository/centos-base/7/os/$basearch/
enabled=1
gpgcheck=0
protect=1

[Centos-epel]
name=CentOS epel
baseurl=http://192.168.10.10:8081/repository/centos-epel/7/$basearch/
enabled=1
gpgcheck=0
protect=1

**Comment by wanghe-fit2cloud** [comment]
v3.7.2版本已修复该问题
