### ISSUE TITLE
自动部署模式下克隆出来的虚拟机异常导致部署失败

### ISSUE THREAD

**Issue by drummerglen** [KubeOperator/KubeOperator#392]
环境描述：
Kubeoperator 3.7.2
vCenter 6.7u2
故障问题：
虚拟机模版 SCSI 控制器 采用的是“LSI Logic 并行”，克隆后kubeoperator对虚拟机进行了自定义设置，把控制器类型改为了“VMware准虚拟”，导致虚拟开机后无法正常进入系统，认不到磁盘，最终导致部署失败

**Comment by drummerglen** [comment]
问题同样发生在扩展节点的场景下，之前手动把克隆的节点控制器类型改回原来的类型可以完成集群自动部署，但是扩展节点ko又会把所有节点的控制器类型改为VMware准虚拟化，导致集群失败

**Comment by wanghe-fit2cloud** [comment]
反馈已收到。
可以进入技术交流群来详细讨论该问题：https://kubeoperator.io/docs/about/contact/
