### ISSUE TITLE
仓库设置支持自定义端口

### ISSUE THREAD

**Issue by huguangya** [KubeOperator/KubeOperator#395]
目前KO针对混合架构的支持需要添加多个架构的仓库，且因为端口已经默认指定了8081-8083，所以一个节点上只能配置一个仓库；针对以上情况，能否支持自定义端口，这样的话就可以添加一个节点的多个仓库到KO中来

**Comment by wanghe-fit2cloud** [comment]
收到。待技术调研通过并确定具体实现方案后，我们会在下一个版本中发布该需求

**Comment by lvxiaohu** [comment]
自定义仓库端口功能在KubeOperator v3.9.0已经支持。
