### ISSUE TITLE
缺陷：vsphere中自动部署机器选择非自定义的模版无法实现ovf部署提示部署失败vcenter6.7 vcenter7.0

### ISSUE THREAD

**Issue by liuchangfitcloud** [KubeOperator/KubeOperator#406]
![image](https://user-images.githubusercontent.com/44662176/133180222-ebc16369-39c4-47f2-ab5b-6d9a05a67ab4.png)

**Comment by wanghe-fit2cloud** [comment]
收到，我们尽快验证并在下个版本中修复。

**Comment by wanghe-fit2cloud** [comment]
v3.11.0 版本已解决
