### ISSUE TITLE
[Bug]使用KubeOperator V3.10.1在通过部署计划openstack部署k8s V1.20.4报错

### ISSUE THREAD

**Issue by kinglong08** [KubeOperator/KubeOperator#413]
**KubeOperator 版本**
v3.10.1

**Kubernetes 版本**
v1.20.x

**Bug 描述**
使用KubeOperator V3.10.1在通过部署计划openstack部署k8s V1.20.x必现的一个报错信息，到主机管理页面中发现新创建的主机内存、cpu等信息均未获取到，将新创建的主机选中后同步一次，然后执行集群搭建则成功。

**Bug 重现步骤(有截图更好)**
1.按照官网文档配置好部署计划所有步骤；
2.到集群管理页面进行创建集群，使用刚创建的部署计划；
3.集群搭建的第二步必报错，报错信息如图；
![4bebf64602edd5d5c22a8a3983feb4b](https://user-images.githubusercontent.com/31060081/134805413-04310960-3105-4bb4-8ef5-3ef5e7a9624a.png)
4.到主机管理页面发现刚创建的主机内存和CPU未获取到，选中这些主机后同步一下，回到搭建步骤中重试则集群搭建成功；

**Comment by kinglong08** [comment]
部署计划中使用的云提供商是OpenStack

**Comment by maninhill** [comment]
3.11 版本已经修复。
