### ISSUE TITLE
[Bug]部署计划通过vsphere部署报错

### ISSUE THREAD

**Issue by liuchangfitcloud** [KubeOperator/KubeOperator#416]
**KubeOperator 版本**

3.11.1
**Kubernetes 版本**
v1.20.4-ko1 

**Bug 描述**

vsphere自动模式下报错
**Bug 重现步骤(有截图更好)**
1.设置vsphere区域，可用区，部署计划
2.新建集群，报错
3.
![image](https://user-images.githubusercontent.com/44662176/139042463-1600438a-7430-4ad6-90c2-dcaed586497a.png)

**Comment by wanghe-fit2cloud** [comment]
> 这个错误信息可否提升下可读性？

后续版本会优化集群初始化过程中抛出的错误信息。

**Comment by wanghe-fit2cloud** [comment]
新版本已经针对错误信息进行了格式化
