### ISSUE TITLE
dnf install -y python2-dnf

### ISSUE THREAD

**Issue by myvker** [KubeOperator/KubeOperator#419]
dnf install -y python2-dnf

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
添加的目标主机内存和CPU分别为多大？

**Comment by myvker** [comment]
4C4G

**Comment by wanghe-fit2cloud** [comment]
执行以下命令，截图看一下结果:
dmidecode -t 17 | grep "Size.*MB" | awk '{s+=$2} END {print s}'

**Comment by myvker** [comment]
把内存调大了就可以了

**Comment by myvker** [comment]
控制台如何查看执行的运行日志呢？还有就是最低配置能再低点吗？演示就可以！

**Comment by myvker** [comment]
{"hwb-master-1":"{"_ansible_no_log":false,"action":"package","changed":false,"cmd":"dnf install -y python2-dnf","failed":true,"invocation":{"module_args":{"allow_downgrade":false,"autoremove":false,"bugfix":false,"conf_file":null,"disable_excludes":null,"disable_gpg_check":false,"disable_plugin":[],"disablerepo":[],"download_dir":null,"download_only":false,"enable_plugin":[],"enablerepo":[],"exclude":[],"install_repoquery":true,"install_weak_deps":true,"installroot":"/","list":null,"lock_timeout":30,"name":["chrony"],"releasever":null,"security":false,"skip_broken":false,"state":"present","update_cache":false,"update_only":false,"validate_certs":true}},"msg":"Could not import the dnf python module using /usr/bin/python (2.7.18 (default, Jun 23 2021, 16:28:12) [GCC 7.3.0]). Please install `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter.","rc":1,"results":[],"stderr":"Error: Unable to find a match: python2-dnf ","stderr_lines":["Error: Unable to find a match: python2-dnf"],"stdout":"Last metadata expiration check: 0:51:20 ago on Tue 02 Nov 2021 02:47:39 PM UTC. No match for argument: python2-dnf ","stdout_lines":["Last metadata expiration check: 0:51:20 ago on Tue 02 Nov 2021 02:47:39 PM UTC.","No match for argument: python2-dnf"]}","hwb-worker-1":"{"_ansible_no_log":false,"action":"package","changed":false,"cmd":"dnf install -y python2-dnf","failed":true,"invocation":{"module_args":{"allow_downgrade":false,"autoremove":false,"bugfix":false,"conf_file":null,"disable_excludes":null,"disable_gpg_check":false,"disable_plugin":[],"disablerepo":[],"download_dir":null,"download_only":false,"enable_plugin":[],"enablerepo":[],"exclude":[],"install_repoquery":true,"install_weak_deps":true,"installroot":"/","list":null,"lock_timeout":30,"name":["chrony"],"releasever":null,"security":false,"skip_broken":false,"state":"present","update_cache":false,"update_only":false,"validate_certs":true}},"msg":"Could not import the dnf python module using /usr/bin/python (2.7.18 (default, Jun 23 2021, 16:28:12) [GCC 7.3.0]). Please install `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter.","rc":1,"results":[],"stderr":"Error: Unable to find a match: python2-dnf ","stderr_lines":["Error: Unable to find a match: python2-dnf"],"stdout":"Last metadata expiration check: 0:06:55 ago on Tue 02 Nov 2021 03:32:05 PM UTC. No match for argument: python2-dnf ","stdout_lines":["Last metadata expiration check: 0:06:55 ago on Tue 02 Nov 2021 03:32:05 PM UTC.","No match for argument: python2-dnf"]}","hwb-worker-2":"{"_ansible_no_log":false,"action":"package","changed":false,"cmd":"dnf install -y python2-dnf","failed":true,"invocation":{"module_args":{"allow_downgrade":false,"autoremove":false,"bugfix":false,"conf_file":null,"disable_excludes":null,"disable_gpg_check":false,"disable_plugin":[],"disablerepo":[],"download_dir":null,"download_only":false,"enable_plugin":[],"enablerepo":[],"exclude":[],"install_repoquery":true,"install_weak_deps":true,"installroot":"/","list":null,"lock_timeout":30,"name":["chrony"],"releasever":null,"security":false,"skip_broken":false,"state":"present","update_cache":false,"update_only":false,"validate_certs":true}},"msg":"Could not import the dnf python module using /usr/bin/python (2.7.18 (default, Jun 23 2021, 16:28:12) [GCC 7.3.0]). Please install `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter.","rc":1,"results":[],"stderr":"Error: Unable to find a match: python2-dnf ","stderr_lines":["Error: Unable to find a match: python2-dnf"],"stdout":"Last metadata expiration check: 0:06:44 ago on Tue 02 Nov 2021 03:32:15 PM UTC. No match for argument: python2-dnf ","stdout_lines":["Last metadata expiration check: 0:06:44 ago on Tue 02 Nov 2021 03:32:15 PM UTC.","No match for argument: python2-dnf"]}","hwb-worker-3":"{"_ansible_no_log":false,"action":"package","changed":false,"cmd":"dnf install -y python2-dnf","failed":true,"invocation":{"module_args":{"allow_downgrade":false,"autoremove":false,"bugfix":false,"conf_file":null,"disable_excludes":null,"disable_gpg_check":false,"disable_plugin":[],"disablerepo":[],"download_dir":null,"download_only":false,"enable_plugin":[],"enablerepo":[],"exclude":[],"install_repoquery":true,"install_weak_deps":true,"installroot":"/","list":null,"lock_timeout":30,"name":["chrony"],"releasever":null,"security":false,"skip_broken":false,"state":"present","update_cache":false,"update_only":false,"validate_certs":true}},"msg":"Could not import the dnf python module using /usr/bin/python (2.7.18 (default, Jun 23 2021, 16:28:12) [GCC 7.3.0]). Please install `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter.","rc":1,"results":[],"stderr":"Error: Unable to find a match: python2-dnf ","stderr_lines":["Error: Unable to find a match: python2-dnf"],"stdout":"Last metadata expiration check: 0:06:54 ago on Tue 02 Nov 2021 03:32:06 PM UTC. No match for argument: python2-dnf ","stdout_lines":["Last metadata expiration check: 0:06:54 ago on Tue 02 Nov 2021 03:32:06 PM UTC.","No match for argument: python2-dnf"]}"}

**Comment by wanghe-fit2cloud** [comment]
https://github.com/KubeOperator/KubeOperator/issues/396
