### ISSUE TITLE
How to push a mirror to registry after deployment

### ISSUE THREAD

**Issue by tzghost** [KubeOperator/KubeOperator#42]
How to push a mirror to registry after deployment.    what is the registry address and port?

**Comment by wanghe-fit2cloud** [comment]
The registry address can be found by querying "insecure-registries" in /etc/docker/daemon.json.
The domain name of registry with the cluster suffix is the registry address.

<img width="676" alt="WX20190816-101634@2x" src="https://user-images.githubusercontent.com/46734380/63138957-fa203280-c00e-11e9-94e6-9f7f39628985.png">

**Comment by tzghost** [comment]
How to solve the following problems?

[root@daemon-1 data]# docker push registry.apps.mycluster.k8s.cluster.test.cn/nginx:1.0
The push refers to a repository [registry.apps.mycluster.k8s.cluster.test.cn/nginx]
Get https://registry.apps.mycluster.k8s.cluster.test.cn/v1/_ping: x509: certificate is valid for kubeops.com, not registry.apps.mycluster.k8s.cluster.test.cn

**Comment by wanghe-fit2cloud** [comment]
Please provide the log of the registry container

**Comment by tzghost** [comment]
Only logs that access the console interface

![企业微信截图_15659373345192](https://user-images.githubusercontent.com/17000535/63148318-66149200-c033-11e9-80e0-c14068962002.png)

**Comment by wanghe-fit2cloud** [comment]
Is the docker push operation on any worker node?

**Comment by tzghost** [comment]
Yes on the works node, no on the non-works node

**Comment by wanghe-fit2cloud** [comment]
Currently ingress is using a self-signed certificate, so you need to add the registry address to /etc/docker/daemone.json, then restart the docker and push

1. add registry address to insecure-registries in /etc/docker/daemon.json file
2. in the /etc/hosts file, point the registry address to any worker node
3. restart docker
4. docker login
5. docker tag
4. docker push

**Comment by gst6062825** [comment]
> Currently ingress is using a self-signed certificate, so you need to add the registry address to /etc/docker/daemone.json, then restart the docker and push
> 
> 1. add registry address to insecure-registries in /etc/docker/daemon.json file
> 2. in the /etc/hosts file, point the registry address to any worker node
> 3. restart docker
> 4. docker login
> 5. docker tag
> 6. docker push

$ docker login --username=admin -p=admin123 registry-ui.apps.carnet.testlp.com
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded

$ docker push registry-ui.apps.carnet.testlp.com/charger_docker/uuevc-main:uuevc-gate_20191229_
error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>You don't have permission to access /v2/charger_docker/uuevc-main/blobs/uploads/\non this server.<br />\n</p>\n<hr>\n<address>Apache/2.4.10 (Debian) Server at registry-ui.apps.carnet.leapmotor.com Port 80</address>\n</body></html>\n"
