### ISSUE TITLE
k8s 存储加入nfs 总是未就绪

### ISSUE THREAD

**Issue by albert2020** [KubeOperator/KubeOperator#421]
k8s 存储加入nfs 总是未就绪，请问需要如何处理
执行步骤
1.先准备了一台虚拟机安装了nfs V4 ，并且启动了nfs
2.再kubeoperator中的集群里面的存储下面的存储提供商加入了nfs
3.确定执行

出现未就绪不清楚要怎么排查错误了
需要的帮助：
希望能够创建好nfs存储，卡住工作流了

**Comment by wanghe-fit2cloud** [comment]
查看nfs pod（kube-system命名空间）日志，参考错误信息

**Comment by albert2020** [comment]
@wanghe-fit2cloud 
查看了错误是这个？网络不好？
Error from server (BadRequest): container "nfs-client-provisioner" in pod "nfs01-6769c88846-mr685" is waiting to start: ContainerCreating
