### ISSUE TITLE
[Bug] 下载的 kubeconfig 文件 apiserver地址为 127.0.0.1

### ISSUE THREAD

**Issue by plateauandsp** [KubeOperator/KubeOperator#422]
**Bug 描述**

KO里面下载的kubeconfig文件无法使用，里面的地址都是127.0.0.1
![image](https://user-images.githubusercontent.com/30932762/141939965-1f8eba0e-398e-4c4f-aee1-35a8316160e3.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们会在接下来版本中优化该问题

**Comment by wanghe-fit2cloud** [comment]
v3.12.0版本已修复
