### ISSUE TITLE
[Feature] kubeoperator 可以支持单机部署么？

### ISSUE THREAD

**Issue by tanguofu** [KubeOperator/KubeOperator#423]
**请描述您的需求或者改进建议.**
只有一台机器  怎么部署呢？？

**Comment by wanghe-fit2cloud** [comment]
官方文档：
https://kubeoperator.io/docs/installation/install/

我们要求提供一台服务器来部署KubeOperator，至少两台服务器（1master+1worker）来作为Kubernetes集群节点。

**Comment by tanguofu** [comment]
那么 请问这里有优化计划不？

**Comment by wanghe-fit2cloud** [comment]
一台服务器来部署KubeOperator + Kubernetes集群这种方案并不是最佳实践，也不适合企业级用户。在我们的后期版本中应该不会支持这种方案。

如果只有一台服务器，你可以考虑使用MiniKube来创建Kubernetes集群。
