### ISSUE TITLE
[Bug]--集群重启之后，主机的连接状态显示失败。

### ISSUE THREAD

**Issue by luolei2939** [KubeOperator/KubeOperator#424]
**KubeOperator 版本**
3.11.2

**Kubernetes 版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/72790301/142179735-879a7cfe-a7c7-42d1-ace1-4a7fb9467fd0.png)

**Comment by wanghe-fit2cloud** [comment]
建议重启KubeOperator后再重新添加主机，如果还存在问题，可以加入技术交流群来共同讨论
