### ISSUE TITLE
[Bug]KO安装完k8s，kubectl get cs 显示controller-manager和scheduler为不健康状态

### ISSUE THREAD

**Issue by mfanoffice** [KubeOperator/KubeOperator#426]
**KubeOperator 版本**
所有版本

**Kubernetes 版本**
v1.19

**Bug 描述**
使用KO安装完k8s后，查询k8s 的 组件状态 kubectl get cs 显示controller-manager和scheduler为不健康状态，需要手动修改参数才能恢复，可否在KO安装完后自动修改？
![image](https://user-images.githubusercontent.com/48307752/143664164-b73aebbb-0ce9-4da7-bcb6-8a57774abb1a.png)

**Bug 重现步骤(有截图更好)**
1. kubectl get cs 会发现controller-manager和scheduler为不健康状态
2. 修改vi /etc/kubernetes/manifests/kube-controller-manager.yaml 和 vi /etc/kubernetes/manifests/kube-scheduler.yaml
3. 将- --port=0 注释掉过一会两组件就健康了。

**Comment by wanghe-fit2cloud** [comment]
Unhealthy状态是因为controller-manager和scheduler 未打开非安全端口造成的
kubectl get cs 这个接口在未来将会被弃用
你可以采用提到的方案来修复
