### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cuiweifu** [KubeOperator/KubeOperator#429]
**KubeOperator 版本**

commit 8555da5bfc864868127112056c02d392808790e5 (HEAD -> master, origin/master, origin/HEAD)
Author: Aaron3S <chenyang@fit2cloud.com>
Date:   Tue Dec 7 14:41:21 2021 +0800

**Bug 描述**

1. KubeOperator/pkg/cron/job/cluster_health.go 文件编译不通过， logger.Log.Error 应该为 logger.Log.Errorf 才可以。 

2. 代码中有多处做加密解密操作用到了配置文件， 例如KubeOperator/pkg/encrypt/encrypt.go文件中有的encrypt.multilevel配置项，但在app.yaml文件中未描述这个相关的内容。 是官方故意将示例移除了吗？

**Comment by Aaron3S** [comment]
感谢您提的问题。

**Comment by cuiweifu** [comment]
多谢答复

我们代码中的注释是比较少的。 具体实现逻辑只能啃代码才可以。 

通过install repo安装测试了一下， 感觉当前工程跟其他的工程是有服务层面的依赖关系的， 但这层关系不能直接的从文档中看出来。 

现在的文档，更面相产品的说明。 对于社区开发者来说不太友好， 估计这也是为何贡献者不是特别多的原因。 相比较kubeasz少了很多人的参与。 

另外从git log中看到貌似我们之前也有使用 kubeasz 但现在更换掉了， 是出于什么考虑要更换呢？
