### ISSUE TITLE
[Bug]kube-flannel-ds 资源配置过小

### ISSUE THREAD

**Issue by TophillZK** [KubeOperator/KubeOperator#430]
**KubeOperator 版本**
v3.11.2

**Kubernetes 版本**
v1.20.10

**Bug 描述**
1、kube-flannel-ds由于资源配置过小，导致pod频繁重启
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 50Mi
              cpu: 100m
2、修改成如下就没问题了
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 200Mi
              cpu: 200m
3、手工修改之后，如果在集群冲新增设备，则资源大小又会恢复，希望在下个版本中调大资源配置

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/35677454/145390022-ca7c926d-6e24-4159-ad67-a7e7a5cb5f30.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈

**Comment by wanghe-fit2cloud** [comment]
新版本已解决。
