### ISSUE TITLE
[Feature]节点名称能够按照在KubeOperator控制台中录入的主机名称命名

### ISSUE THREAD

**Issue by TophillZK** [KubeOperator/KubeOperator#431]
**请描述您的需求或者改进建议.**
目前KubeOperator生成节点名称时，是按照：集群名称-角色-添加序号   的模式进行生成的，导致后期在使用时，查找某个Pod所在主机然后登录上去看一些问题时，需要先找到Pod，看其节点名称，然后再通过kubectl get node 找到节点IP，然后才能登录到这个主机，使用起来比较麻烦。

希望在下个版本中，能够根据我录入到KubeOperator中的主机名称字段来生成节点名称并做对应的hostnamectl
当然可能会有些同学还是习惯使用原有的模式，那么能够有个选项就更方便了。

期待这个改进，谢谢~~

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑该需求

**Comment by wanghe-fit2cloud** [comment]
新版本已经支持 HostName 和 IP 两种命名规则。
