### ISSUE TITLE
[Bug]新版本v3.12.0安装报错

### ISSUE THREAD

**Issue by TophillZK** [KubeOperator/KubeOperator#432]
**KubeOperator 版本**
v3.12.0

**Kubernetes 版本**
v1.20.12

**Bug 描述**
/opt/kubeoperator/data/kobe/project/ko/roles/prepare/docker/templates/daemon.json.j2
配置项 "exec-opts": ["native.cgroupdriver=cgroupfs"]
在 CentOS Linux release 7.6.1810 ，3.10.0-957.el7.x86_64 下面报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/35677454/145751754-e82a51aa-937d-4bc9-a965-3be7c8363fa7.png)

**Comment by wanghe-fit2cloud** [comment]
提供一下详细的错误信息截图 error
warning可以忽略

**Comment by TophillZK** [comment]
![image](https://user-images.githubusercontent.com/35677454/145755843-f4ed5f25-cbdb-4e22-8333-3c980d7b72d0.png)
控制台上详细的截图，请参考

**Comment by TophillZK** [comment]
![image](https://user-images.githubusercontent.com/35677454/145756377-eab9fad8-df35-40ef-a620-f5e565964e09.png)
![image](https://user-images.githubusercontent.com/35677454/145756469-9694da14-8e48-4ecd-a041-297abf46e30c.png)
控制台报错信息见上图

**Comment by wanghe-fit2cloud** [comment]
nexus 镜像仓库手动开启认证了吧

**Comment by TophillZK** [comment]
1、nexus我修改了admin密码，在nexus和ko都修改了，后来发现报错，我都恢复成默认密码admin123，仍然不行
2、nexus的anonymous用户是允许访问的
3、在nexus上我仅仅是添加了一个新用户

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/145761667-c099f8a4-cfb8-432f-881a-31b9fb274088.png)
错误原因是集群节点pull nexus镜像仓库中镜像需要认证导致的
默认设置是：Allow anonymous users to access the server，pull镜像不需要认证

**Comment by TophillZK** [comment]
![image](https://user-images.githubusercontent.com/35677454/145763179-fea2e3ea-3c4a-4371-8463-0de262180281.png)
这个配置确认没有修改的

**Comment by wanghe-fit2cloud** [comment]
不太清楚你那边具体做了什么操作导致的pull 镜像需要认证了

**Comment by TophillZK** [comment]
那我先不着急，等有空把几台设备重做了之后再试试了，谢谢大佬的及时回复~~

**Comment by wanghe-fit2cloud** [comment]
你可以用离线包中的nexus-data.tar.gz文件覆盖安装目录中持久化文件(./kubeoperator/data/nexus-data)
然后重启服务
