### ISSUE TITLE
[Bug]镜像仓库填写阿里云私有仓库授权失败，账号密码正常

### ISSUE THREAD

**Issue by cowardmrx** [KubeOperator/KubeOperator#433]
**KubeOperator 版本**

**Kubernetes 版本**
v1.21.7+k3s1

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/74823020/145767531-604e3737-0338-4754-95b5-83c396ac3ed2.png)
2.
![image](https://user-images.githubusercontent.com/74823020/145767267-f6da1e9d-382d-4d07-a819-51a948f659e0.png)

**Comment by wanghe-fit2cloud** [comment]
当前版本支持的镜像仓库类型有：Harbor、Nexus和Docker Registry三种，还不支持阿里镜像仓库

1、Docker Registry仓库是：https://github.com/distribution/distribution，不可以输入阿里镜像仓库地址
2、Docker Registry仓库可以在KubeOperator的工具列表中直接启用
![image](https://user-images.githubusercontent.com/46734380/145768206-dee57aba-42f9-49db-a4bf-bc12faaa3304.png)
3、KubeOperator应用商店中也支持添加Harbor

**Comment by cowardmrx** [comment]
> 

好的，感谢回复
