### ISSUE TITLE
[Bug] centos7.9系统识别为Ubuntu

### ISSUE THREAD

**Issue by seaurching** [KubeOperator/KubeOperator#435]
**KubeOperator 版本**
v3.12.0

**Kubernetes 版本**
v1.20.12-ko1

**Bug 描述**
初始化系统的时候提示系统为Ubuntu,找不到apt-get命令.明明是RedHat家族的系统,却说是Debian家族的

**Bug 重现步骤(有截图更好)**

**Comment by wanghe-fit2cloud** [comment]
提供一下主机列表截图

**Comment by seaurching** [comment]
> 提供一下主机列表截图

暂时无法提供截图,centos7.9系统识别为ubuntu.
另外在系统架构x86_64这里改了nexus的密码,在部署Prometheus的时候提示密码错误,修改密码不会同步到数据库中.
还有在1.23.1版本的集群中,clusterroleboing的apiversion为v1不是v1beta,请检查其他版本

**Comment by wanghe-fit2cloud** [comment]
1、删除缓存后重试，看问题是否还会复现：rm -rf /opt/kubeoperator/data/kobe/cache/*
2、nexus仓库和kubeoperator系统设置-仓库这两个地方都需要修改密码，并没有同步
3、kubeopertor当前支持的k8s版本为1.18和1.20两个大版本

**Comment by seaurching** [comment]
备份集群,一直显示运行中,点击查看日志,无法连接到logger
