### ISSUE TITLE
使用harbor 

### ISSUE THREAD

**Issue by BruceChinese** [KubeOperator/KubeOperator#436]
**KubeOperator 版本**
3.12.0

**Kubernetes 版本**
1.18

**Bug 描述**
如果不想使用 nexus  想使用自己的私有harbor 这个支持吗 如果支持 如何配置

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wanghe-fit2cloud** [comment]
不支持。
nexus除了作为镜像仓库外，还是raw、helm、rpm和apt仓库

**Comment by BruceChinese** [comment]
毕竟这个目前用的不是很多，要批量修改线上的配置，成本也是很高的
