### ISSUE TITLE
[Bug]集群部署失败，ansible get result failed

### ISSUE THREAD

**Issue by qd19zzx** [KubeOperator/KubeOperator#437]
**KubeOperator 版本**
3.10.1

**Kubernetes 版本**
1.20.4

**Bug 描述**
kubeopertor正常运行7天左右后。部署集群，到“准备系统环境”报错，错误信息如下图所示。同时检查主机状态的cronjob也报相同的错误。
![c4db61f9e1ee7b8a718a927dd6bb6b6](https://user-images.githubusercontent.com/35022748/147031176-61041b7e-eef4-4b1e-b7aa-b46c710fdb59.png)

docker exec 进入kobe容器检查，发现报错的目录下的确没有result.json文件。查询kobe日志，并没有找到报错信息。

koctl restart重启服务后，服务恢复正常。

**Bug 重现步骤(有截图更好)**
没有找到具体的重现步骤。此环境用作部署测试，运行7天时间内，总共部署删除了40套左右的集群。

**Comment by wanghe-fit2cloud** [comment]
好的，问题已收到，感谢反馈。
