### ISSUE TITLE
[Bug]集群备份显示运行中

### ISSUE THREAD

**Issue by seaurching** [KubeOperator/KubeOperator#438]
**KubeOperator 版本**
v3.12.0

**Kubernetes 版本**
v1.20.0

**Bug 描述**
设置了自动备份,备份类型是sftp,一共有6个备份进程,一直显示运行中,无法结束,重启了这个平台后还是显示一直运行中,查看控制台日志,什么也看不到,然后就弹出未认证让重新登录.在集群看了一下后台的jobs,有一个kube-bench,他的images 镜像是一个私有镜像registry.kubeoperator.io,这个地址并不能解析

**Comment by wanghe-fit2cloud** [comment]
任务状态一直显示为运行中，是因为ansible任务都还没有触发执行。你可以先看一下kobe容器中进程和kobe容器日志。
koctl restart 重启服务后，还是显示运行中是正常的（这里我们没有重置机制），你可以再次执行手动备份试一下。
备份任务和集群的jobs是没有关联的。registry.kubeoperator.io 这个域名是写入集群节点的hosts文件的，解析到KubeOperator的部署机。

**Comment by seaurching** [comment]
> 任务状态一直显示为运行中，是因为ansible任务都还没有触发执行。你可以先看一下kobe容器中进程和kobe容器日志。 koctl restart 重启服务后，还是显示运行中是正常的（这里我们没有重置机制），你可以再次执行手动备份试一下。 备份任务和集群的jobs是没有关联的。registry.kubeoperator.io 这个域名是写入集群节点的hosts文件的，解析到KubeOperator的部署机。

还是加一个重置机制就好了.

**Comment by wanghe-fit2cloud** [comment]
好的，后续版本增加。
