### ISSUE TITLE
aws云主机布署operator,弹性IP无法注册

### ISSUE THREAD

**Issue by yangbo0734** [KubeOperator/KubeOperator#439]
**请描述您的需求或者改进建议.**
aws云主机布署operator,弹性IP无法注册，导致后台启用kueapp应用商店无法启用，以及新安装的k8s集群，metric-server无法正常获取pod监控数据．运行是正常的．

**Comment by wanghe-fit2cloud** [comment]
添加云主机时，要使用内网IP。

**Comment by wanghe-fit2cloud** [comment]
针对公有云主机部署的集群
应用商店等部署成功后弹性 IP 无法访问的问题，我们计划在后续版本中会给出解决方案。

**Comment by wanghe-fit2cloud** [comment]
该需求已经纳入后续开发计划
