### ISSUE TITLE
是否可以增加 Weave Scope 的认证及访问控制机制？

### ISSUE THREAD

**Issue by KubeOperator** [KubeOperator/KubeOperator#44]
具体请看：

https://github.com/weaveworks/scope/issues/3453
https://github.com/weaveworks/scope/blob/master/site/faq.md#rbac-and-weave-scope-oss

**Comment by wanghe-fit2cloud** [comment]
Weave Scope 的认证及访问控制机制已在KubeOperator2.0版本中增加
