### ISSUE TITLE
无法配置自建harbor仓库

### ISSUE THREAD

**Issue by rait-winter** [KubeOperator/KubeOperator#441]
harbor仓库版本v1.10.3，kubeoperator版本3.12，报错 404 NOT FOUND

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
问题是因为 harbor v1 和 v2 两个版本 API 不兼容导致的。
我们的开发测试环境是 harbor v2，使用是没有问题的，你可以将 harbor 仓库版本升级到 v2。

在下个版本中，我们会兼容 v2 和 v2两个版本。
