### ISSUE TITLE
[Question]使用自建harbor仓库问题

### ISSUE THREAD

**Issue by rait-winter** [KubeOperator/KubeOperator#443]
**请描述您的问题.**
1.使用自建harbor仓库，如果在系统配置处设置自建仓库，无法获取镜像与安装包安装集群
2.在集群创建后，添加harbor仓库，在每个worker节点上进行docker pull时，无法很好拉取自建harbor仓库中镜像，需要手动添加“insecure-registries”，是否有办法在每个worker节点添加时，增加自建harbor仓库的insecure-registries

**Comment by wanghe-fit2cloud** [comment]
1、KO系统设置-仓库：不可以设置自建仓库
2、设置 insecure-registries 是因为你没有为 harbor 开启 https，所以需要在集群所有节点手动添加。至于是否有办法自动添加，在后续版本规划中我们考虑一下吧。
