### ISSUE TITLE
[Feature]支持华为sfs

### ISSUE THREAD

**Issue by jstbw** [KubeOperator/KubeOperator#445]
**请描述您的需求或者改进建议.**
麻烦适配一下华为的sfs
https://github.com/huaweicloud/external-sfs/tree/master/examples/sfs-provisioner/kubernetes

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
后面版本支持吧。

sfs 部署文档：https://github.com/huaweicloud/external-sfs/tree/master/deploy/sfs-provisioner/kubernetes
