### ISSUE TITLE
Pod列表中的终端目前没有限制

### ISSUE THREAD

**Issue by chrinly** [KubeOperator/KubeOperator#446]
只读权限的用户可以进入终端进行kill等危险命令操作，希望后续版本可以加一下

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本中针对 Pod 列表的终端权限进行限制，和分配给用户的权限保持一致。

**Comment by wanghe-fit2cloud** [comment]
可以将KubePi版本 升级到 v1.4.1，并赋予用户view-workload的权限，此时用户进入dashboard pod列表后，不再具有terminal的权限

**Comment by wanghe-fit2cloud** [comment]
KubePi 最新版本 v1.4.1 只读用户也无 Terminal 权限。
