### ISSUE TITLE
[Bug]使用备份恢复集群后，集群崩溃

### ISSUE THREAD

**Issue by seaurching** [KubeOperator/KubeOperator#447]
**KubeOperator 版本**
v3.12.0

**Kubernetes 版本**
v1.20.12
**Bug 描述**
集群状态为notready
重启所有的docker后显示ready，无法正常使用,检查etcd报错

```
etcdctl --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key  member list
{"level":"warn","ts":"2022-02-11T18:02:11.132+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-2bd36185-ae29-45e7-9b1f-963ea0c1554e/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: authentication handshake failed: EOF\""}
```
严重影响使用，我再也不用你们的了

**Comment by seaurching** [comment]
> 问题已收到，正在尝试本地复现。

备份后的文件，怎么查看原始的内容

**Comment by wanghe-fit2cloud** [comment]
查询 etcd 集群所有成员的命令：
```shell
ETCDCTL_API=3 etcdctl --endpoints 172.16.10.230:2379 \
  --cert=/etc/kubernetes/pki/etcd/server.crt \
  --key=/etc/kubernetes/pki/etcd/server.key \
  --cacert=/etc/kubernetes/pki/etcd/ca.crt \
  member list
```

**Comment by seaurching** [comment]
> 查询 etcd 集群所有成员的命令：
> 
> ```shell
> ETCDCTL_API=3 etcdctl --endpoints 172.16.10.230:2379 \
>   --cert=/etc/kubernetes/pki/etcd/server.crt \
>   --key=/etc/kubernetes/pki/etcd/server.key \
>   --cacert=/etc/kubernetes/pki/etcd/ca.crt \
>   member list
> ```

可以查看到集群状态是正常的healthy。另外master节点使用docker ps -qa|xargs docker rm 变成正常状态后，删除pod的时候，提示too old resource version，

**Comment by wanghe-fit2cloud** [comment]
> 



> > 查询 etcd 集群所有成员的命令：
> > ```shell
> > ETCDCTL_API=3 etcdctl --endpoints 172.16.10.230:2379 \
> >   --cert=/etc/kubernetes/pki/etcd/server.crt \
> >   --key=/etc/kubernetes/pki/etcd/server.key \
> >   --cacert=/etc/kubernetes/pki/etcd/ca.crt \
> >   member list
> > ```
> 
> 可以查看到集群状态是正常的healthy。

你发的 etcd 报错信息，是因为你查询的命令不对。

**Comment by seaurching** [comment]
> > 
> 
> > > 查询 etcd 集群所有成员的命令：
> > > ```shell
> > > ETCDCTL_API=3 etcdctl --endpoints 172.16.10.230:2379 \
> > >   --cert=/etc/kubernetes/pki/etcd/server.crt \
> > >   --key=/etc/kubernetes/pki/etcd/server.key \
> > >   --cacert=/etc/kubernetes/pki/etcd/ca.crt \
> > >   member list
> > > ```
> > 
> > 
> > 可以查看到集群状态是正常的healthy。
> 
> 你发的 etcd 报错信息，是因为你查询的命令不对。

查询命令对不对，已经不重要了。重要的是，集群起来后删除pod，提示资源版本太旧，无法删除任何pod

**Comment by wanghe-fit2cloud** [comment]
> > > 
> > 
> > 
> > > > 查询 etcd 集群所有成员的命令：
> > > > ```shell
> > > > ETCDCTL_API=3 etcdctl --endpoints 172.16.10.230:2379 \
> > > >   --cert=/etc/kubernetes/pki/etcd/server.crt \
> > > >   --key=/etc/kubernetes/pki/etcd/server.key \
> > > >   --cacert=/etc/kubernetes/pki/etcd/ca.crt \
> > > >   member list
> > > > ```
> > > 
> > > 
> > > 可以查看到集群状态是正常的healthy。
> > 
> > 
> > 你发的 etcd 报错信息，是因为你查询的命令不对。
> 
> 查询命令对不对，已经不重要了。重要的是，集群起来后删除pod，提示资源版本太旧，无法删除任何pod

兄弟，我们的产品本身就是开源的，你在没有搞清楚具体原因的情况下就直接给出这么一个武断的结论是不是有点不太合适呀？

真有问题咱们可以探讨，但是请不要着急的随意下结论。

**Comment by seaurching** [comment]
这个解决了吗@wanghe-fit2cloud
