### ISSUE TITLE
Node节点主机名 修改

### ISSUE THREAD

**Issue by xiuyang123** [KubeOperator/KubeOperator#450]
**请描述您的问题.**
Node节点主机名 修改---解决办法

**Comment by xiuyang123** [comment]
kubeoperator--扩容集群节点完成后--如何修改node节点主机名

**Comment by wanghe-fit2cloud** [comment]
创建集群时，节点命名规则支持 hostname 和 ip 两种模式。
如果采用的是 hostname，我们会按照自己的规则来给 node 节点命名。
可以手动修改，但是还需要修改所有节点的 hosts 记录。

**Comment by wanghe-fit2cloud** [comment]
后期版本可以这样：
节点命名规则可以直接采用录入主机时的主机名称来给 node 节点命令，这样就应该能解决你的问题。

**Comment by wanghe-fit2cloud** [comment]
v3.14.0 版本已经支持根据主机名称来给集群 node 节点命名。
