### ISSUE TITLE
[Question]KO安裝external-ceph，報錯yum lockfile is held by another process

### ISSUE THREAD

**Issue by liujunfei980** [KubeOperator/KubeOperator#451]
使用KO V3.12.0版本對接external-ceph時，初始化過程中報以下錯誤：

failed: [zz-k8s-cluster01-worker-2 -> None] (item=zz-k8s-cluster01-worker-4) => {"ansible_loop_var": "item", "changed": false, "item": "zz-k8s-cluster01-worker-4", "msg": "yum lockfile is held by another process"}

請問是否有KO對接外部ceph和cinder的操作文檔說明？具體安裝過程或者視頻教程。

**Comment by wanghe-fit2cloud** [comment]
> 使用KO V3.12.0版本對接external-ceph時，初始化過程中報以下錯誤：
> 
> failed: [zz-k8s-cluster01-worker-2 -> None] (item=zz-k8s-cluster01-worker-4) => {"ansible_loop_var": "item", "changed": false, "item": "zz-k8s-cluster01-worker-4", "msg": "yum lockfile is held by another process"}
> 
> 請問是否有KO對接外部ceph和cinder的操作文檔說明？具體安裝過程或者視頻教程。

KO 启用外部 Ceph 持久化存储时，需要在所有集群节点安装 ceph-common 客户端。
```shell
yum install -y ceph-common
```
你现在的问题是 zz-k8s-cluster01-worker-4 节点上的 yum 被其他程序占用了。
