### ISSUE TITLE
[Feature]ko是否可以支持cephfs

### ISSUE THREAD

**Issue by liujunfei980** [KubeOperator/KubeOperator#452]
KO后续版本中是否可以支持外部cephfs，可从存储类下拉选项提供商中选择cephfs类。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前 KO 支持外部 ceph rbd 持久化存储，后续版本支持 cephfs。

**Comment by classcit** [comment]
也请支持下rook cephfs，同时现在rook的版本较低，烦请更新下rook的版本
