### ISSUE TITLE
[Bug]通过ko卸载集群重新安装，当重新安装的集群与之前卸载的集群重名时，kubepi集群连接会访问异常

### ISSUE THREAD

**Issue by chenxin2001** [KubeOperator/KubeOperator#455]
**KubeOperator 版本**
v3.13.0

**Kubernetes 版本**
v1.20.10-ko1

**Bug 描述**
通过ko卸载集群重新安装，当重新安装的集群与之前卸载的集群重名时，kubepi集群连接会访问异常。

**Bug 重现步骤(有截图更好)**
1.登入ko平台>集群，点击删除；
2.点击添加，重新安装集群，且集群名与之前卸载的集群重名时；
3.点击安装好的集群的dashboard，kubepi提示集群异常

![企业微信截图_42a886d5-831f-4942-a2bd-63810158b201](https://user-images.githubusercontent.com/34565342/160227014-047ef9f6-b596-4368-9451-982ca256d2f1.png)

![企业微信截图_ef1b4629-7a73-48a7-9866-e9c7586138cb](https://user-images.githubusercontent.com/34565342/160227010-43a72096-db26-41c6-9767-98baf56b2105.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本中修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v3.14.0 版本已修复。
