### ISSUE TITLE
[Question]Error for docker build --build-arg GOARCH=arm64 -t server-arm64:v1 . 

### ISSUE THREAD

**Issue by Jchicode** [KubeOperator/KubeOperator#456]
**请描述您的问题.**
<img width="653" alt="image" src="https://user-images.githubusercontent.com/12872991/160367157-8d0fc11b-176f-4b6e-968b-1353d1d9079e.png">

**Comment by wanghe-fit2cloud** [comment]
在开发环境没有复现该的问题。

![image](https://user-images.githubusercontent.com/46734380/160368807-b2d29abf-6506-48ac-80f0-ccdfeef68525.png)

**Comment by Jchicode** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/12872991/160369421-6f79652d-b841-4b9f-b770-4f0cd1a8531a.png">
Hello, can you compile with arm64?
GOARCH=arm64

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/160370107-c963c2cd-29c2-4f70-9ab6-ba0c12d2270d.png)

**Comment by Jchicode** [comment]
Thanks, do I need to install some dependencies? What is your environment?

**Comment by wanghe-fit2cloud** [comment]
整个 build 过程是在容器内进行的，也不需要在服务器上安装依赖包，默认的 build 基础镜像是 golang:1.16。

**Comment by Jchicode** [comment]
> 整个 build 过程是在容器内进行的，也不需要在服务器上安装依赖包，默认的 build 基础镜像是 golang:1.16。

Thanks, I am currently executing this process in amd64 environment, the command is ```docker build --build-arg GOARCH=arm64 -t server-arm64:v1 .```
There was an error when executing to make, but I see only GOARCH is configurable.
Will it have something to do with my current system environment?

**Comment by wanghe-fit2cloud** [comment]
make docker_server GOARCH=amd64

**Comment by Jchicode** [comment]
> make docker_server GOARCH=amd64

I eventually want to build an arm64 image.

**Comment by Jchicode** [comment]
Thanks, I'll try it
