### ISSUE TITLE
[Bug]创建可用区选择区域报错

### ISSUE THREAD

**Issue by wuhl92** [KubeOperator/KubeOperator#457]
**KubeOperator 版本**
3.14.0

**Kubernetes 版本**
不涉及

**Bug 描述**
创建可用区选择区域报错
vsphere版本6.5

**Bug 重现步骤(有截图更好)**
1.创建可用区
2.选择区域后报错
3.截图如下：
![image](https://user-images.githubusercontent.com/28152197/161680321-49caf412-6adf-46e6-9239-89a4cce7bd4a.png)
4.server日志如下：
server_1      | [HTTP Server] http: panic serving 172.21.0.10:46968: reflect.Set: value of type mo.VmwareDistributedVirtualSwitch is not assignable to type mo.Network
server_1      | goroutine 13016 [running]:
server_1      | net/http.(*conn).serve.func1(0xc0004303c0)
server_1      |         /usr/local/go/src/net/http/server.go:1805 +0x153
server_1      | panic(0x4080820, 0xc00056fd50)
server_1      |         /usr/local/go/src/runtime/panic.go:971 +0x499
server_1      | reflect.Value.assignTo(0x4424e20, 0xc000d76580, 0x99, 0x47dd965, 0xb, 0x45f09e0, 0x0, 0x0, 0x0, 0x0)
server_1      |         /usr/local/go/src/reflect/value.go:2451 +0x3f7
server_1      | reflect.Value.Set(0x45f09e0, 0xc000baec40, 0x199, 0x4424e20, 0xc000d76580, 0x99)
server_1      |         /usr/local/go/src/reflect/value.go:1564 +0xbd
server_1      | github.com/vmware/govmomi/vim25/mo.LoadObjectContent(0xc000c5b040, 0x1, 0x1, 0x42a4780, 0xc000baec40, 0x0, 0x0)
server_1      |         /go/pkg/mod/github.com/vmware/govmomi@v0.23.0/vim25/mo/retrieve.go:147 +0xa8a
server_1      | github.com/vmware/govmomi/property.(*Collector).Retrieve(0xc000dfcae0, 0x4df74d8, 0xc00013c038, 0xc000dfcac0, 0x1, 0x1, 0xc003132980, 0x2, 0x2, 0x42a4780, ...)
server_1      |         /go/pkg/mod/github.com/vmware/govmomi@v0.23.0/property/collector.go:182 +0x4a5
server_1      | github.com/vmware/govmomi/property.(*Collector).RetrieveOne(...)
server_1      |         /go/pkg/mod/github.com/vmware/govmomi@v0.23.0/property/collector.go:210
server_1      | github.com/KubeOperator/KubeOperator/pkg/cloud_provider/client.(*vSphereClient).getNetworkName(0xc0017a7480, 0xc000dc6f20, 0x1e, 0xc003039440, 0x6, 0xc001742ac0, 0x1d, 0x0, 0x0)
server_1      |         /build/ko/pkg/cloud_provider/client/vsphere.go:124 +0x1cd
server_1      | github.com/KubeOperator/KubeOperator/pkg/cloud_provider/client.(*vSphereClient).ListClusters(0xc0017a7480, 0x0, 0x0, 0x0, 0x0, 0x0)
server_1      |         /build/ko/pkg/cloud_provider/client/vsphere.go:98 +0x515
server_1      | github.com/KubeOperator/KubeOperator/pkg/service.zoneService.ListClusters(0x4e13418, 0x7b5ecd8, 0x4e0b810, 0x7b5ecd8, 0x4e2a220, 0xc00183cd20, 0x4e0b858, 0xc0018446c0, 0x41e5b20, 0xc000ce26f0, ...)
server_1      |         /build/ko/pkg/service/zone.go:347 +0x133
server_1      | github.com/KubeOperator/KubeOperator/pkg/controller.ZoneController.PostClusters(0x4e463d0, 0xc0030f61b0, 0x4e21210, 0xc001827fc0, 0x28, 0x28, 0x7ff7ac8f7108, 0x30)
server_1      |         /build/ko/pkg/controller/zone.go:222 +0xf0
server_1      | reflect.Value.call(0x45e5be0, 0xc0002f2920, 0x1e13, 0x47bff4c, 0x4, 0x7b5e6a0, 0x0, 0x0, 0xb, 0xc000dd91b8, ...)
server_1      |         /usr/local/go/src/reflect/value.go:476 +0x8e7
server_1      | reflect.Value.Call(0x45e5be0, 0xc0002f2920, 0x1e13, 0x7b5e6a0, 0x0, 0x0, 0x1e13, 0xc000dd9230, 0x15057f8)
server_1      |         /usr/local/go/src/reflect/value.go:337 +0xb9
server_1      | github.com/kataras/iris/v12/mvc.(*ControllerActivator).handlerOf.func2(0x4e463d0, 0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/mvc/controller.go:497 +0x3cb
server_1      | github.com/kataras/iris/v12/context.DefaultNext(0x4e463d0, 0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343 +0x10c
server_1      | github.com/kataras/iris/v12/context.(*context).Next(0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352 +0x3e
server_1      | github.com/KubeOperator/KubeOperator/pkg/middleware.ForceMiddleware(0x4e463d0, 0xc0030f61b0)
server_1      |         /build/ko/pkg/middleware/force.go:15 +0x142
server_1      | github.com/kataras/iris/v12/context.DefaultNext(0x4e463d0, 0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343 +0x10c
server_1      | github.com/kataras/iris/v12/context.(*context).Next(0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352 +0x3e
server_1      | github.com/KubeOperator/KubeOperator/pkg/middleware.PagerMiddleware(0x4e463d0, 0xc0030f61b0)
server_1      |         /build/ko/pkg/middleware/pager.go:15 +0x19b
server_1      | github.com/kataras/iris/v12/context.DefaultNext(0x4e463d0, 0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343 +0x10c
server_1      | github.com/kataras/iris/v12/context.(*context).Next(0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352 +0x3e
server_1      | github.com/KubeOperator/KubeOperator/pkg/middleware.RBACMiddleware.func1(0x4e463d0, 0xc0030f61b0)
server_1      |         /build/ko/pkg/middleware/rbac.go:30 +0xce
server_1      | github.com/kataras/iris/v12/context.DefaultNext(0x4e463d0, 0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343 +0x10c
server_1      | github.com/kataras/iris/v12/context.(*context).Next(0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352 +0x3e
server_1      | github.com/KubeOperator/KubeOperator/pkg/middleware.UserMiddleware(0x4e463d0, 0xc0030f61b0)
server_1      |         /build/ko/pkg/middleware/user.go:34 +0x2e9
server_1      | github.com/kataras/iris/v12/context.DefaultNext(0x4e463d0, 0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343 +0x10c
server_1      | github.com/kataras/iris/v12/context.(*context).Next(0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352 +0x3e
server_1      | github.com/KubeOperator/KubeOperator/pkg/middleware.(*JwtMiddleware).Serve(0xc000e3fc78, 0x4e463d0, 0xc0030f61b0)
server_1      |         /build/ko/pkg/middleware/jwt.go:25 +0x14d
server_1      | github.com/kataras/iris/v12/context.Do(0x4e463d0, 0xc0030f61b0, 0xc00183d5f0, 0x6, 0x6)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1030 +0x82
server_1      | github.com/kataras/iris/v12/context.(*context).Do(0xc0030f61b0, 0xc00183d5f0, 0x6, 0x6)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1217 +0x55
server_1      | github.com/kataras/iris/v12/core/router.(*routerHandler).HandleRequest(0xc00303c860, 0x4e463d0, 0xc0030f61b0)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/handler.go:250 +0x55f
server_1      | github.com/kataras/iris/v12/core/router.(*Router).BuildRouter.func1(0x4deb008, 0xc0014541c0, 0xc001834100)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:135 +0x8f
server_1      | github.com/kataras/iris/v12/i18n.(*I18n).Wrapper.func1(0x4deb008, 0xc0014541c0, 0xc001834100, 0xc003017cf8)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/i18n/i18n.go:437 +0xec
server_1      | github.com/kataras/iris/v12/core/router.(*wrapper).ServeHTTP(0xc0030af460, 0x4deb008, 0xc0014541c0, 0xc001834100)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:254 +0x50
server_1      | github.com/kataras/iris/v12/core/router.(*Router).ServeHTTP(0xc0002a1810, 0x4deb008, 0xc0014541c0, 0xc001834100)
server_1      |         /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:227 +0x48
server_1      | net/http.serverHandler.ServeHTTP(0xc0001ef880, 0x4deb008, 0xc0014541c0, 0xc001834100)
server_1      |         /usr/local/go/src/net/http/server.go:2868 +0xa3
server_1      | net/http.(*conn).serve(0xc0004303c0, 0x4df7548, 0xc0001364c0)
server_1      |         /usr/local/go/src/net/http/server.go:1933 +0x8cd
server_1      | created by net/http.(*Server).Serve
server_1      |         /usr/local/go/src/net/http/server.go:2994 +0x39b

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、创建可用区选择的是默认模板还是自定义模板
2、部署KubeOperator是下载的离线包还是在线脚本

**Comment by wuhl92** [comment]
1.还未到这一步，具体出问题API如下
![image](https://user-images.githubusercontent.com/28152197/161717714-c0bf57ee-21bd-414d-9f7d-29de9bb9f12d.png)。
2.下载的离线包。

**Comment by zhengkunwang223** [comment]
> 1.还未到这一步，具体出问题API如下 ![image](https://user-images.githubusercontent.com/28152197/161717714-c0bf57ee-21bd-414d-9f7d-29de9bb9f12d.png)。 2.下载的离线包。
vcenter 是否用了第三方交换机或者对网卡有其他的处理

**Comment by wuhl92** [comment]
什么叫第三方交换机或者对网卡有其他处理？
vcenter是部署在我们公司内网的，且rancher可以正常使用。

**Comment by zhengkunwang223** [comment]
> 什么叫第三方交换机或者对网卡有其他处理？ vcenter是部署在我们公司内网的，且rancher可以正常使用。

已经复现问题,govmomi的一个类型转换问题,在网络中含有交换机的情况下出现,下个版本会解决这个BUG.
暂时可以通过选择没有交换机的Datacenter来使用KO

**Comment by drscrewdriver** [comment]
这个能复现的吧 有下文吗？ 还找不到基于于openstack的KubeOperator最佳实践 不知道你那有没有类似的指南
