### ISSUE TITLE
[Bug]openstack 添加自动模式可用区 网络类型识别失败无法选择提交

### ISSUE THREAD

**Issue by drscrewdriver** [KubeOperator/KubeOperator#458]
**KubeOperator 版本**
版本: v3.14.0

**Kubernetes 版本**
不涉及

**Bug 描述**
centos8stream 下packstack生成 openstack  xena版本集群 选择网络时可以选择列表 public 或private 但是提交时显示输入项不能为空而不能添加可用区

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/19632018/162578932-388bdda8-5d99-4619-8ef0-078e23f1c219.png)

![image](https://user-images.githubusercontent.com/19632018/162578852-e8b62c32-1561-4f14-a073-cd8ad3ca031e.png)
选择网络时列表为空
选择IP类型为floating时网络类型出现 public和 private选项

**Comment by drscrewdriver** [comment]
openstack 支持版本范围是否有建议 如果是openstack版本支持问题 我可以更换openstack部署版本再做测试

**Comment by wanghe-fit2cloud** [comment]
问题已收到，感谢反馈。
