### ISSUE TITLE
[Bug] rokeylinux 8.5 创建集群 ipvs 模式 nf_conntrack_ipv4 名称版本错误导致无法继续安装

### ISSUE THREAD

**Issue by drscrewdriver** [KubeOperator/KubeOperator#459]
**KubeOperator 版本**
v3.14.0

**Kubernetes 版本**
v1.22.6-ko1 尝试安装未成功

**Bug 描述**

master和worker都是正常识别成了 rokeylinux 8.5 安装时 ipvs 模式 加载的模块仍然是nf_conntrack_ipv4 不是nf_conntrack 导致无法加载模块而继续安装 是否是支持这个类型的系统的呢 之后会换回centos系统再做尝试
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wanghe-fit2cloud** [comment]
目前版本还不支持 rokeylinux。
