### ISSUE TITLE
[Question]centos 高版本支持问题

### ISSUE THREAD

**Issue by drscrewdriver** [KubeOperator/KubeOperator#460]
**请描述您的问题.**
重新看了下文档rhel centos只写了支持7系列 8和9stream版本都不支持吗？

**Comment by wanghe-fit2cloud** [comment]
> **请描述您的问题.** 重新看了下文档rhel centos只写了支持7系列 8和9stream版本都不支持吗？

目前暂不支持8和9stream版本。
