### ISSUE TITLE
[Question] Offline installation

### ISSUE THREAD

**Issue by Jchicode** [KubeOperator/KubeOperator#461]
Hello, how can I support fully offline Kubernetes cluster deployment.
I failed at this step of apt.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/12872991/163962113-4808ef8c-c448-4a1a-9858-1159d7f57a43.png">

**Comment by Jchicode** [comment]
> 集群节点操作系统版本是多少？ 目前我们在开发环境适配的ubuntu版本有20.04和18.04，支持x86_64和arm64两种架构。

18.04, x86

**Comment by Jchicode** [comment]
<img width="361" alt="image" src="https://user-images.githubusercontent.com/12872991/163969473-3f39a187-0771-4f1e-b0ac-6a74da2668ae.png">

**Comment by wanghe-fit2cloud** [comment]
部署机IP:8081 查看一下仓库中是否有conntrack安装包
![image](https://user-images.githubusercontent.com/46734380/163969981-8c85688e-16bf-46c3-ab4c-ea3469a248b7.png)

![image](https://user-images.githubusercontent.com/46734380/163970081-e5cebbff-d1f0-4555-9124-8260a7cf378a.png)

**Comment by Jchicode** [comment]
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/12872991/163970750-c5e55688-0673-4d5c-b12b-064914a9fd48.png">
Without this, where to download this offline package

**Comment by wanghe-fit2cloud** [comment]
安装的哪个版本？是下载的离线包吗？

**Comment by Jchicode** [comment]
I downloaded https://kubeoperator.fit2cloud.com/nexus/nexus-v3.13.0.tar.gz

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/163971710-26173747-772a-4b20-a8e9-ac39aa22af07.png)

**Comment by Jchicode** [comment]
Hello, I found the problem. The offline package you provided has a relatively low apt version. I have executed apt-get update when there is a network condition, and then packaged the nexus file and placed it on the offline deployment machine, which can be executed normally.  
@wanghe-fit2cloud
