### ISSUE TITLE
[Question]Offline installation

### ISSUE THREAD

**Issue by Jchicode** [KubeOperator/KubeOperator#462]
Hello. I uploaded the offline package but it still doesn't work.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/12872991/164133403-8b4dcf1e-cfe1-4b20-8729-861ed2a69ea8.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/12872991/164133369-282c9a04-de14-4ffc-97e1-2d7f2d5c5388.png">

**Comment by wanghe-fit2cloud** [comment]
在master-1节点，手动执行 apt-get install conntrack ，看下具体的错误信息吧。

**Comment by Jchicode** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/12872991/164134964-f33605dd-5b88-4122-9171-ae19817d107c.png">

**Comment by Jchicode** [comment]
```apt-get update```
<img width="702" alt="image" src="https://user-images.githubusercontent.com/12872991/164136323-24e4d9e6-4056-485c-98f0-5475afe0697f.png">

**Comment by Jchicode** [comment]
This is nexus. Is it affected by this state?
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/12872991/164138311-047268bb-76fc-4455-93e2-7431eda61547.png">

**Comment by Jchicode** [comment]
My current environment is that there is no Internet access at all, only intranet communication

**Comment by wanghe-fit2cloud** [comment]
> My current environment is that there is no Internet access at all, only LAN communication

问题在于集群节点访问仓库， 502
![image](https://user-images.githubusercontent.com/46734380/164140879-662045d2-3051-4ab3-a24c-395d6755e42e.png)

**Comment by wanghe-fit2cloud** [comment]
离线包中已经将所需包缓存到了nexus apt仓库中，不需要外网环境。

**Comment by Jchicode** [comment]
He seems to fail when only apt, I can pull other repositories of the nexus.
<img width="788" alt="image" src="https://user-images.githubusercontent.com/12872991/164141111-56661a9d-5abf-4243-8c72-3c3c25c558ba.png">

**Comment by wanghe-fit2cloud** [comment]
在我们测试环境操作一下，看能不能复现吧。

**Comment by JohnNiang** [comment]
在问题还未得到 issue 作者确认之前，不建议 close 这个 issue。

It is not recommended to close this issue until the problem has been confirmed by the issue author.

**Comment by Jchicode** [comment]
Thank you, I restarted the nexus service, and the status of the apt-proxy-bionic repository is normal.
But after I execute ```apt-get update```, the request for the repository is 502.
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/12872991/164142823-92a7f077-4490-4977-b7a2-e69a6b87a89f.png">

**Comment by Jchicode** [comment]
> 在我们测试环境操作一下，看能不能复现吧。

Looking forward to a reply. I also debug it locally, and continue to discuss if there is progress

**Comment by Jchicode** [comment]
I read this configuration, it is proxy mode, not hosted.
This mode will request ```http://mirrors.aliyun.com/ubuntu``` and will not go to the local repository.
You can turn off the Internet here, or use a firewall to block the Internet@wanghe-fit2cloud 
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/12872991/164157466-78d43487-61e0-400d-ba09-4af4124d5ec8.png">
