### ISSUE TITLE
[Question] Offline installation

### ISSUE THREAD

**Issue by Jchicode** [KubeOperator/KubeOperator#463]
If there is any result, please reply here.
Duplicated with https://github.com/KubeOperator/KubeOperator/issues/461.

**Comment by wanghe-fit2cloud** [comment]
还没有复现你说的问题

**Comment by wanghe-fit2cloud** [comment]
有结果之后，会在issue中回复你，不需要重复开issues.

**Comment by Jchicode** [comment]
Okay, thank you! Can you open that issue?
