### ISSUE TITLE
[Question] 关于nexus oss的用途咨询

### ISSUE THREAD

**Issue by drscrewdriver** [KubeOperator/KubeOperator#464]
**请描述您的问题.**
这个nexus的存储的用处是什么 从KubeOperator 只能看到配置接入 它的地位似乎处于可有可无的地位
如果可以的话我可能更倾向于用外置harbor？ 这个的默认集群创建时回把设置的nexus设置为可信源?
另外工具面板、kubeapps、chartmuseum区别是什么 这块的功能介绍是否有

**Comment by wanghe-fit2cloud** [comment]
nexus: apt/rpm/docker/chart/raw仓库
