### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xlyoung** [KubeOperator/KubeOperator#465]
**KubeOperator 版本**

3.14
**Kubernetes 版本**

1.22
**Bug 描述**
因为我是x86和arm64混合架构，我安装kubeapp，应用跑在了我的arm64架构的服务器上，无法拉取kubeapp镜像。有什么办法只装在我的x86节点上？

需要可以指定x86节点安装吗？
**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/19601248/165266317-62556131-2dd2-4d14-9343-bc40e391b22e.png)

2.
![image](https://user-images.githubusercontent.com/19601248/165266361-3aa875dd-e4a1-40ad-99b5-2900d8286891.png)

3.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本中优化该问题。
