### ISSUE TITLE
Dashboard 不能访问

### ISSUE THREAD

**Issue by ghostdaxia** [KubeOperator/KubeOperator#467]
k8s集群dashboard为什么不能访问呢，提示 ： 
login error: 登录失败,用户名或密码错误

**Comment by wanghe-fit2cloud** [comment]
dashboard 的登录凭据：系统设置 - kubepi，默认用户密码：admin/kubepi

如果在kubepi系统中修改过用户密码，才需要在KO的系统设置- kubepi这里来手动同步，其他情况不需要手动修改这里。

**Comment by ghostdaxia** [comment]
可能是修改了admin口令的原因，重装不修改默认口令好了，似乎是这样的
