### ISSUE TITLE
[Bug] volumes里面configmap的items格式不正确

### ISSUE THREAD

**Issue by seaurching** [KubeOperator/KubeOperator#468]
**KubeOperator 版本**
v3.13.0

**Kubernetes 版本**
1.23.5
**Bug 描述**
deployment,daemonset等kind在挂载configmap的子key时,items应该在configmap下一级,而不是和configmap同级

这个是kubeoperator的界面显示的
![截图20220429124756](https://user-images.githubusercontent.com/7349963/165886677-8fea335e-534c-4918-a9a2-37ecf85b0ac8.png)

这个是官方文档的
![截图20220429125050](https://user-images.githubusercontent.com/7349963/165886868-9704c677-c1b1-4a3d-ba5d-bd01bef8f095.png)

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by wanghe-fit2cloud** [comment]
kubepi v1.5.0 版本已修复
