### ISSUE TITLE
[Bug]当使用混合架构时，cis扫描在拉取镜像是使用x86的，当work节点加载时报错

### ISSUE THREAD

**Issue by xlyoung** [KubeOperator/KubeOperator#469]
**KubeOperator 版本**
3.14

**Kubernetes 版本**
1.22

**Bug 描述**
当我们是混合架构时候，拉取这个cis所需要的pod 到集群内部执行时候，arm架构服务器的镜像使用的是 x86的

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/19601248/167054439-786ee60a-c53f-4317-9729-ecd82dccbe13.png)

2.
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/19601248/167054448-d76e415b-0402-41d4-ba12-7953a8ad23fe.png">

3.
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/19601248/167054472-c49ec642-ba24-4ff6-bdf2-47c51c45cfdf.png">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
后续版本修复该问题。
