### ISSUE TITLE
[Bug]全新安装k8s，部署rook-ceph失败

### ISSUE THREAD

**Issue by opser-gavin** [KubeOperator/KubeOperator#470]
**KubeOperator 版本** 版本: v3.14.0

**Kubernetes 版本**v1.22.6-ko1
![80ccb2c38043e0876ce12dd3f3cd504](https://user-images.githubusercontent.com/25680177/169431563-8b336c0e-4207-4f62-b30f-56510d2fff4b.png)

**Bug 描述** 全新安装以上版本k8s，部署rook-ceph失败

**Bug 重现步骤(有截图更好)**
1.之前安装的Ko（ko安装的时候要早一些，但没做特别修改只是会重启，不确定跟这有没关系）
2.全新安装k8s集群
3.在集群管理中-》存储-》存储提供商-》部署rook-ceph
![a0a07fef5187a22d808cc8a9960e5c6](https://user-images.githubusercontent.com/25680177/169431516-e63fa3dd-0f18-4c0b-81d1-435a0d33044f.png)

**Comment by wanghe-fit2cloud** [comment]
get
