### ISSUE TITLE
[Bug]添加glusterfs存储提供商失败

### ISSUE THREAD

**Issue by 9odes** [KubeOperator/KubeOperator#471]
**KubeOperator 版本**
3.14.0

**Kubernetes 版本**
1.22.6

**Bug 描述**
create provisioner error {"hibrain-master-1":"{"_ansible_no_log":false,"action":"yum","failed":true,"msg":"The conditional check 'ansible_distribution in [ 'CentOS','RedHat','EulerOS','Kylin Linux Advanced Server' ]' failed. The error was: error while evaluating conditional (ansible_distribution in [ 'CentOS','RedHat','EulerOS','Kylin Linux Advanced Server' ]): 'ansible_distribution' is undefined The error appears to be in '/var/kobe/data/project/ko/roles/plugins/cluster-storage/glusterfs/tasks/main.yml': line 1, column 3, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: - name: CentOS | Install glusterfs mount utils ^ here "}","hibrain-worker-1":"{"_ansible_no_log":false,"action":"yum","failed":true,"msg":"The conditional check 'ansible_distribution in [ 'CentOS','RedHat','EulerOS','Kylin Linux Advanced Server' ]' failed. The error was: error while evaluating conditional (ansible_distribution in [ 'CentOS','RedHat','EulerOS','Kylin Linux Advanced Server' ]): 'ansible_distribution' is undefined The error appears to be in '/var/kobe/data/project/ko/roles/plugins/cluster-storage/glusterfs/tasks/main.yml': line 1, column 3, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: - name: CentOS | Install glusterfs mount utils ^ here "}"}

**Comment by wanghe-fit2cloud** [comment]
在KubeOperator部署机找到以下yml文件（默认安装路径为/opt）：
/opt/kubeoperator/data/kobe/project/ko/10-plugin-cluster-storage-glusterfs.yml

手动删除 gather_facts: false
修改后文件为：
```yml
- hosts:
  - kube-master
  - kube-worker
  - new-worker
  roles:
  - plugins/cluster-storage/glusterfs
```
再重新添加gfs存储提供商，看是否能添加成功。

**Comment by 9odes** [comment]
> 在KubeOperator部署机找到以下yml文件（默认安装路径为/opt）： /opt/kubeoperator/data/kobe/project/ko/10-plugin-cluster-storage-glusterfs.yml
> 
> 手动删除 gather_facts: false 修改后文件为：
> 
> ```yaml
> - hosts:
>   - kube-master
>   - kube-worker
>   - new-worker
>   roles:
>   - plugins/cluster-storage/glusterfs
> ```
> 
> 再重新添加gfs存储提供商，看是否能添加成功。

可以成功添加了，谢谢
