### ISSUE TITLE
[Bug]【华为FusionCompute】通过KO部署计划创建集群报错

### ISSUE THREAD

**Issue by fit2cloud-baozezhong** [KubeOperator/KubeOperator#475]
**KubeOperator 版本**
目前使用的是3.11版本，但是最新版本3.14也是有这个问题

**Kubernetes 版本**
集群版本 v1.20.10-ko1，Kubernetes貌似页面上没看到

**Bug 描述**
创建华为FusionCompute部署计划，然后通过部署计划创建集群报错，init cluster resource for create failed: site  not found 
实际改了下代码解决这个发现下一步，又会有 no such host报错

**Bug 重现步骤(有截图更好)**
1.创建区域选择云提供商为华为Fusioncompute
2.选择上述区域创建可用区
3.选择呢上述可用区创建部署计划
4.创建集群选择部署计划创建，会在集群的状态中发现失败，日志详情init cluster resource for create failed: site  not found

**Comment by fit2cloud-baozezhong** [comment]
![image](https://user-images.githubusercontent.com/72718889/173994892-5e958545-b152-4da6-8a4b-b3fbb76db2de.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本中修复该问题。

**Comment by wanghe-fit2cloud** [comment]
最新版本 v3.16.0 已发布。
