### ISSUE TITLE
[Feature]建议优化集群详情页面中关键信息显示

### ISSUE THREAD

**Issue by chenxin2001** [KubeOperator/KubeOperator#476]
**请描述您的需求或者改进建议.**
现状：
当前在 KO 集群详情页面中部分关键信息显示不够明显，包括：
1. 集群名称，只能在“集群详情-概览”中显示，若存在多集群的情况下，切换其他页签时，容易混淆目前正在操作的是哪个集群。
2. 容量信息，当前显示使用百分比，但没具体数值，如CPU总量是多少MHZ，对于使用者来说只显示百分比没有很大参考价值。

优化建议：
1.集群名称显示置顶，如在“集群详情”字段后面显示“集群名称”；
2.容量信息，显示具体的监控指标数值，供用户参考。

![image](https://user-images.githubusercontent.com/34565342/174273544-c4c83827-4b42-4c94-99c9-a9dd46410a44.png)

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by wanghe-fit2cloud** [comment]
v3.5.1 版本已优化。
