### ISSUE TITLE
[Question]添加主机时报错

### ISSUE THREAD

**Issue by chunfz** [KubeOperator/KubeOperator#477]
**环境**
- 虚拟化平台 **Hyper-V**
- 主机操作系统 **CentOS Linux release 7.9.2009 (Core)**

**报错信息**
Invalid entry length (0). DMI table is broken! Stop.

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by wanghe-fit2cloud** [comment]
应该是获取主机资源时不兼容导致的，后续版本会修复该问题。

**Comment by chunfz** [comment]
测试发现，Hyper-V 2代虚拟机没有这个问题。

**Comment by wanghe-fit2cloud** [comment]
> 测试发现，Hyper-V 2代虚拟机没有这个问题。

好的。
