### ISSUE TITLE
[Bug]KubePi日志显示异常

### ISSUE THREAD

**Issue by chenxin2001** [KubeOperator/KubeOperator#479]
**KubeOperator 版本**
KubePi v1.5.2

**Kubernetes 版本**

**Bug 描述**
KubePi日志显示异常，出现以下2个问题：
1. 容器运行一段时间后，会出现字符乱码且日志无法实时打印；
2. 使用日志文件下载，本地打开中文字符显示乱码

**Bug 重现步骤(有截图更好)**
1.登录kubepi；
2.选择运行一段时间后的容器，在线查看其日志，会出现字符乱码且日志无法实时打印，如图所示
![image](https://user-images.githubusercontent.com/34565342/175856462-83520ec8-fa17-4c20-9db6-aaf41573d5bb.png)
3.选择打印中文字符日志的容器，在线查看其日志，并下载日志文件。通过本地编辑器打开日志文件，中文部分显示乱码，如图所示：
![image](https://user-images.githubusercontent.com/34565342/175856563-c7173645-788c-4d2b-a933-89f6e4a3f24b.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
[KubePi](https://github.com/KubeOperator/KubePi/) 是我们另外一款开源产品
