### ISSUE TITLE
Failed to install some of the specified packages

### ISSUE THREAD

**Issue by hmy111** [KubeOperator/KubeOperator#485]
Failed to install some of the specified packages
环境：虚拟机 Centos8 aarch64
<img width="769" alt="image" src="https://user-images.githubusercontent.com/39590293/178550976-3361a7b0-ae7a-4199-9b6d-61f23877cad9.png">

**Comment by wanghe-fit2cloud** [comment]
https://kubeoperator.io/docs/installation/install/

![image](https://user-images.githubusercontent.com/46734380/178634914-43a5f939-d7c5-4462-b43b-da39fcbcd5e1.png)
