### ISSUE TITLE
[Feature]兼容 Safire

### ISSUE THREAD

**Issue by merlinHou** [KubeOperator/KubeOperator#486]
**请描述您的需求或者改进建议.**
KubeOperator系统设置添加仓库，连接性测试通过但无法点击提交 （ 对Safire没有适配，chrome可以）

**Comment by wanghe-fit2cloud** [comment]
我在本地的 Safari 浏览器，版本15.5 (17613.2.7.1.8)，没有复现添加仓库不兼容的问题。
请问，你所使用的 Safari 和 KubeOperator 分别是什么版本？
