### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by merlinHou** [KubeOperator/KubeOperator#487]
**KubeOperator 版本**

3.15.1
**Kubernetes 版本**

v1.22.10
**Bug 描述**

添加集群
**Bug 重现步骤(有截图更好)**
1.使用系统centos 内核 版本Linux 4.18.0或者Linux2.6.31，创建集群失败
2.journalctl -xe查看日志，出现Failed to find module 'nf_conntrack_ipv4'
3.高版本的centos内核nf_conntrack_ipv4被nf_conntrack替换了。建议增加对不同内核的判断

**Comment by wanghe-fit2cloud** [comment]
1、脚本中存在针对内核版本的判断：
kernel >= 4.19: nf_conntrack
kernel < 4.19: nf_conntrack_ipv4

2、集群节点支持的操作系统，参考官方文档：
https://kubeoperator.io/docs/installation/install/
![image](https://user-images.githubusercontent.com/46734380/178689576-499ac041-5fc2-449a-9bef-62996606de20.png)

**Comment by merlinHou** [comment]
那应该是CentOS Stream release 8的问题我先换成ubuntu

**Comment by merlinHou** [comment]
> 1、脚本中存在针对内核版本的判断：内核>= 4.19：nf_conntrack内核<4.19：nf_conntrack_ipv4
> 
> 2、集群节点支持的操作系统，参考官方文档： https://kubeoperator.io/docs/installation/install/ ![图像](https://user-images.githubusercontent.com/46734380/178689576-499ac041-5fc2-449a-9bef-62996606de20.png)

CentOS Stream release 8  内核Linux 4.18.0会有这个问题
