### ISSUE TITLE
exec: "docker": executable file not found in $PATH

### ISSUE THREAD

**Issue by wuqiang3424** [KubeOperator/KubeOperator#488]
初始化控制平面
cmd
/usr/local/bin/kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml
message
non-zero return code
stderr
error execution phase preflight: [preflight] Some fatal errors occurred:
[ERROR FileExisting-crictl]: crictl not found in system path
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
stdout
[init] Using Kubernetes version: v1.22.10
[preflight] Running pre-flight checks
[preflight] WARNING: Couldn't create the interface used for talking to the container runtime: docker is required for container runtime: exec: "docker": executable file not found in $PATH

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/178697468-d9c8efe7-63be-42c8-9466-3462a0b293c7.png)

**Comment by wuqiang3424** [comment]
![image](https://user-images.githubusercontent.com/32158667/178701171-3a42c686-8686-4645-8ae3-d459c5c62706.png)
这个是有的

**Comment by wanghe-fit2cloud** [comment]
> ![image](https://user-images.githubusercontent.com/32158667/178701171-3a42c686-8686-4645-8ae3-d459c5c62706.png) 这个是有的

在 KubeOperator 系统中录入主机时，选择的凭据也是 root 用户吗?

**Comment by wuqiang3424** [comment]
换了root，重新部署可以了，多谢
