### ISSUE TITLE
Kubeapps启动不了

### ISSUE THREAD

**Issue by hmy111** [KubeOperator/KubeOperator#489]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/39590293/178902362-faaddfc3-34c9-4cb6-9120-20cee962a239.png">

环境：Ubuntu 20.4 aarch64
日志： standard_init_linux.go:228: exec user process caused: exec format error

**Comment by wanghe-fit2cloud** [comment]
kubeapps 官方不支持 arm64

**Comment by hmy111** [comment]
好的
