### ISSUE TITLE
[Question]kubepi修改密码后，导致Dasboard无法登录

### ISSUE THREAD

**Issue by liujunfei980** [KubeOperator/KubeOperator#490]
问题描述
KO版本: 3.14.0
在系统设置中修改kubepi密码后，打开Dashboard一直提示用户名或密码错误
![image](https://user-images.githubusercontent.com/35226938/179337092-ee9e25e8-376a-4af3-92ac-b7c4a301b37f.png)
![image](https://user-images.githubusercontent.com/35226938/179337139-ed365f67-02c1-43b9-9cb8-b6b7dd30df95.png)

**Comment by wanghe-fit2cloud** [comment]
kubepi默认密码：admin/kubepi

修改密码需要到kubepi系统中修改，然后在ko系统设置这里同步

**Comment by wanghe-fit2cloud** [comment]
你可以将 ko 升级到最新版本 v3.15.1

**Comment by liujunfei980** [comment]
> 你可以将 ko 升级到最新版本 v3.15.1

好的，我升级下KO
