### ISSUE TITLE
[Feature]升级demo环境服务器内核

### ISSUE THREAD

**Issue by mongoliaredmountain** [KubeOperator/KubeOperator#491]
**请描述您的需求或者改进建议.**
是否能升级一下Demo环境CentOS7.9的内核到5.4+，否则没有办法部署CNI插件cilium

**Comment by wanghe-fit2cloud** [comment]
是的，cilium 对 kernel 版本有要求。
Demo 环境升级内核的问题，我们后续会考虑的。
