### ISSUE TITLE
[Bug]Retry error beacuse of "ansible_distribution variable is not defined "

### ISSUE THREAD

**Issue by lengpucheng** [KubeOperator/KubeOperator#493]
**KubeOperator 版本**
v3.15

**Kubernetes 版本**
v1.22.8-ko1

**Bug 描述**
当创建集群中出现异常中断（例如掉电】网络波动或其他原因），点击重试，之后提示未找到  ansible_distribution

**Bug 重现步骤(有截图更好)**
1. 在KUBERNETES组件初始化前的任意步骤，中断KO与被控机之间的网络，等待ansible超时，KO显示部署异常
2. 点击异常集群重试
4. 等到KUBERNETES组件初始化步骤，会提示 ansible_distribution 找不到该变量

**可能的原因**
翻阅KO/ansible源代码[roles/prepare/kubernetes/tasks/main.yml#L40](https://github.com/KubeOperator/ansible/blob/master/roles/prepare/kubernetes/tasks/main.yml#L40) 其中有使用该变量对操作系统进行判断的语句，猜测可能的原因系**该变量在集群初始化中注入到ansible变量中，重试时未注入**，希望可以排查解决该问题。同理如果该原因为实际的原因，则可能**所有的在创建集群中传入的自定义变量都会受到影响**！！！！

**Comment by wanghe-fit2cloud** [comment]
你先把集群删除，重建吧。
你反馈的问题，我们在本地复现追踪一下。

**Comment by wugh888** [comment]
网络模式选择了cilium ，然后扩展节点 也会有这个错误

**Comment by lengpucheng** [comment]
这个问题已经解决
