### ISSUE TITLE
[Question]config file not found in /etc/kubepi

### ISSUE THREAD

**Issue by wuqiang3424** [KubeOperator/KubeOperator#494]
![image](https://user-images.githubusercontent.com/32158667/180370595-1a16f4ea-c6fd-45dd-80c5-a55aae626a77.png)

这个报错是缺什么文件了，帮忙给看看吧

**Comment by wanghe-fit2cloud** [comment]
部署的是什么版本

**Comment by wuqiang3424** [comment]
![image](https://user-images.githubusercontent.com/32158667/180373749-3e6fb003-b3f1-4f4a-82e3-a7ea2c9920d5.png)
版本: v3.15.1

**Comment by wanghe-fit2cloud** [comment]
koctl status 看一下服务状态

**Comment by wuqiang3424** [comment]
![image](https://user-images.githubusercontent.com/32158667/180374055-ca8b43df-71ef-445e-87dd-5f49ff5b1a0a.png)

**Comment by wuqiang3424** [comment]
影响到了，具体是在给集群授权用户的时候失败，报超时的问题，查看后端调用的容器日志发现有上述问题存在
![image](https://user-images.githubusercontent.com/32158667/180374731-ebe45550-a852-4dcc-b45f-7ffda33afc7b.png)

**Comment by wanghe-fit2cloud** [comment]
两个问题

**Comment by wanghe-fit2cloud** [comment]
集群是通过KubeOperator创建的吗？版本是什么？

**Comment by wuqiang3424** [comment]
问题1.集群不是通过KubeOperator创建的，是二进制的方式，admin用户可以看到全部信息
问题2.版本是v1.19.16

**Comment by wanghe-fit2cloud** [comment]
1.19 版本我们也没有测试过兼容性（KubeOperator 目前支持 1.18、1.20、1.22三个大版本）

admin 用户没问题的话，应该是在调用授权接口时超时了，有可能是版本 API 兼容性的问题
