### ISSUE TITLE
[Question]啟用GPU功能後，nvidia gpu 相關pod無法初始化

### ISSUE THREAD

**Issue by liujunfei980** [KubeOperator/KubeOperator#495]
OS版本：Centos7.8
內核版本：3.10.0-1127
kubeoperator版本：3.14.0
nvidia型號：Tesla P100
nvidia驅動版本：460.73.01
使用ko啟動GPU功能後，創建的pod無法初始化，如下截圖：
![image](https://user-images.githubusercontent.com/35226938/180595541-f4669de9-cbd8-4b0d-be1d-eb0b0870bec1.png)
查看nvidia-driver-daemonset-hm9pb 日誌信息，如下截圖：
![image](https://user-images.githubusercontent.com/35226938/180595621-cb3f0017-af6c-45e6-a193-74b49b9dceb3.png)
![image](https://user-images.githubusercontent.com/35226938/180595626-a7b38268-bffc-4ce4-bead-0cbf59aa7407.png)

**Comment by wanghe-fit2cloud** [comment]
gpu-operator项目地址: https://github.com/NVIDIA/gpu-operator

可以在该项目下查找相关问题的解决方案，也可以尝试手动卸载后部署最新版本

**Comment by liujunfei980** [comment]
> gpu-operator项目地址: https://github.com/NVIDIA/gpu-operator
> 
> 可以在该项目下查找相关问题的解决方案，也可以尝试手动卸载后部署最新版本

已解決，導致該問題的原因是Centos7.8內核版本低，而該nvidia-driver-daemonset中的image驅動版本太高導致，通過以下幾個步驟解決該問題：
1.pull 官方image
   docker pull nvidia/driver:440.64.00-1.0.0-3.10.0-1127.el7.x86_64-centos7
2.重新修改tag
   docker tag nvidia/driver:440.64.00-1.0.0-3.10.0-1127.el7.x86_64-centos7 registry.kubeoperator.io:8082/kubeoperator/driver:440.64.00-centos7
3.kubectl edit daemonsets.apps nvidia-driver-daemonset -n gpu-operator-resources 
    更換該daemonsets中的image為registry.kubeoperator.io:8082/kubeoperator/driver:440.64.00-centos7
![image](https://user-images.githubusercontent.com/35226938/180720037-bcd77e78-b54e-4afe-a8ec-3a7bece54512.png)
幫助文檔：https://github.com/NVIDIA/gpu-operator/issues/155
