### ISSUE TITLE
[Bug]扩容k8s集群worker节点配置，KO主机管理列表中相应地主机配置信息无法同步

### ISSUE THREAD

**Issue by chenxin2001** [KubeOperator/KubeOperator#496]
**KubeOperator 版本**
v3.16.0

**Kubernetes 版本**
1.22

**Bug 描述**
扩容k8s集群worker节点配置，增加主机的内存大小。KO主机管理列表中相应地主机配置信息无法同步

**Bug 重现步骤(有截图更好)**
1.在虚拟化平台中增加worker节点的内存大小
2.在KO平台，进入“主机”栏，勾选已完成扩容的节点，并点击同步。
3.主机的CPU、内存信息仍为扩容前配置信息，无法更新同步成功。
![image](https://user-images.githubusercontent.com/34565342/182790784-74c47cdc-8b35-4d65-bc85-22d6b5a3b000.png)
![image](https://user-images.githubusercontent.com/34565342/182790909-4b11a06f-69b5-4307-a834-4b01eaf53e8c.png)
![image](https://user-images.githubusercontent.com/34565342/182791059-b9a30e53-4a7e-41c8-b33e-29c0ee6b8c2d.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重启服务器后生效.
