### ISSUE TITLE
[Bug] 创建备份账号，添加 minio  buckets 无法显示

### ISSUE THREAD

**Issue by wojiushixiaobai** [KubeOperator/KubeOperator#498]
手动填写也填写不了

![1c667a28ed0b4815eeb62b124558402](https://user-images.githubusercontent.com/24326988/183329038-3f9315ff-80ae-490a-a9f7-79aad855155d.png)

**Comment by wanghe-fit2cloud** [comment]
Bucket 信息是通过下方“获取桶”按钮动态获取的，不支持手动输入。
如果点击按钮后没有桶信息，先手动确认一下输入的 endpoint 等信息是否正确。
