### ISSUE TITLE
[Feature]备份账号支持Minio的https协议

### ISSUE THREAD

**Issue by chenxin2001** [KubeOperator/KubeOperator#500]
**请描述您的需求或者改进建议.**
在KO的备份账号中添加Minio账号信息时，发现
endpoint地址只支持http协议，配置https协议提示获取桶失败。希望后续能支持https协议的minio环境
![image](https://user-images.githubusercontent.com/34565342/183871872-f2e72d2b-c660-4579-a164-aaa3119b0240.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
最新版本 v3.16.2 已支持。
