### ISSUE TITLE
[Bug]deployment页面连续伸缩 会显示多个deployment的伸缩并有可能一起修改成功

### ISSUE THREAD

**Issue by drscrewdriver** [KubeOperator/KubeOperator#501]
**KubeOperator 版本**
 v3.16.0

**Kubernetes 版本**
v1.22.12-ko1

**Bug 描述**

![image](https://user-images.githubusercontent.com/19632018/184107589-333b713b-dfb3-4127-a749-4cc6fd89d36a.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wanghe-fit2cloud** [comment]
将 issues 反馈到 KubePi 项目：
https://github.com/KubeOperator/KubePi/issues
