### ISSUE TITLE
[Bug] 集群 - 备份 - ETCD 备份/恢复，生成出的备份文件有8小时时差

### ISSUE THREAD

**Issue by fzhygithub** [KubeOperator/KubeOperator#503]
**KubeOperator 版本**
kubeoperator-release-v3.15.0

**Kubernetes 版本**
v1.22.8-ko1

**Bug 描述**
集群 - 备份 - ETCD 备份/恢复，生成出的备份文件有8小时时差

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Bug 修整方法**
kube-operator部署机

在容器配置中增加宿主时区挂载
vim /opt/kubeoperator/docker-compose.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro

提醒：如果更改了Yaml，则需要重新创建容器
docker-compose -f /opt/kubeoperator/docker-compose.yml stop
docker-compose -f /opt/kubeoperator/docker-compose.yml rm

启动容器服务
koctl start

更新后的容器时区验证
[root@kubeoperator ~]# docker exec -it kubeoperator_server date
Wed Aug 17 16:13:47 CST 2022

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
