### ISSUE TITLE
[Feature]CentOS7 停止支持服务后，会转向哪些系统呢？

### ISSUE THREAD

**Issue by drscrewdriver** [KubeOperator/KubeOperator#504]
**请描述您的需求或者改进建议.**
阿里云os系统能支持吗？

**Comment by drscrewdriver** [comment]
因为centos7要停止支持服务了 后期会转向哪些系统呢？

**Comment by wanghe-fit2cloud** [comment]
> **请描述您的需求或者改进建议.** 阿里云os系统能支持吗？

不支持。

**Comment by wanghe-fit2cloud** [comment]
> 因为centos7要停止支持服务了 后期会转向哪些系统呢？

目前支持的操作系统有：
https://kubeoperator.io/docs/installation/install/

![image](https://user-images.githubusercontent.com/46734380/185822430-f901a316-a490-4780-a71a-1e860f90f5ab.png)
