### ISSUE TITLE
[Bug]vSphere虚拟机的模板修改后，就无法再创建新集群和扩充新节点

### ISSUE THREAD

**Issue by wugh888** [KubeOperator/KubeOperator#507]
**KubeOperator 版本**
3.16.2

**Kubernetes 版本**
1.20.14

**Bug 描述**
修改vSphere虚拟机的模板
1.将模板转为虚拟机
2.修改完虚拟机的配置后转换为模板
3.然后就无法再创建集群和扩充节点了。在这个过程中模板名字没有改变
是否有可能是配置中记录的是模板id，在我转换后id变了？

![image](https://user-images.githubusercontent.com/17397052/187576319-048be2e7-6c60-4d53-948b-8a3b31899b30.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wugh888** [comment]
好想在这个界面重新选择一次模板，确定后就好了。。。。。。。。。。。

**Comment by wanghe-fit2cloud** [comment]
Get.
