### ISSUE TITLE
[Bug]Minio备份账号更新bucket信息，执行备份任务时未生效

### ISSUE THREAD

**Issue by chenxin2001** [KubeOperator/KubeOperator#509]
**KubeOperator 版本**
v3.16.2

**Kubernetes 版本**

**Bug 描述**
当一个备份账号存在多个bucket时
Minio备份账号更新bucket信息，执行备份任务时未生效

**Bug 重现步骤(有截图更好)**
1.进入KO，选择“备份账号”中其中一个备份账号点击“编辑”；
2.修改桶信息，由原"test"桶切换成“test2”桶，点击保存；
3.进入k8s集群详情页面，选择“备份/恢复”，点击“备份”创建备份任务，配置手动执行任务；
4.待任务执行完成，登录Minio环境分别查看“test”和“test2”的桶数据；
5.新增的备份文件仍创建在原“test“桶中。
这是同一个账号切换不同桶的问题，实际上删除备份账号1创建备份账号2，修改“备份/恢复”里的账号信息执行任务，一样会把备份数据存放在已被删除备份账号1的桶里面
![image](https://user-images.githubusercontent.com/34565342/189022366-cfe550cc-482d-43d2-969f-3379a2460623.png)
![image](https://user-images.githubusercontent.com/34565342/189022344-0a4ab7b7-af06-4328-8b2e-91ece073726b.png)
![image](https://user-images.githubusercontent.com/34565342/189022416-dfcbd3b8-3bc2-459b-9a05-1b5fe55e2f16.png)
![image](https://user-images.githubusercontent.com/34565342/189022448-0bc3f9a3-f47b-4c86-85c1-3587f37be2f4.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本中修复该问题。
