### ISSUE TITLE
[Bug]删除vSphere存储提供商失败，the output has been hidden due to the fact that 'no_log: true' was specified for this result

### ISSUE THREAD

**Issue by ldzbook** [KubeOperator/KubeOperator#510]
**KubeOperator 版本**
v3.16.2

**Kubernetes 版本**
v1.22.12

**Bug 描述**
删除vSphere存储提供商失败，the output has been hidden due to the fact that 'no_log: true' was specified for this result
![a0f8c2419dee2648db2b3c8c9f437ce](https://user-images.githubusercontent.com/13903790/189024116-a8e7abaa-5468-4a82-860f-c34d8524e06d.jpg)
![4b5d3f30d633347aafe221602f6ca85](https://user-images.githubusercontent.com/13903790/189024207-957b4d1e-4bf2-4e1e-a980-e661967d73c8.jpg)

**Bug 重现步骤(有截图更好)**
1.新增vSphere类型存储供应商
![image](https://user-images.githubusercontent.com/13903790/189024768-2b2d86ff-c435-4f59-8d11-388230d877a6.png)

2.qi启用工具，并启用存储
![image](https://user-images.githubusercontent.com/13903790/189024326-f30a3c81-58a5-4dda-8478-16e4de44781d.png)

3.工具启用失败，报错pod has unbound immediate PersistentVolumeClaims 

4.禁用工具，删除存储类，删除存储供应商

5.怀疑存储供应商创建问题，反复上述操作。更改创建方式，使用“导入”；更改namespace。尝试删除后再启用工具，多次尝试后出现删除vSphere存储提供商失败

**Comment by ldzbook** [comment]
期间，通过kubepi检查启动失败的pod，发现yaml配置中，没有相关vsphere存储类的配置

**Comment by wanghe-fit2cloud** [comment]
可以进去集群，通过命令查看 vsphere-csi 相关 pod 是否都运行正常？
也可以配合 kubectl logs、describe 等命令查看相关 pod 日志、事件等。

**Comment by ldzbook** [comment]
不存在vsphere相关pod

**Comment by wanghe-fit2cloud** [comment]
登录 KubeOperator 服务器，删除 no_log: true 相关配置（文件及所在路径见下图），然后再执行卸载和安装 vsphere 操作，看一下具体的日志信息。

![image](https://user-images.githubusercontent.com/46734380/189796437-a9a2f399-dbed-4bb7-b528-ed5f3d9be8ef.png)
![image](https://user-images.githubusercontent.com/46734380/189796542-9f4f6698-b49a-409c-9b55-c050e6158065.png)

**Comment by ldzbook** [comment]
删除vsphere时异常信息如下
![image](https://user-images.githubusercontent.com/13903790/189799128-0c054ee8-f3b2-45f6-a76b-ccdab09020f6.png)

**Comment by wanghe-fit2cloud** [comment]
在我们的开发环境（vSphere Client 版本 7.0.3.00100）没有复现你反馈的问题，
看一下是不是跟你的 vSphere 版本有关系。
