### ISSUE TITLE
[Bug]vsphere集群扩容，报错“create host model failed: datacenter '' not found”

### ISSUE THREAD

**Issue by ldzbook** [KubeOperator/KubeOperator#511]
**KubeOperator 版本**
v3.16.2

**Kubernetes 版本**
 v1.22.12

**Bug 描述**
vsphere集群节点扩容，报错“create host model failed: datacenter '' not found”，然后“节点扩容”任务就一直等待中
![cbfdcf05e425484a54f0e798a8f209f](https://user-images.githubusercontent.com/13903790/190036131-0f56f048-fe62-4473-a199-984dbd5c7135.jpg)
![0786fafcd8fd18bbc18c0ede9299664](https://user-images.githubusercontent.com/13903790/190036242-250f402a-1691-41e8-9474-6995a1fe6836.jpg)

**Bug 重现步骤(有截图更好)**
1.通过vsphere使用官方模板创建的集群，节点配置未作更改，节点扩容失败。重新创建的集群也是如此，必现
2.
3.

**Comment by wanghe-fit2cloud** [comment]
在我们的开发环境（vSphere Client 版本 7.0.3.00100）没有复现你反馈的问题，
看一下是不是跟你的 vSphere 版本有关系。

**Comment by ldzbook** [comment]
可能是，vSphere Client 版本6.7.0

**Comment by ldzbook** [comment]
还有两个问题
那该如何将“节点扩容”任务取消？
是否就完全无法使用节点伸缩，也不能手动扩容？

**Comment by wanghe-fit2cloud** [comment]
1、重启 KO 服务后，删除节点时选择强制删除
2、在我们的开发环境（vSphere Client 版本 7.0.3.00100）没有出现自动模式扩容、缩容失败的问题，可能和版本有关系
