### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by fws20060501** [KubeOperator/KubeOperator#513]
**请描述您的问题.**
KubeOperator版本: v3.16.2
kubernetes : v1.20.14
docker : 20.10.7
etcd : v3.4.14
containerd : 1.4.3

我的master其中一个节点故障掉了，请问我怎么恢复回去或新加入一台master机。

![image](https://user-images.githubusercontent.com/51530023/191550561-59429165-d4ef-44d8-883c-7c561eb6b7b0.png)
![image](https://user-images.githubusercontent.com/51530023/191550698-569f727c-b84b-4e78-83a8-8bdbda531cf6.png)

**Comment by fws20060501** [comment]
> 后续版本会支持添加 master 节点功能。

那现在Master节点故障得如何修复，重新加入一台同样IP的主机，它会自动再去安装这些组件吗？

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/191648819-7c9a08bd-651d-49b1-a255-8e664fc865cd.png)
先确定你这台服务器还能不能继续正常使用吧。
不能修复的话，可以将该节点强制删除，当前版本你可以继续添加worker节点。

**Comment by fws20060501** [comment]
> ![image](https://user-images.githubusercontent.com/46734380/191648819-7c9a08bd-651d-49b1-a255-8e664fc865cd.png) 先确定你这台服务器还能不能继续正常使用吧。 不能修复的话，可以将该节点强制删除，当前版本你可以继续添加worker节点。

这台已经不能再用了，但是把他删除掉的话，不是master就少了一台，而且etcd也不是三节点了。

**Comment by wanghe-fit2cloud** [comment]
是的，2 个 master 节点暂不影响集群的正常使用，等支持添加 master 节点版本发布后再升级。
