### ISSUE TITLE
[Bug]KO 运行一段时间后会产生大量僵尸进程，触发机器的监控告警信息

### ISSUE THREAD

**Issue by chenxin2001** [KubeOperator/KubeOperator#514]
**KubeOperator 版本**
v3.16

**Kubernetes 版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. KO 运行一段时间后；
2. 登录KO部署机后台，执行ps 相关命令 ps -e -o stat,ppid,pid,cmd | egrep '^[Zz]' ；
3. 发现大量僵尸进程
4. kill -9 处理僵尸进程导致KO控制台无法登录，需重启KO服务才能恢复正常。
zabbix告警：
![image](https://user-images.githubusercontent.com/34565342/191713983-1c25209c-25f2-4d82-957a-3c73aea62c04.png)
部署机上的僵尸进程：
![image](https://user-images.githubusercontent.com/34565342/191713982-1eb15bbb-77d8-4fd4-9a7d-71c005f85978.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本中优化该问题。

**Comment by wanghe-fit2cloud** [comment]
最新版本已修复上述问题。
