### ISSUE TITLE
[Question]The Python 2 bindings for rpm are needed for this module

### ISSUE THREAD

**Issue by 9odes** [KubeOperator/KubeOperator#516]
**请描述您的问题.**
部署集群报错
日志：
准备系统环境
hibrain-master-1
TASK [prepare/base : Install base rpm package] *********************************
fatal: [hi-master-1]: FAILED! => {"changed": false, "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}

系统版本 CentOS Linux release 7.9.2009 (Core)
Python版本 
Python 2.7.5 (default, Nov 16 2020, 22:23:17)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2

**Comment by wanghe-fit2cloud** [comment]
参考：https://github.com/KubeOperator/KubeOperator/issues/396

**Comment by 9odes** [comment]
使用python3脚本依旧报这个错误
