### ISSUE TITLE
编译出错[Question]

### ISSUE THREAD

**Issue by Michael754267513** [KubeOperator/KubeOperator#517]
**请描述您的问题.**
下载master，进行docker build  发现不成功。
GOOS=linux GOARCH=amd64  go-bindata -o ./pkg/i18n/locales.go -pkg i18n ./locales/...
GOOS=linux GOARCH=amd64  go build -o /build/ko/dist/usr/local/bin/ko-server main.go
vendor/helm.sh/helm/v3/internal/fileutil/fileutil.go:25:2: //go:build comment without // +build comment
vendor/helm.sh/helm/v3/pkg/cli/environment.go:35:2: //go:build comment without // +build comment
vendor/sigs.k8s.io/json/json.go:24:2: //go:build comment without // +build comment
make: *** [Makefile:17: build_server_linux] Error 1
The command '/bin/sh -c make build_server_linux GOARCH=$GOARCH' returned a non-zero code: 2

**Comment by Michael754267513** [comment]
修改dockerfile 相关 参数。 
ARG GOPROXY="https://goproxy.cn"
ARG GOARCH="amd64"
ARG XPACK="yes"

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后面版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
master 分支已修复。
