### ISSUE TITLE
镜像拉取失败

### ISSUE THREAD

**Issue by Ben-DA** [KubeOperator/KubeOperator#519]
我安装成功了一个新的集群，并且选择了带有GPU支持，但是新的gpu节点加入后，关于nvidia的相关pods出现backoff pulling image，于是我在目标节点上手动执行了docker pull registry.kubeoperator.io:8082……
但是报错是no such host。
我也尝试ping registry.……了，但是还是找不到目标主机。
这要如何修复呢
![图片](https://user-images.githubusercontent.com/76471614/194268775-3a4e031a-2c2b-4ea6-a668-0c5a2a25eace.png)
![图片](https://user-images.githubusercontent.com/76471614/194268974-b944e5cb-b2aa-4dbc-9d31-4862438f06e7.png)

**Comment by wanghe-fit2cloud** [comment]
registry.kubeoperator.io 是写入 /etc/hosts 文件的，指向了 KO 的部署节点。
你可以手动添加 hosts 记录后再尝试一下 pull 镜像。

**Comment by Ben-DA** [comment]
我尝试了您的方法，然后新的报错出现了。
`Failed to pull image "registry.kubeoperator.io:8082/kubeoperator/driver:460.73.01-ubuntu20.04": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.kubeoperator.io:8082/kubeoperator/driver:460.73.01-ubuntu20.04 not found: manifest unknown: manifest unknown`
似乎是不存在该镜像，这要如何解决呢

**Comment by wanghe-fit2cloud** [comment]
GPU 相关镜像需要部署机可以访问外网，将镜像缓存到 nexus 仓库中（镜像仓库是 proxy 类型），上述报错应该是在缓存过程中超时导致的。
