### ISSUE TITLE
[Bug]KO安装K8S时无法找到正确的环境变量

### ISSUE THREAD

**Issue by wanghaibo-person** [KubeOperator/KubeOperator#522]
**KubeOperator 版本**
v3.16.2

**Kubernetes 版本**
v1.22.12

**Bug 描述**
安装时KO在初始化控制平台的步骤报错如下：
![620b7e744659900f18692e2960bd9dd](https://user-images.githubusercontent.com/46038902/195799212-7e5374ab-f2ec-4b37-931e-1b1537127fb1.jpg)
实际服务器中，docker与kubelet等/usr/local/bin下面的命令能不带绝对路径执行
![fc843045f2e1281e6ddfd587e90e2df](https://user-images.githubusercontent.com/46038902/195799482-1707d707-49d3-4199-b307-7a6e83ce32d4.jpg)

**Bug 重现步骤(有截图更好)**
1.服务器操作系统centos7.9，内核版本5.18.11-1.el7.elrepo.x86_64，操作系统自带环境变量不支持/usr/local/bin
![image](https://user-images.githubusercontent.com/46038902/195801841-b2ac3522-2f9a-4b76-bf7c-e82947695012.png)

2.手动配置/etc/profile，增加/usr/local/bin的环境变量
![image](https://user-images.githubusercontent.com/46038902/195802245-31fa02a6-c737-4440-9ecf-24d6b24feafd.png)

3.KO安装时，使用root用户安装
![47c657e17f0acd6ad7478cba92813b4](https://user-images.githubusercontent.com/46038902/195802496-c6df9463-76d1-4ef8-a7f1-2d0a02e5d86c.jpg)

4.首次报错后，发现此环境变量问题，删除了集群，再添加的此环境变量
重建集群，重启服务器均无效

5.手动将master和所有node节点下，/usr/local/bin下的二进制可执行文件拷贝的/usr/bin下可规避此问题，放到/usr/local/bin下始终读不到

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
