### ISSUE TITLE
kubepi不能登录

### ISSUE THREAD

**Issue by Zsfzy** [KubeOperator/KubeOperator#523]
**请描述您的问题.**

登录提示认证信息已过期，请重新登录

![微信截图_20221020113900](https://user-images.githubusercontent.com/21311004/196851161-8e140815-b9cf-490d-b140-6bb8fa094095.png)

用kubectl装的非持久化版本

kubernetes VERSION v1.24.2

**Comment by wanghe-fit2cloud** [comment]
可以先尝试使用 docker run 方式起服务，看能不能正常访问
```shell
sudo docker run --privileged -d --restart=unless-stopped -p 80:80 kubeoperator/kubepi-server
```

部署在 K8s 集群的方式，我们在本地环境复现一下问题。

**Comment by Zsfzy** [comment]
docker

> 可以先尝试使用 docker run 方式起服务，看能不能正常访问
> 
> ```shell
> sudo docker run --privileged -d --restart=unless-stopped -p 80:80 kubeoperator/kubepi-server
> ```
> 
> 部署在 K8s 集群的方式，我们在本地环境复现一下问题。

docker可以用

**Comment by wanghe-fit2cloud** [comment]
参考文档中 [kubectl](https://kubeoperator.io/docs/kubepi/install/) 部分，在本地开发环境（k8s version v1.22.12）中部署，未复现不能登录的问题。

**Comment by Zsfzy** [comment]
> 参考文档中 [kubectl](https://kubeoperator.io/docs/kubepi/install/) 部分，在本地开发环境（k8s version v1.22.12）中部署，未复现不能登录的问题。

可能是版本较高的原因 我用的1.25.2
