### ISSUE TITLE
registry

### ISSUE THREAD

**Issue by Lihy6472** [KubeOperator/KubeOperator#528]
在工具中启用registry后，账号密码是什么？我在那里能看到？
![image](https://user-images.githubusercontent.com/116717391/198268317-5783700e-de8a-4d03-89a2-2269bd948197.png)

**Comment by wanghe-fit2cloud** [comment]
仓库要使用 nodeport 端口，不是 5000。
用户密码：admin/kubeoperator

**Comment by Lihy6472** [comment]
默认是https吗？还是需要手动配置https？

**Comment by wanghe-fit2cloud** [comment]
默认 http

**Comment by Lihy6472** [comment]
https需要怎么配置？KubeOperator部署的k8s集群，修改docker.service加入--insecure-registry参数后重启失败，service docker restart不报错，但是执行docker ps 会提示检查docker运行状态
