### ISSUE TITLE
[Question]新安装的k8集群评分为D+

### ISSUE THREAD

**Issue by limitspace7788** [KubeOperator/KubeOperator#531]
**请描述您的问题.**ko版本3.16.2，k8s版本v1.22.12-ko1，3master3worker，安装完成之后集群评分只有D+,如何提升集群的评分等级？
另外，Host IPC is not configured / Host network should not be configured / Host PID is not configured 如何解决？
https://xmywb.oss-cn-beijing.aliyuncs.com/typora/2022/11/09-25-42-33415b0a50532fbf538d0045d55edf25-20221115092542-aaa6ce.png

**Comment by wanghe-fit2cloud** [comment]
如何提升集群评分等级，参考[polaris](https://github.com/FairwindsOps/polaris)官方说明。

**Comment by limitspace7788** [comment]
收到，感谢。
