### ISSUE TITLE
[Bug]velero 定时备份失败，提示“FailedValidation”

### ISSUE THREAD

**Issue by golanghu** [KubeOperator/KubeOperator#536]
**KubeOperator 版本**
3.16.2

**Kubernetes 版本**

1.22.12
**Bug 描述**

velero 定时备份，输入cron表达式（0 0/10 * * * *），确定后提示“FailedValidation”

![image](https://user-images.githubusercontent.com/48056671/207502259-798f8b6b-4932-446f-84f9-57158d33dd07.png)

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by golanghu** [comment]
Sorry，已确定是表达式问题。不是bug。
