### ISSUE TITLE
[Bug]ETCD 恢复后，删除工作负载后（例如deploy），pod无法删除，依然是running状态

### ISSUE THREAD

**Issue by golanghu** [KubeOperator/KubeOperator#537]
**KubeOperator 版本**

3.16.2

**Kubernetes 版本**

1.22.12

**Bug 描述**

ETCD 恢复后，删除工作负载后（例如deploy），pod无法删除，依然是running状态

**Comment by golanghu** [comment]
在这个issues[issues/447](https://github.com/KubeOperator/KubeOperator/issues/447)看到了相同的问题，不知是否已有好的解决办法？

**Comment by Mrliuch** [comment]
也遇到了同样的问题，而且如果快速kubectl get xxx多次可以看到历史的资源

**Comment by Mrliuch** [comment]
> 也遇到了同样的问题，而且如果快速kubectl get xxx多次可以看到历史的资源,如图： ![image](https://private-user-images.githubusercontent.com/38660378/307231302-eeedf06d-d027-4b64-9045-8f85d461bed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzA0MDMsIm5iZiI6MTcwODY3MDEwMywicGF0aCI6Ii8zODY2MDM3OC8zMDcyMzEzMDItZWVlZGYwNmQtZDAyNy00YjY0LTkwNDUtOGY4NWQ0NjFiZWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA2MzUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NWE4ODU0MGY0ZTY2MjQ1MWFjNzc2YjIyMjg3NzdmZTVjNzBlZTcyNWQzMDQ3YjhjMTQyNTZlNmE1ZjY5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RSUm9rEjY-DT-RkOPJp_4Hug_NdR4bc6ppZUQ-khVGw)
> 
> kubelet报错如下： ![image](https://private-user-images.githubusercontent.com/38660378/307231448-5f23b83c-8c01-4ef0-8f69-30c29828bf65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzA0MDMsIm5iZiI6MTcwODY3MDEwMywicGF0aCI6Ii8zODY2MDM3OC8zMDcyMzE0NDgtNWYyM2I4M2MtOGMwMS00ZWYwLThmNjktMzBjMjk4MjhiZjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA2MzUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyOWM3YThiYjRjMmIyY2E3ZTQyNjZjMzVhN2U0ZWY1NzM1YjI2MzhkZWQzZDNkZmJjOTM4YmRiY2M2MjM2ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gqzgjoMk8txkYNwyid4VPrNsKnCBvGsK6aBhMghCdds)

已解决，etcd数据不同步导致的
