### ISSUE TITLE
[Bug]多个Bug反馈，原先用了部署计划做的集群，现在准备迁移到新的vsphere中，如何手动添加主机？

### ISSUE THREAD

**Issue by leqii-com** [KubeOperator/KubeOperator#545]
**KubeOperator 版本**
3.16.1

**Kubernetes 版本**
kubernetes : v1.22.12

**Bug 描述**
1、手动添加主机，然后失败了，无法删除该主机，提示 该主机已经关联项目。
![微信图片_20230201134021](https://user-images.githubusercontent.com/79353242/215961770-04cf4efa-33dc-47cd-a130-2f3b1810bc76.png)

2、“部署计划”添加的集群，添加节点，点完添加后，无法成功创建节点，在“任务中”卡了几天，也无法取消这个任务，这样，添加功能  废了。
![微信图片_20230201134105](https://user-images.githubusercontent.com/79353242/215961889-c53646dd-196f-4cc7-9764-dba20744fa30.png)

3、在“项目”中无法添加自己 添加的主机。
![微信图片_20230201134045](https://user-images.githubusercontent.com/79353242/215961903-4817b77b-b261-4f50-99a1-8291aeb8ea16.png)

4、在项目中无法登录“控制台”，提示用户名密码错误。
![微信截图_20230201134437](https://user-images.githubusercontent.com/79353242/215961984-ff9f0e6c-b198-479e-988c-8c9137415fd3.png)

**Bug 重现步骤(有截图更好)**
图在上面了。

升级可否解决这些bug呀？

**Comment by wanghe-fit2cloud** [comment]
上面四点不是升不升级 KubeOperator 的问题：

1、要删除的主机已经关联了项目，先去项目管理中手动删除资源
2、状态为等待中，说明通过计划任务就没有在vsphere或者openstack中创建出来虚拟机
3、已经提示你了，自动模式创建的集群不支持手动添加主机
4、这里的Dashboard是容器启动的KubePi项目，默认用户名密码: admin/kubepi
