### ISSUE TITLE
[Question]kubeoperator_mysql很耗CPU

### ISSUE THREAD

**Issue by liujunfei980** [KubeOperator/KubeOperator#559]
**请描述您的问题.**
使用kubeoperator v3.15.0版本，發現mysql很耗CPU，不管系統分多少CPU都能吃滿，導致ko web不能正常訪問，如下圖：
![image](https://user-images.githubusercontent.com/35226938/228094059-45bc20d1-235b-4383-a3f0-671eeca8095e.png)
![image](https://user-images.githubusercontent.com/35226938/228094130-c0ac69c0-c92d-4397-9ece-7e82f19e3229.png)
![image](https://user-images.githubusercontent.com/35226938/228094170-1baa897d-fe81-4703-b8c8-e8ec038ce0e7.png)
![image](https://user-images.githubusercontent.com/35226938/228094255-8fc1fd0e-edb4-4fb0-9100-55929f7f8905.png)

**Comment by wanghe-fit2cloud** [comment]
在本地开发测试环境持续观察了一段时间，一直没能复现上述问题。
> 后续版本我们会尝试替换掉 MySQL 8.0，解决 CPU 占用资源较大的问题。
