### ISSUE TITLE
[Question]启用prometheus组件后无法使用servicemonitors.monitoring.coreos.com  CRD 资源

### ISSUE THREAD

**Issue by JonChanGit** [KubeOperator/KubeOperator#564]
**请描述您的问题.**

启用prometheus组件后无法使用servicemonitors.monitoring.coreos.com  CRD 资源

请问是还需要安装啥组件吗，还是自带的prometheus组件不完整

**Comment by wanghe-fit2cloud** [comment]
工具中启用的 prometheus 为 helm 安装，并非 prometheus operator。
