### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by fizzX1** [KubeOperator/KubeOperator#566]
**请描述您的问题.**
现在我们部署了3个master，第一个master节点宕机无法恢复了，发现在kubeoperator中，集群是无法点击操作的，如何配置可以更换kubeconfig文件，使kubeoperator可以正常运维这个集群？可以重新添加master节点替换第一个宕机无法恢复的master节点吗？

**Comment by wanghe-fit2cloud** [comment]
当前版本还不支持动态修改 master 节点数量，后续版本会考虑支持。
#567
