### ISSUE TITLE
KubeOperator v4.x 计划

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#568]
KubeOperator v4.x 将支持 K8s v1.26 及以上版本。

<img width="1457" alt="image" src="https://github.com/KubeOperator/KubeOperator/assets/41712985/6bc1e64d-b806-444a-8ee9-70e154114e5e">

**Comment by lengpucheng** [comment]
很高兴KO的后续大版本计划，在V4版本迭代时是否可以考虑以下特性：
1. 是否可以考虑**ALL IN ONE**的轻量级模式，例如在某些实验室和演示环境下或者资源不充裕的环境下，可以将KO本机也作为集群的其中一个节点，或者仅使用一个节点来部署演示KO+K8S
2. 是否可以加入自定义的插件（或小工具）机制，例如我希望部分集群可以在集群安装完毕后自动执行某些脚本（通过ansible），或者安装嵌入的第三方的工具等。这些应该允许使用者或开发者通过配置文件的方式取动态的添加或者修改，而不是需要重新编译，也应该将部分小工具和插件的安装可以提前到创建集群时插件面板中进行选取。这样对于普通用户来说可以节约不同时段多次进入页面的等待，对于更大规模的系统便于通过API调用的方式集成KO作为创建集群的引擎。
希望这些建议可以在4.X中被考虑

**Comment by jiahuilong** [comment]
希望能够支持对Master节点的增、删维护管理

**Comment by pufaqi** [comment]
礼问：V4.X 还在进行吗？或者说kubeoperator还在维护吗？
