### ISSUE TITLE
kubeopeator 里 nginx 代理 nexus

### ISSUE THREAD

**Issue by spacexnasa** [KubeOperator/KubeOperator#576]
如何使用 kubeoperator 自带的 nginx，代理 kubeoperator 里的 nexus，我修改了  ./conf/nginx.conf 然后再重启，kubeopeartor 里的nginx 一直提示 restarting，我用其他的 nginx 代理，就没问题，同样的写法

**Comment by wanghe-fit2cloud** [comment]
持久化配置文件为：`./conf/nginx.conf`
容器重启还是配置文件的问题，可以查看一下 nginx容器日志来协助定位问题。
> 因为是容器化安装，要重点注意文件路径等问题
