### ISSUE TITLE
[Bug] k8s_install-cni_kube-flannel-ds-jdvrs_kube-system exited状态

### ISSUE THREAD

**Issue by earthGavinLee** [KubeOperator/KubeOperator#578]
**KubeOperator 版本**  3.6.14

**Kubernetes 版本**  1.18.6

**Bug 描述** 容器k8s_install-cni_kube-flannel-ds-jdvrs_kube-system exited状态

**Bug 重现步骤(有截图更好)**
1.
2.
3.
![2](https://github.com/KubeOperator/KubeOperator/assets/8288083/0acea1df-752b-4ea7-98cd-20b4f7952ba4)

![1](https://github.com/KubeOperator/KubeOperator/assets/8288083/043dffff-ce34-4333-b04c-59b397ff4615)
![3](https://github.com/KubeOperator/KubeOperator/assets/8288083/45e683a3-b4d1-4b6c-ab9a-1eab3cfd83bb)

**Comment by wanghe-fit2cloud** [comment]
OOMKilled: Pod 的内存使用超出了 resources.limits 中的限制，被强制杀死。
