### ISSUE TITLE
[Question]openeuler22.03部署集群评分D+

### ISSUE THREAD

**Issue by stdnt-xiao** [KubeOperator/KubeOperator#582]
**请描述您的问题.**
操作系统版本：openeuler22.03
异常信息：
Host network should not be configured
Host PID is not configured
Host IPC is not configured

kubelet状态异常：
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
    Drop-In: /usr/lib/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: active (running) since Sat 2023-09-23 07:59:50 CST; 5h 23min ago
       Docs: https://kubernetes.io/docs/
    Process: 444500 ExecStartPre=/usr/sbin/swapoff -a (code=exited, status=0/SUCCESS)
   Main PID: 444502 (kubelet)
      Tasks: 18 (limit: 60021)
     Memory: 59.5M
     CGroup: /system.slice/kubelet.service
             └─ 444502 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --hostname-over>

9月 23 13:22:39 node001 kubelet[444502]: E0923 13:22:39.434998  444502 summary_sys_containers.go:47] "Failed to get system container stats" err="failed to get cgroup stats for \"/system.slice/docker.serv>
9月 23 13:22:39 node001 kubelet[444502]: E0923 13:22:39.436063  444502 summary_sys_containers.go:47] "Failed to get system container stats" err="failed to get cgroup stats for \"/system.slice/kubelet.ser>
9月 23 13:22:47 node001 kubelet[444502]: E0923 13:22:47.710062  444502 kubelet_node_status.go:586] "Failed to set some node status fields" err="failed to validate nodeIP: node IP: \"192.168.26.196\" not >
9月 23 13:22:49 node001 kubelet[444502]: E0923 13:22:49.470229  444502 cadvisor_stats_provider.go:415] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/system.slice/docker.se>
9月 23 13:22:49 node001 kubelet[444502]: E0923 13:22:49.478589  444502 summary_sys_containers.go:47] "Failed to get system container stats" err="failed to get cgroup stats for \"/system.slice/kubelet.ser>
9月 23 13:22:49 node001 kubelet[444502]: E0923 13:22:49.478719  444502 summary_sys_containers.go:47] "Failed to get system container stats" err="failed to get cgroup stats for \"/system.slice/docker.serv>
9月 23 13:22:57 node001 kubelet[444502]: E0923 13:22:57.817717  444502 kubelet_node_status.go:586] "Failed to set some node status fields" err="failed to validate nodeIP: node IP: \"192.168.26.196\" not >
9月 23 13:22:59 node001 kubelet[444502]: E0923 13:22:59.515704  444502 cadvisor_stats_provider.go:415] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/system.slice/docker.se>
9月 23 13:22:59 node001 kubelet[444502]: E0923 13:22:59.516865  444502 summary_sys_containers.go:47] "Failed to get system container stats" err="failed to get cgroup stats for \"/system.slice/kubelet.ser>
9月 23 13:22:59 node001 kubelet[444502]: E0923 13:22:59.516915  444502 summary_sys_containers.go:47] "Failed to get system container stats" err="failed to get cgroup stats for \"/system.slice/docker.serv>
~

<img width="1120" alt="image" src="https://github.com/KubeOperator/KubeOperator/assets/20313983/76ff953b-944f-4230-8aaa-4ccdb4b37bf3">
<img width="1418" alt="image" src="https://github.com/KubeOperator/KubeOperator/assets/20313983/98194192-2d74-4d9d-8850-36cc8c91acbf">

**Comment by stdnt-xiao** [comment]
[如何提升集群评分等级，参考[polaris](https://github.com/FairwindsOps/polaris)官方说明。](https://github.com/KubeOperator/KubeOperator/issues/531#issuecomment-1314641980)
有查看polaris，但是未检索到合适的解决方法。能提供详细一点的解决该问题的链接？谢谢！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题还是需要参考 polaris 官方说明。
