### ISSUE TITLE
["Unexpect error occur: (1062, "Duplicate entry 'master1.k8scluster.kubeoperator' for key 'name'")"]

### ISSUE THREAD

**Issue by lvxiaohu** [KubeOperator/KubeOperator#63]
同样的集群名称，卸载集群后，重新安装报错 
"Unexpect error occur: (1062, "Duplicate entry 'master1.k8scluster.kubeoperator' for key 'name'")"

![image](https://user-images.githubusercontent.com/29087369/65813578-cfc6b500-e209-11e9-981c-09f082712957.png)

**Comment by KubeOperator** [comment]
2.1 版本已解决。
