### ISSUE TITLE
[Bug: 凭据名称中文支持]

### ISSUE THREAD

**Issue by lvxiaohu** [KubeOperator/KubeOperator#64]
![image](https://user-images.githubusercontent.com/29087369/65825073-fe459e00-e2a4-11e9-9852-458d154af5f8.png)

![image](https://user-images.githubusercontent.com/29087369/65825079-0c93ba00-e2a5-11e9-9819-b8ab73cafe58.png)

**Comment by KubeOperator** [comment]
2.1 版本已解决。
