### ISSUE TITLE
集群-备份/恢复页面 保留分数没有限制最大最小值

### ISSUE THREAD

**Issue by youmu-2019** [KubeOperator/KubeOperator#68]
环境信息：
KubeOperator版本：2.1.0
浏览器版本：Chorme 77.0.3865.90
云提供商：vsphere

测试步骤：
1.登录KubeOperator后，创建集群，安装成功后，设置备份/恢复
2.备份保留分数可以选中 -6，且没有最大值限制，选中-6 后，保存成功。

预计结果：
提示保留分数输入错误信息。
实际结果：
点击保存后，没有提示任何信息，且保存成功。
![图片](https://user-images.githubusercontent.com/56707401/67075480-d4a1d780-f1bd-11e9-8bcc-a78cc97eac19.png)

**Comment by KubeOperator** [comment]
2.1 版本已解决。
