### ISSUE TITLE
【集群】-【健康状态页面】信息显示不友好

### ISSUE THREAD

**Issue by youmu-2019** [KubeOperator/KubeOperator#69]
环境信息：
KubeOperator版本：2.1.0
浏览器版本：Chorme 77.0.3865.90
云提供商：vsphere

测试步骤：
1.登录KubeOperator后，创建集群，安装成功后，单击健康状态，查看健康状态

预计结果：
集群健康状态显示信息完全正确
实际结果：
1.过去半年集群运行状态（可用率0%）表信息显示不全。
2.单击 健康状态选项时，闪现红色状态。
![图片](https://user-images.githubusercontent.com/56707401/67075359-9b696780-f1bd-11e9-9600-afc0d44fee27.png)

**Comment by KubeOperator** [comment]
已经优化。
