### ISSUE TITLE
无法打开集群内置应用，包括k8s DashBoard，Grafana等

### ISSUE THREAD

**Issue by youmu-2019** [KubeOperator/KubeOperator#70]
环境信息：
KubeOperator版本：2.1.0
浏览器版本：Chorme 77.0.3865.90
云提供商：vsphere

测试步骤：
1.登录KubeOperator后，创建集群并安装成功后，单击集群内置应用
2.本地配置内置应用的DNS后，单击 k8s Dashboard 链接，Grafana 链接等

预计结果：
可以打开K8s Dashboard 页面，Grafana Dashboard 应用页面
实际结果：
无法打开K8s Dashboard 页面，Grafana Dashboard 应用页面。提示404 信息。

**Comment by KubeOperator** [comment]
已经解决。
