### ISSUE TITLE
手动模式创建集群时，配置节点页面看不到主机列表

### ISSUE THREAD

**Issue by youmu-2019** [KubeOperator/KubeOperator#71]
环境信息：
KubeOperator版本：2.1.0
浏览器版本：Chorme 77.0.3865.90
云提供商：vsphere

测试步骤：
1.登录KubeOperator后，添加5个主机为手动创建使用
2.集群页面创建手动模式部署的集群，在配置节点步骤，选择master和worker主机时，看不到主机下拉菜单，无法选择主机

预期结果：
可以看见手动添加的所有主机
实际结果：
在配置节点步骤，选择master和worker主机时，看不到主机下拉菜单，无法选择主机
![图片](https://user-images.githubusercontent.com/56707401/67084079-dd4ed980-f1ce-11e9-99ec-9442e33d87fe.png)

**Comment by KubeOperator** [comment]
已经解决。
