### ISSUE TITLE
无法使用Openstack创建集群

### ISSUE THREAD

**Issue by youmu-2019** [KubeOperator/KubeOperator#72]
环境信息：
KubeOperator版本：2.1.0
浏览器版本：Chorme 77.0.3865.90
云提供商：vsphere

测试步骤：
1.登录KubeOperator后，添加云提供商为openstack的区域，可用区以及部署计划
2.集群页面，创建选择云提供商为openstack的集群
3.概览页面，安装该集群

预期结果：
成功安装集群
实际结果：
安装失败

**Comment by KubeOperator** [comment]
未能重现。
