### ISSUE TITLE
集群选择vsphere云提供商，配置存储时显示cinder存储类型

### ISSUE THREAD

**Issue by youmu-2019** [KubeOperator/KubeOperator#73]
环境信息：
KubeOperator版本：2.1.0
浏览器版本：Chorme 77.0.3865.90
云提供商：vsphere

测试步骤：
1.登录KubeOperator后，添加云提供商为vsphere的区域，可用区以及部署计划
2.集群页面，创建集群时，选择上述部署计划，配置存储页面，选择cinder存储类型，完成后，安装集群

预期结果：
配置存储页面，cinder存储类型应该不可见
实际结果：
选择cinder存储类型后，集群安装失败。

**Comment by KubeOperator** [comment]
已经解决。
