### ISSUE TITLE
添加主机失败，但仍显示在主机列表里

### ISSUE THREAD

**Issue by youmu-2019** [KubeOperator/KubeOperator#74]
环境信息：
 KubeOperator版本：2.1.0 
浏览器版本：Chorme 77.0.3865.90 
云提供商：vsphere
测试步骤： 
1.登录KubeOperator后，添加凭据，凭据的密码是错误的
2.主机页面，添加主机，使用上诉错误密码的凭据
3.添加主机失败后，查看主机列表信息
预期结果：
提示添加主机失败，删除该主机信息 
实际结果： 
提示添加主机失败，但是该主机仍显示在主机列表里

**Comment by KubeOperator** [comment]
2.1 版本已解决。
