### ISSUE TITLE
新创建集群，集群状态是ERROR

### ISSUE THREAD

**Issue by youmu-2019** [KubeOperator/KubeOperator#76]
环境信息：
 KubeOperator版本：2.1.0 浏览器版本：
Chorme 77.0.3865.90 
云提供商：vsphere
测试步骤： 
1.登录KubeOperator后，添加区域，可用区和部署计划 
2.集群页面，创建集群 
3.概览页面，查看集群状态
预期结果：
集群状态应该是就绪中
实际结果：
集群状态：ETCD，kube-apiserver和kube-controller 状态都是Error

**Comment by KubeOperator** [comment]
2.1 版本已解决。
