### ISSUE TITLE
登录 Docker Registry 但不知道账号 / 密码

### ISSUE THREAD

**Issue by Wang-Kai** [KubeOperator/KubeOperator#81]
<img width="796" alt="屏幕快照 2019-10-22 下午9 13 38" src="https://user-images.githubusercontent.com/13144386/67289237-de567280-f510-11e9-89e2-d8a70bc49cb6.png">

**Comment by wanghe-fit2cloud** [comment]
username: admin
password: admin123
weave scope的用户密码同上

**Comment by Lihy6472** [comment]
在部署的服务器内登陆提示401，认证失败
![image](https://user-images.githubusercontent.com/116717391/198265652-c05b9656-f8de-4dc1-acac-a95f98907b77.png)
