### ISSUE TITLE
[v2.1]手动部署模式下，创建集群是配置节点栏目无法正常显示 Bug1

### ISSUE THREAD

**Issue by lvxiaohu** [KubeOperator/KubeOperator#93]
![image](https://user-images.githubusercontent.com/29087369/67647948-10336300-f96f-11e9-9cf5-40192fcb00c8.png)
![image](https://user-images.githubusercontent.com/29087369/67647957-17f30780-f96f-11e9-8468-bc07bc66a87c.png)

worker数量改为2时，就可以正常显示 
![image](https://user-images.githubusercontent.com/29087369/67647977-2b9e6e00-f96f-11e9-80ec-aea14885c947.png)
![image](https://user-images.githubusercontent.com/29087369/67647984-32c57c00-f96f-11e9-96d9-0bcdfe213cc7.png)

**Comment by KubeOperator** [comment]
已经解决。
