### ISSUE TITLE
创建集群配置节点页面空白

### ISSUE THREAD

**Issue by wangzhengkun** [KubeOperator/KubeOperator#94]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
V2.1
**Bug 描述**
简要描述您碰到的问题
手动模式创建集群 配置节点页面空白
**Bug 重现步骤**
手动模式创建集群
worker数量选1
点击下一步

**期待的正确结果**
worker数量为3的时候正常

**截图**
![image](https://user-images.githubusercontent.com/12987937/67648676-58ec1b80-f971-11e9-8d05-da67bf5ffe87.png)

**Comment by KubeOperator** [comment]
2.1.36 版本已经解决。
