### ISSUE TITLE
没有在 Openstack 一键部署 K8s 集群的文档 

### ISSUE THREAD

**Issue by addressone** [KubeOperator/KubeOperator#97]
**请描述您的需求或者改进建议.**
没有在 Openstack 一键部署 K8s 集群的文档 

**请描述你建议的实现方案**
提供在 Openstack 一键部署 K8s 集群的文档

**Comment by KubeOperator** [comment]
已经提供，请参考：https://docs.kubeoperator.io/kubeoperator-v2.1/userguide-openstack
