### ISSUE TITLE
手动模式下不能增加 worker 数量

### ISSUE THREAD

**Issue by maninhill** [KubeOperator/KubeOperator#98]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
2.1.36

**Bug 描述**
简要描述您碰到的问题
手动模式下不能增加 worker 数量

**Bug 重现步骤**
1.  安装 KubeOperator
2.  部署K8s 集群，手动模式
3.  准备一新主机
4.  扩容 Worker -> 失败

**期待的正确结果**
正确情况下应该是什么样的？
可以扩容成功

**截图**
如果有截图，请附上截图.

**Comment by KubeOperator** [comment]
最新本fix

**Comment by KubeOperator** [comment]
2.1.42 已解决。

**Comment by maninhill** [comment]
已验证，赞。
