### ISSUE TITLE
创建集群-配置检查步骤检查操作系统功能无效，没有正确判断是centos 7.5 版本的系统

### ISSUE THREAD

**Issue by youmu-2019** [KubeOperator/KubeOperator#99]
**KubeOperator 版本**
您所使用的 KubeOperator 版本是？
2.1.36

**Bug 描述**
简要描述您碰到的问题
创建集群-配置检查步骤检查操作系统功能无效，没有正确判断是centos 7.5 版本的系统
**Bug 重现步骤**
1.  添加一个主机，操作系统为centos 7.5 
2. 创建集群时，配置检查步骤检查操作系统功能无效，没有正确判断是centos 7.5 版本的系统，仍通过检查继续下一步。

**期待的正确结果**
正确情况下应该是什么样的？
配置检查步骤正确检查出操作系统版本，提示 不支持centos7.6 版本以下等相关信息。
**截图**
如果有截图，请附上截图.

**Comment by admxj** [comment]
我也遇到了这样的问题, 以下是以下是我的截图
![企业微信截图_a7500e25-b497-404a-9727-26ff81bb3ff3](https://user-images.githubusercontent.com/15245021/67821149-f0c74200-faf6-11e9-97bf-2b00422d8392.png)
![企业微信截图_a13e5217-3509-4870-97a1-e73d7884a4c4](https://user-images.githubusercontent.com/15245021/67821185-118f9780-faf7-11e9-89d0-c58e4fedb200.png)

**Comment by KubeOperator** [comment]
已经解决。
